### ISSUE TITLE
Vimeo: an uploaded video is "in progress" status after upload

### ISSUE THREAD

**Issue by MiroslavMerinsky** [tus/tus-js-client#101]
Hi,

Could you help me with one issue related to uploading to Vimeo server?
After upload everything in browser looks good. On console there is message "video has been uploaded", the queries to Vimeo seems good too, but the video is still in progress status and not visible on Vimeo.

https://drive.google.com/file/d/1i4diwqcxCjs62jlAUrNHIAXyHHgwgV41/view?usp=sharing
https://drive.google.com/file/d/1E4bRcKSASxrP3xiid-MEeTJulYUPMxCJ/view?usp=sharing
https://drive.google.com/file/d/1ZPDLydugQaZYi66_-Q-xh78OEUXgBJw5/view?usp=sharing

> JS
    var upload = new tus.Upload(file, {
    uploadUrl: data.uploadUrl,
    overridePatchMethod: false,
    retryDelays: [0, 1000, 3000, 5000],
    onError: function(error) {
        console.log("Failed because: " + error)
    },
    onProgress: function(bytesUploaded, bytesTotal) {
        var percentage = (bytesUploaded / bytesTotal * 100).toFixed(2);
        console.log(bytesUploaded, bytesTotal, percentage + "%");
    },
    onSuccess: function() {
        console.log("Upload %s from %s", upload.file.name, upload.url);
    }
});
// Start the upload
upload.start();

Thank you.

Best Regards,

Miroslav

**Comment by kvz** [comment]
We're playing around with Vimeo uploads using Uppy, and in the offchance it helps your case, here's some code that works for us https://github.com/transloadit/uppy-vimeo-thing/blob/master/Vimeo.js

**Comment by MiroslavMerinsky** [comment]
Could you send link again? Unfortunately is invalid.

Thank you.

**Comment by MiroslavMerinsky** [comment]
There was issue on the Vimeo. I solved it with Vimeo support. Sorry for the mistake.
