### ISSUE TITLE
Support IE9?   Any examples?   thanks

### ISSUE THREAD

**Issue by cheerful-li** [tus/tus-js-client#104]
In README.md I see support for ie 9,   but the example code ```var file = e.target.files[0]``` will failed in IE9

**Comment by Acconut** [comment]
Thank you for bringing this up. I wasn't aware that the File API is not present in IE9, so the examples would indeed not work there. We should remove that platform from our automated tests.

**Comment by Acconut** [comment]
The list of supported browsers and automated tests has been updated, so this can be closed.
