### ISSUE TITLE
Request header field Tus-Resumable is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by fabiodiniz** [tus/tus-js-client#105]
I'm implementing an upload process to Vimeo using the resumable approach, using the upload link returned from Vimeo API (using Tus approach). Then I setup the Tus instance using the received upload link in the uploadUrl parameter. Then after starting, I received the following error:

> Request header field Tus-Resumable is not allowed by Access-Control-Allow-Headers in preflight response.

Is that URL (upload link received from Vimeo) the correct one? Should I use the paremeter uploadUrl or endpoint?

**Comment by Acconut** [comment]
> Is that URL (upload link received from Vimeo) the correct one?

I am not too familiar with the Vimeo API but from what I have heard from other people, I assume this is the correct URL.

> Should I use the paremeter uploadUrl or endpoint?

As far as I know, this should be supplied as the uploadUrl.

If the problem persists, please submit more details about your setup.

**Comment by fabiodiniz** [comment]
The project is a SPA using VueJS and Vuex.

The process starts with a request to our API that makes another request for the Vimeo API, which receives the upload link. With the method below we initialize the Tus Client using the upload link from Vimeo's API:

<img width="892" alt="screen shot 2018-03-21 at 20 34 27" src="https://user-images.githubusercontent.com/10063057/37743137-5fdc8206-2d47-11e8-8962-143437c3ad9c.png">
<img width="645" alt="screen shot 2018-03-21 at 20 45 37" src="https://user-images.githubusercontent.com/10063057/37743442-d957c400-2d48-11e8-8f9d-03918a304fc2.png">

**Comment by fabiodiniz** [comment]
The project is a SPA using VueJS and Vuex.

The process starts with a request to our API that makes another request for the Vimeo API, which receives the upload link. With the method below we initialize the Tus Client using the upload link from Vimeo's API:

<img width="893" alt="screen shot 2018-03-21 at 20 48 40" src="https://user-images.githubusercontent.com/10063057/37743531-47513964-2d49-11e8-8731-42c9e58a691a.png">

When I try to start an upload, that's what I got:

<img width="498" alt="screen shot 2018-03-21 at 20 51 43" src="https://user-images.githubusercontent.com/10063057/37743639-d07aa964-2d49-11e8-80c9-3dec1a442df7.png">

<img width="653" alt="screen shot 2018-03-21 at 20 52 10" src="https://user-images.githubusercontent.com/10063057/37743645-d5b79f22-2d49-11e8-8acb-ab0dd9f7732a.png">

<img width="1035" alt="screen shot 2018-03-21 at 20 52 23" src="https://user-images.githubusercontent.com/10063057/37743649-d8ac7e46-2d49-11e8-9158-032239ae4413.png">

Any idea what I'm doing wrong? :)

**Comment by fabiodiniz** [comment]
Is this issue related with this one (#89)? It looks like it is a problem with Vimeo's implementation of Tus. Theoretically, this URL that I'm using in `uploadUrl` is a created upload URL (something after this step - https://github.com/tus/tus-resumable-upload-protocol/blob/master/protocol.md#creation - which is handled by Vimeo's API), right?

What I'm understanding is that the client is doing a preflight request for a `HEAD` request, which should check the upload progress and then start upload with `PATCH` requests, based on `Upload-Offset` received from the first response's header. But the server answered that it doesn't allow either `HEAD` method or `Tus-Resumable` header. Is it ok, to check the status before it has started? Is this an client or a server error?

**Comment by fabiodiniz** [comment]
Our mistake. The problem was the Vimeo's API version. Seems the default API used is not 3.4. So setting the API version to 3.4 resulted in a different response from Vimeo, which seems to have worked.

**Comment by Acconut** [comment]
I am glad to hear that you working it out :+1: And thanks for letting us know the solution

**Comment by gabriellimoni** [comment]
how did you set the API version?

**Comment by Acconut** [comment]
@gabriellimoni I have never use the Vimeo API but apparently you can use the Accept header to specific the version (see https://developer.vimeo.com/api/common-formats#using-the-accept-header).

**Comment by gabriellimoni** [comment]
Thanks!

Em qui, 21 de fev de 2019 18:57, Marius <notifications@github.com> escreveu:
