### ISSUE TITLE
Update NPM to v1.5

### ISSUE THREAD

**Issue by fabiodiniz** [tus/tus-js-client#109]
I guess there's something missing for the v1.5 release to show up on NPM. Every time I setup a new environment, I need to download it from GitHub and overwrite it in node_modules folder, because the last release available is 1.4.5.

![screen shot 2018-04-06 at 11 20 13](https://user-images.githubusercontent.com/10063057/38426244-82cf9ed2-398c-11e8-8933-8de431f5948e.png)

Thanks.

**Comment by Acconut** [comment]
Thank you for letting us know, we just pushed 1.5.0 to NPM. I don't know how we missed out on that.

**Comment by fabiodiniz** [comment]
Thank u :)
