### ISSUE TITLE
not working with tus-node-server

### ISSUE THREAD

**Issue by djsg** [tus/tus-js-client#110]
I have tried tus-js-client with my Laravel PHP code. It works if I put upload endpoint to https://master.tus.io/files/. If I put endpoint to my local machine, which runs a standalone tus-node-server (127.0.0.1:8000), I have the following exception:

Uncaught DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
at Upload._createUpload (http://10.217.131.239:8080/tus-js-lib/dist/tus.js:569:11)
at Upload.start (http://10.217.131.239:8080/tus-js-lib/dist/tus.js:457:12)
at HTMLInputElement.startUpload (http://10.217.131.239:8080/tus-js-lib/demo.js:106:10)

What went wrong with my local TUS server? How can I debug?

**Comment by Acconut** [comment]
It looks like the `endpoint` that you provided to `new tus.Upload` is not a valid URL, so tus-js-client is not able to create an upload. What value does this parameter have in your situation?

**Comment by djsg** [comment]
I ran a standalone tus-node-server, which has the following code:
`const tus = require('tus-node-server');

const server = new tus.Server();
server.datastore = new tus.FileStore({
    path: './files'
});

const host = '127.0.0.1';
const port = 8000;
server.listen({ host, port }, () => {
    console.log(`[${new Date().toLocaleTimeString()}] tus server listening at http://${host}:${port}`);
});`

It prints out "[09:33:58] tus server listening at http://127.0.0.1:8000" when getting started; and I use "http://127.0.0.1:8000" as the endpoint for tus_js_client.

**Comment by Acconut** [comment]
Can you please try using http://127.0.0.1:8000/files as the endpoint? tus-node-server is only accepting uploads at the `/files` path.

**Comment by djsg** [comment]
yes, it is working now. Previously I tried http://127.0.0.1:8000/files before, but I used './files' as storage path not knowing '/file' is relevant to tus-node-server running location.
Now I have two more questions:
(1) how can I use https endpoint? I have a guess: maybe I don't need to change the tus-js-client and tus-node-server.js at all, I just need to change http to https in endpoint. At browser side, browser will take care of https encryption, at server side, I should use a web server like Apache2 to redirect https traffic to the tus-node-server. Is it a correct way?
(2) Now the server is standalone, how can I embed it into my PHP web server?

**Comment by Acconut** [comment]
> yes, it is working now. Previously I tried http://127.0.0.1:8000/files before, but I used './files' as storage path not knowing '/file' is relevant to tus-node-server running location.

The `path` property defines under which URL tus-node-server is accessible while the `directory` property defines where the files will be stored on disk: https://github.com/tus/tus-node-server/blob/master/lib/stores/FileStore.js#L27

>  I have a guess: maybe I don't need to change the tus-js-client and tus-node-server.js at all, I just need to change http to https in endpoint. At browser side, browser will take care of https encryption, at server side, I should use a web server like Apache2 to redirect https traffic to the tus-node-server. Is it a correct way?

Yes, exactly that is correct. You can find example configurations for Apache and Nginx at https://github.com/tus/tusd/tree/master/docs. Even though they are in the tusd repository, they can be used for tus-node-server as well with minimal changes.

> Now the server is standalone, how can I embed it into my PHP web server?

tus-node-server allows you to listen to events, e.g. when an upload is finished: https://github.com/tus/tus-node-server#events. From those event listeners you can then send a request to your PHP web server to do further processing.

**Comment by djsg** [comment]
I took a looked at both Apache and Nginx configuration files.
For Apache, there are lines 
`        # Pass requests to tusd server
        ProxyPass /files http://localhost:1080/files
        ProxyPassReverse /files http://localhost:1080/files`
I basically understand.
However, in Nginx config file, there is nothing similar. I wonder how Nginx knows what traffic to forward to tus server. It cannot be all the HTTPS traffice, because I have other web server running.

**Comment by djsg** [comment]
Is it in location?
 `
location / {
        # Forward incoming requests to local tusd instance
        proxy_pass http://localhost:8080;
...
}
`

**Comment by Acconut** [comment]
> Is it in location?

Yes, it is.

> got some error like

What does the log output from tus-node-server look like when you start it using the `DEBUG=*` environment variable?

**Comment by djsg** [comment]
can you be more specific on how to enable debug mode?
I use nodejs tus_node_server.js to start. It runs in a Ubuntu OS.
Now I have that HTTP 412 error even without running proxy in between.

Is there good document on how to write the server code like catch events, and errors, etc?

**Comment by rictorres** [comment]
@djsg he meant something like:

- suppose you start your app with `npm start`
- to enable debug logging you'd do `DEBUG=* npm start`

**Comment by djsg** [comment]
After some try-and-error, I believe I have managed to make tus-js-client to work with tus-node-server through nginx proxy.
However, since my server security cert is self-signed; line 499 of upload.js xhr.send(...) function hit net:ERR_CERT_AUTHORITY_INVALID error.
Is there a better way than disabling it in browser?

**Comment by djsg** [comment]
after disable security check in chrome, I got that 412 error code again. 
Here is the tus-node-server print to screen msg:
  tus-node-server Invalid upload-metadata header: filename N3o5MjAteDY0Lm1zaQ==,filetype

**Comment by djsg** [comment]
Hi all,

thanks for your help. Since my original problem is resolved. I will close this issue.
