### ISSUE TITLE
Passing extra data from client to server

### ISSUE THREAD

**Issue by ivanghisleni** [tus/tus-js-client#111]
Hi 

is it possible to passing extra-data to server, for example the destination folder?

thanks

**Comment by rictorres** [comment]
yes, it is. you can send it inside the `metadata` object:

```
new tus.Upload(file, {
    // ...
    metadata: {
        filename: file.name,
        filetype: file.type,
        destination: '/path/to/folder',
    },
    // ...
})
```

**Comment by ivanghisleni** [comment]
I found the same solution, the problem was reading this data from tus-php but I've found how to get this param.

Thank you
Ivan
