### ISSUE TITLE
getting fingerprint value

### ISSUE THREAD

**Issue by ivanghisleni** [tus/tus-js-client#112]
Hi 

is it possible getting the fingerprint key while tus-js is uploading?

thanks
Ivan

**Comment by Acconut** [comment]
No, there is currently no documented way to access the used fingerprint. May I ask what you are intending to do?
That being said, you can access the internal `_fingerprint` value (https://github.com/tus/tus-js-client/blob/master/lib/upload.js#L45) but there are **absolutely no** guarantees that this property will not change in future releases and break your app!

**Comment by ivanghisleni** [comment]
OK, I find another way using backend functionality.

Thanks

**Comment by mb21** [comment]
I'm also wondering whether there is a way to get the fingerprint. The reason is that I would like to use the fingerprint as a filename when uploading a user-supplied file to [supabase storage](https://supabase.com/docs/guides/storage/uploads/resumable-uploads).

That way, we could keep `removeFingerprintOnSuccess: false` and not set the `x-upsert` header, which supabase discourages because of the CDN lag.

**Comment by Acconut** [comment]
> The reason is that I would like to use the fingerprint as a filename when uploading a user-supplied file to [supabase storage](https://supabase.com/docs/guides/storage/uploads/resumable-uploads).

The fingerprint of a file may not be unique as it is calculated based on the file's meta data and not on the actual content. I am not sure if these collisions, where two different files have the same fingerprint, could lead to problem in your case, but I wanted to point this out.

> That way, we could keep `removeFingerprintOnSuccess: false` and not set the `x-upsert` header, which supabase discourages because of the CDN lag.

I don't understand this, but I am also not familiar with Supabase's services. This might also not be relevant for answering your question.

> Because we would need the fingerprint to supply it to the `Upload` constructor, what would be ideal, is if the default `fingerprint` function would be exported by tus-js.

The default fingerprinting method is exported via `tus.defaultOptions.fingerprint`, so there is no need to duplicate the code :)
