### ISSUE TITLE
download link in tus js client demo page

### ISSUE THREAD

**Issue by djsg** [tus/tus-js-client#116]
I assume tus server does not support HTTP download.
If it is true, how does the download link in the demo page (https://tus.io/demo.html) work?
Following tus-js-cleint/index.html, I implemented my tus upload page: the upload works well; however, when user clicks links to uploaded files, it shows "Not found".

**Comment by Acconut** [comment]
The tus protocol does not specific anything about downloading files. However, some server, such as https://github.com/tus/tusd which powers the demo at https://tus.io/, support downloads. Other servers, most notably https://github.com/tus/tus-node-server/, do not support downloads out of the box, which can cause the "Not found" errors you are seeing. So it depends on what server you are using. How does your setup look like?

**Comment by djsg** [comment]
I use tus-node-server.
Actually I have a web server, which can handle downloading job. However, the demo page of tus js client uses endpoint in both upload and download cases, if I am not wrong. I want to change download link pointing to my web server. Which JS file shall I look into?

**Comment by Acconut** [comment]
> I want to change download link pointing to my web server. Which JS file shall I look into?

If you are referring to the demo, these lines are responsible for showing the download button to the user: https://github.com/tus/tus-js-client/blob/552db742b519dda40f02eda551e325001bf15105/demo/demo.js#L94-L99

**Comment by djsg** [comment]
@Acconut 
Thank you for taking time to answer my questions. Greatly appreciate it
I am new to JavaScript. My questions may be rather basic.

But I cannot find onclick function for that anchor variable, which links to each individual upload file, I guess. Where is anchor defined?

That anchor has only one href member variable, pointing to TUS upload link to the particular uploaded file. If it is only used for download, I can change it to my web server's link to that same file.

**Comment by Acconut** [comment]
> But I cannot find onclick function for that anchor variable, which links to each individual upload file, I guess. Where is anchor defined?

For anchor elements (which have the HTML tag `a`) you don't have to define an onclick listener. It is enough to set the `href` attribute. This way the browser will automatically send the user to the defined link if the anchor is clicked.

> If it is only used for download, I can change it to my web server's link to that same file.

Yes, that's correct, if I understood you correctly.
