### ISSUE TITLE
Upload by readStream in electron get error

### ISSUE THREAD

**Issue by ythvg** [tus/tus-js-client#117]
**Uncaught Error: source object may only be an instance of File or Blob in this environment**

**Comment by Acconut** [comment]
I don't have much experience using recent versions of Electron, so I am unsure what could cause this error. Can you share your code responsible for calling tus-js-client?

**Comment by ythvg** [comment]
well, I resolved this problem, I find that the library **dist/tus.js** is only worked in browser environment, but the import from the npm is worked only in node.js environment

**Comment by Acconut** [comment]
I am glad to hear that you were able to figure it out by yourself. You are right that tus-js-client might get confused since in Electron's renderer process both the Node.js APIs and browser APIs are available. I am going to close this issue. Feel free to open another one if you have more questions.
