### ISSUE TITLE
Get request data (URL, etc)

### ISSUE THREAD

**Issue by raphaelarias** [tus/tus-js-client#123]
Hi, thanks for the awesome package.

We are trying to integrate with Cloudflare Stream. After the upload starts, the URL changes, including then, the videoId. More info in the Cloudflare docs below.

https://developers.cloudflare.com/stream/getting-started/uploading-command-line/#uploading-your-video

This ID cannot be set, and it's required to later retrieve more info about the video.

Is there anyway to access the request information so we can get this video from the upload URL?

Thank you

**Comment by Acconut** [comment]
Thanks for the kind words. I have never worked with Cloudflare Stream, so I can't help you with anything specific there.

However, it seems as if the video ID is part of the upload URL. The upload URL can be accesses by the `url`property (https://github.com/tus/tus-js-client#tusuploadurl) after an upload has been started. From this URL you should be able to extract the video ID using a simple regular expression, I think.

**Comment by prestonp** [comment]
I adapted the existing node.js example for use with Cloudflare Stream. The video ID is available through the upload.url as @Acconut previously mentioned.

Install the tus client
```
npm install tus-js-client
```

Set up a index.js and configure your endpoint using your Cloudflare account and appropriate auth headers:

```
var fs = require("fs");
var tus = require("tus-js-client");

var path = __dirname + "/test.mp4";
var file = fs.createReadStream(path);
var size = fs.statSync(path).size;

var options = {
  endpoint: "https://api.cloudflare.com/client/v4/accounts/<CLOUDFLARE ACCT ID>/media",
  headers: {
    'x-auth-email': '<CLOUDFLARE EMAIL>',
    'x-auth-key': '<CLOUDFLARE AUTH KEY>',
  },
  resume: true,
  metadata: {
    filename: "test.mp4",
    filetype: "video/mp4"
  },
  uploadSize: size,
  onError: function (error) {
    throw error;
  },
  onProgress: function (bytesUploaded, bytesTotal) {
    var percentage = (bytesUploaded / bytesTotal * 100).toFixed(2);
    console.log(bytesUploaded, bytesTotal, percentage + "%");
  },
  onSuccess: function () {
    console.log("Upload finished:", upload.url);
    var index = upload.url.lastIndexOf("/") + 1;
    var mediaId = upload.url.substr(index)
    console.log("Media id:", mediaId);
  }
};

var upload = new tus.Upload(file, options);
upload.start();
```

Run the upload

```
node index.js
```

**Comment by Acconut** [comment]
@prestonp Thank you for the example code! I am going to close this issue since the question was answered.
