### ISSUE TITLE
Ignoring lock if you retry

### ISSUE THREAD

**Issue by freost** [tus/tus-js-client#130]
Hi,

We're currently testing tus to see if it will fit our needs but we're having a weird issue.

I'm uploading a file in one tab, then open a second tab and try to upload the same file. I get `Failed because: Error: tus: upload is currently locked; retry later, originated from request (response code: 423, response text: )
Do you want to retry?` as expected. I click on `ok` and get the same error again, still as expected.

But if I click on cancel and try again to upload the same file it'll start a new upload using a new file id. Is this working as intended?

Tested in Safari and Chrome.

**Comment by freost** [comment]
I figured out why this happens. The fingerprint gets deleted from local storage when you click cancel.

**Comment by Acconut** [comment]
Glad to read that you figured it out on your own :+1:
