### ISSUE TITLE
Cancel/Terminate upload

### ISSUE THREAD

**Issue by Badabum** [tus/tus-js-client#135]
Hi, 
Current interface of the `Upload` object defines `abort` function that should be used to stop the uploading, but then this particular upload can be resumed. I'm wondering if there is a support for the [Termination](https://tus.io/protocols/resumable-upload.html#termination) extension in this library. The scenario is pretty simple - I'd like to call smth like `cancel()` (or maybe `terminate`) to abort the upload and free all the resources associated with it. If there isn't such possibility I'd be thankful for any workarounds.
Any answer much appreciated.

**Comment by Badabum** [comment]
Renamed title

**Comment by Badabum** [comment]
Ah, I guess I can use `Upload.url` and construct the `DELETE` request by my own to do that. Anyway, will be thankful for suggestions :)

**Comment by Acconut** [comment]
As you correctly noted, tus-js-client does not have native support for the Termination extension built in. However, you can issue the DELETE request directly on your own, as you already wrote. So no, there is currently no other way to terminate an upload from the browser.

**Comment by Badabum** [comment]
@Acconut thanks for the reply. Closing the issue.

**Comment by kvz** [comment]
We're considering this functionality in Uppy (https://github.com/transloadit/uppy/issues/1544) and think it might be nice to let tus-js-client worry about the actual request to make the abstraction non-leaky, and have all requests play by the same rules (perhaps the tus-js-client sets specific timeouts, logging, retries, etc) what do you think @Acconut, open to have this part of the tus-js-client? If so we can re-open and maybe ask @ifedapoolarewaju to take this on if he has more time

**Comment by Acconut** [comment]
Sure, if @ifedapoolarewaju wants to give it a try. I would recommend opening a new issue where we can talk about the proper API design for it because I am not yet sure whether it should be `tus.terminate(uploadUrl)` or `tus.Upload#terminate()`.

**Comment by ifedapoolarewaju** [comment]
> I would recommend opening a new issue where we can talk about the proper API design

@Acconut would you still recommend that we discuss this in a separate issue or should we just do that here since this issue has already been re-opened?

**Comment by Acconut** [comment]
> would you still recommend that we discuss this in a separate issue

Yes, please.

**Comment by Acconut** [comment]
Closing this since it's implemented in #159
