### ISSUE TITLE
Transfer is finished although it was aborted

### ISSUE THREAD

**Issue by mass85** [tus/tus-js-client#138]
Steps to reproduce:

1. Assuming that TUS server is at 10.4.0.1, block all incoming packets from the server `iptables -I INPUT -s 10.4.0.1 -j DROP`
2. Start upload. `netstat` will show that corresponding TCP connection is in `SYN_SENT` state.
3. After i.e. 30seconds call `upload.abort()`
4. Accept all incoming packets from the server `iptables -I INPUT -s 10.4.0.1 -j ACCEPT`

In result file will be uploaded and succeed callback called. I would expect the opposite - file is not uploaded and no callback called (according to the documentation of `upload.abort()`)

tus-js-client version based on 1.4.5.

**Comment by Acconut** [comment]
I am not able to reproduce the problem as you described it using following scripts:

```js
var fs = require("fs");
var tus = require("tus-js-client");

var path = "/dev/zero";
var file = fs.createReadStream(path);
var size = 10 * 1000 * 1000; // 10 MB

var options = {
  endpoint: "https://master.tus.io/files/",
  resume: true,
  metadata: {
      filename: "README.md",
      filetype: "text/plain"
  },
  uploadSize: size,
  onError: function (error) {
    throw error;
  },
  onProgress: function (bytesUploaded, bytesTotal) {
    var percentage = (bytesUploaded / bytesTotal * 100).toFixed(2);
    console.log(bytesUploaded, bytesTotal, percentage + "%");
  },
  onSuccess: function () {
    console.log("Upload finished:", upload.url);
  }
};

var upload = new tus.Upload(file, options);
upload.start();

setTimeout(function() {
  console.log("Aborting upload");
  upload.abort();
}, 3 * 1000);
```

First of all, if I just run this script without any iptables rules, it properly stops the upload after 3s. However, when I use the iptables rule to drop all incoming packages, the `upload.abort()` call immediately causes following error to appear:

```
Error: tus: failed to create upload, caused by Error: socket hang up, originated from request (response code: 0, response text: )
    at new DetailedError (/home/marius/workspace/tus/tus-js-client/lib.es5/error.js:22:87)
    at Upload._emitXhrError (/home/marius/workspace/tus/tus-js-client/lib.es5/upload.js:260:23)
    at Request.xhr.onerror (/home/marius/workspace/tus/tus-js-client/lib.es5/upload.js:385:16)
    at ClientRequest.<anonymous> (/home/marius/workspace/tus/tus-js-client/lib.es5/node/request.js:92:15)
    at ClientRequest.emit (events.js:180:13)
    at TLSSocket.socketCloseListener (_http_client.js:368:9)
    at TLSSocket.emit (events.js:185:15)
    at _handle.close (net.js:541:12)
    at TCP.done [as _onclose] (_tls_wrap.js:379:7)
```

Could this be a OS-specific issue? What does your setup look like?

**Comment by mass85** [comment]
When I used your script, I could not reproduce problem either. However it was enough to add one option to reproduce: `retryDelays: [0, 1000, 3000, 5000, 10000]`.

**Comment by Acconut** [comment]
Ah, thanks. The `retryDelays` were the missing piece in the puzzle. I was able to reproduce it locally and found a fix for it. Would you mind testing this patch before a release to see if it also helps with your problem?

**Comment by mass85** [comment]
I did not observe any change in behavior, but maybe this is because I don't know how to install such a dev version properly. Could you publish it to npm?

**Comment by Acconut** [comment]
Ok, no worries. I pushed 1.6.1 to NPM for you to test it out.

**Comment by devarsh** [comment]
I am facing a similar issue, upload is not aborting despite calling abort, it finishes regardlessly.

```js
 instance = new tus.Upload(fd, {
      endpoint: "http://localhost:8080/files/",
      resume: true,
      removeFingerprintOnSuccess: true,
      /*retryDelays: [0, 3000, 5000, 10000, 20000],*/
      metadata: {
        filename: fd.name,
        filetype: fd.type,
      },
      onProgress: (bytesUploaded, bytesTotal) => {
        const percentage = ((bytesUploaded / bytesTotal) * 100).toFixed(2);
        setProgress({
          totalSize: progress.totalSize,
          percentage: Number(percentage),
          uploadedLengthStr: computeSize(bytesUploaded),
        });
      },
      onSuccess: () => {
        monkeyPatchReducer(
          fileUploadState.dispatch,
          fileUploadState.state,
          completeUpload(id),
          startUpload
        );
        uploadedUrlRef.current = instance.url;
      },
      onError: function (error) {
        console.log(error);
        pauseUpload(id, false)(fileUploadState.dispatch);
      },
    });
    return instance;
  };
```
