### ISSUE TITLE
Crashed to upload large files ( > 500MB): [Terminating app due to uncaught exception 'NSMallocException', reason: 'Failed to grow buffer']

### ISSUE THREAD

**Issue by nikolaytsigvintsev** [tus/tus-js-client#146]
Hi.

I'm trying to upload a large file. My application crashes after launching the upload with the error: 
- Terminating app due to uncaught exception 'NSMallocException', reason: 'Failed to grow buffer' 

On a small file size works well.

> iPad Pro
Deployment Target : 12.1
React-Native v0.58

Code:
```
      const upload = new tus.Upload({ uri: 
        `${RNFS.DocumentDirectoryPath}/images/${item.image}`}, {
        endpoint: 'http://192.168.1.5:1080/files/',
        retryDelays: [0, 1000, 3000, 5000, 10000, 15000, 20000],
        resume: true,
        metadata: {
          name: item.image,
          filetype: item.image.substring(item.image.lastIndexOf('.') + 1).toUpperCase(),
          copyright: 30
        },
        onError: (error) => {
          console.log('Error upload:', error)
        },
        onProgress: (uploadedBytes, totalBytes) => {
          console.log(`Progress: ${uploadedBytes / totalBytes}%`)
        },
        onSuccess: () => {
          console.log('Upload URL:', upload.url)
        }
      })
      upload.start()
```

**Comment by Acconut** [comment]
That's interesting, thanks for reporting. It seems to me as if tus-js-client is trying to read the entire file in memory before uploading it. This works fine if enough memory is available to cover a smaller file but obviously fails for bigger uploads.

I am not sure how to fix this inside tus-js-client out of my head now but maybe @arturi knows if React Native has a better way for streaming uploads.

@nikolaytsigvintsev: As a workaround you might want to add the `chunkSize: 100 * 1024 * 1024` option when you create the `tus.Upload` instance. This will cause the upload to be split into multiple PATCH requests where at most 100MiB are uploaded per request. Therefore, not more than 100MiB should be necessary. Of course, this is only a workaround for now and we need to find a better solution.

**Comment by nikolaytsigvintsev** [comment]
Hi.

Thanks for the answer. I tried to install chunkSize, but it did not help.
Exactly the same mistake.

  const upload = new tus.Upload({ uri: `${RNFS.DocumentDirectoryPath}/images/${item.image}`}, {
        endpoint: 'http://192.168.1.5:1080/files/',
        retryDelays: [0, 1000, 3000, 5000, 10000, 15000, 20000],
        chunkSize: 100 * 1024 * 1024,
        resume: true,
        metadata: {
          name: item.image,
          filetype: item.image.substring(item.image.lastIndexOf('.') + 1).toUpperCase(),
          copyright: 30
        },
        onError: (error) => {
          console.log('Error upload:', error)
        },
        onProgress: (uploadedBytes, totalBytes) => {
          console.log(`Progress: ${uploadedBytes / totalBytes}`)
        },
        onSuccess: () => {
          console.log('Upload URL:', upload.url)
      })
      upload.start()

**Comment by Acconut** [comment]
Oh, I forgot. tus-js-client apparently tries to load the file into memory before it slices it using the `chunkSize` option. That explains why setting this parameter does not change anything for your situation. Frankly, I am not sure how to resolve this. I am not experienced enough with React Native to know if there is a way to read a fixed amount of bytes from a file at a specific offset. Not sure if @arturi had time to look into this yet.

In the meantime you might want to look into using https://github.com/vinzscam/react-native-tus-client which is a tus-js-client-like wrapper around the native Android and iOS tus clients. I have never tried them by myself but they should be able to handle bigger files.

**Comment by nikolaytsigvintsev** [comment]
Hi.

Thank you for taking the time to respond.

The tus-js-client documentation says that you can start the upload with the Readable stream option. I think that one of the ways out of this problem is to create a readable stream and send it to the upload function. Only I cannot create a readable stream (react-native) that I can send in the Upload function.
I created a question on Stakoverflow.

Thanks for help.

**Comment by Acconut** [comment]
> The tus-js-client documentation says that you can start the upload with the Readable stream option. 

We only implemented uploading from readable stream for the browsers and Node.js, so I doubt that this would work without modifications for React Native. We are happy to extend the support for streaming uploads to React Native if you would like to give it a try.

> I created a question on Stakoverflow.

That's great, would you mind sharing a link with us?

**Comment by nikolaytsigvintsev** [comment]
Hi.

Thanks for the answer.

I do not know how I can help you. I am new to the react-native. I can try to make a function to upload file by stream, but tell me where to start.

link: https://stackoverflow.com/questions/55496609/tus-js-client-for-react-native-crashed-to-upload-large-files

**Comment by kvz** [comment]
Hi @nikolaytsigvintsev, we're working on this. We'll have a (very basic) example/version online over at the Uppy site, hopefully today.

**Comment by nikolaytsigvintsev** [comment]
Hi.

I am very glad that your work goes forward. 
I noticed that Arthur added an example response-native-expo to the Uppy site (https://github.com/transloadit/uppy/tree/master/examples/react-native-expo). I took the code from the example and compiled it for a native reaction. Tell me how the option works (fileReader: getTusFileReader). I think this is what I need.

My code snippet:

this.uppy = Uppy ({id: 'uppy', autoProceed: false, debug: true})
.use (Tus, {
resume: true
autoRetry: true
retryDelays: [0, 1000, 3000, 5000],
end point: “http://192.168.1.5:1080/files/”,
urlStorage: AsyncStorage,
fileReader: getTusFileReader,
chunkSize: 10 * 1024 * 1024, // keep the chunk size small to avoid memory shortage
meta: {
Copyright: 30
}
})

add file to uppy:
this.uppy.addFile ({
Name: node.asset.url,
type: 'image / jpeg',
data: {uri: `$ {RNFS.DocumentDirectoryPath} / images / $ {node.asset.url}`},
Source: “Local”,
isRemote: false
})

start downloading by event:
this.uppy.upload (). then ((result) => {
if (result.failed.length> 0) {
console.error ('Error:')
result.failed.forEach ((file) => {
console.error (file.error)
})
} still {
console.info ('Successful downloads:', result.successful)
}
})

All works good but the problem of large files remained. I adapted the code in getTusFileReader.js for 'react-native' , but can't understand how works 'fileReader: getTusFileReader'

getTusFileReader.js :

import RNFetchBlob from 'rn-fetch-blob'
import RNFS from 'react-native-fs'
import base64 from 'base64-js'

export default function getTusFileReader(file, chunkSize, cb) {
  RNFetchBlob.fs.stat(file.uri)
    .then((stats) => {
      console.log('Size file = ', stats.size)
      cb(null, new TusFileReader(file, stats.size))
    })
    .catch(cb)
}

class TusFileReader {
  constructor(file, size) {
    this.file = file
    this.size = size
  }

  slice(start, end, cb) {
    end = Math.min(end, this.size)
    const options = {
      length: end - start,
      postion: start
    }
    RNFS.read(this.file.uri, options.length, options.postion, 'base64').then((data) => {
      cb(null, base64.toByteArray(data))
    }).catch(cb)
  }

  close() {

  }

Thanks and good luck.

**Comment by nikolaytsigvintsev** [comment]
Hi.

I compiled and started expo example from (https://github.com/transloadit/uppy/tree/master/examples/react-native-expo ) on iPad device

The problem of large files remained.

Videoreport: https://www.dropbox.com/s/p4w17aocopg9izc/ScreenRecording_05-02-2019%2013-00-21.MP4?dl=0

thanks.

**Comment by kvz** [comment]
Hi @nikolaytsigvintsev, it seems we had a typo in there earlier :scream: sad that we're not using TypoScript (pun intended :) ) for examples yet maybe :joy_cat: @ifedapoolarewaju discovered and fixed it here: https://github.com/transloadit/uppy/commit/854654b135eece671288fadf52c08e97ff220c59

We've tested this and confirmed it works on an Android simulator.

Sorry for the long and dangerous road we're putting you on! Would you mind seeing if this fixes it for you too?

Thanks for bearing with us!

**Comment by nikolaytsigvintsev** [comment]
Hi @kvz.

Thanks for the answer.
The program works on the simulator, because there may be more memory on the simulator that real device ?
On real device iPad Pro all works good until size file < 500 - 700MB
I tried upload file 542MB result good, on upload file 2.4G result failed.

Videoreport: https://www.dropbox.com/s/1z8yy5v85mmy72m/ScreenRecording_05-08-2019%2013-31-57.MP4?dl=0
--------------------------------------------------------------------------------------------------
I'm trying to understand how the tusFileReader function works.
I inserted console.log() statements into the getTusFileReader function and into the slice() function.
The function slice() is not called.
As I understand it, the slice() function works for streaming uploading.

Thanks.

**Comment by ifedapoolarewaju** [comment]
@nikolaytsigvintsev there might be something off with your code. How are you instantiating Tus? Are you passing the `tusFileReader` into your TusOptions?

**Comment by ifedapoolarewaju** [comment]
@nikolaytsigvintsev the `slice` method exists so that we can read the file in chunks, and not the entire content. But the actual chunk reading is dependent on your implementation of the `slice` method. In the `getTusFileReader` example [here](), we are using `Expo.FileSystem` which ensures that the files are read in chunks. But from what I see in your code above, you are modifying it to use `RNFetchBlob` and `RNFS`, which I cannot guaranty that they will always read files in chunks.

So this error is due to your modification. In fact, based on the error in your logs above:
`[Error: tus: cannot fetch file.uri as Blob, make sure the uri is correct and accessible. [object Object]]`, I can guess it is triggered by this portion of your code:

```js
export default function getTusFileReader(file, chunkSize, cb) {
   RNFetchBlob.fs.stat(file.uri)
     .then((stats) => {
        console.log('Size file = ', stats.size)
        cb(null, new TusFileReader(file, stats.size))
      }).catch(cb)
}
```
This line particularly `RNFetchBlob.fs.stat(file.uri)`
so it fails right earlier on. This is why you never see the console logs in the `slice` method. Cos it never gets there.

**Comment by nikolaytsigvintsev** [comment]
Hi @ifedapoolarewaju.

Thank you for taking the time to reply.

In topic hight I wrote that **all good works if files < 500-700 MB .** 
1. I get -> .then (stats) in getTusFileReader with file size. So uri is fine, right?
2. console.log ('File size =', stats.size) shows me the file size
3. I made the slice() function be called and console.log('Start slice:', `${start}:${end}`) show me 'start' and 'end' parameters 
4. In my video report you can see that in your example at Expo also an error appears when loading large files. (the device is iPad Pro)
5. Maybe try uploading 3 GB-4 GB files to your simulator

I will continue to look for a solution to the problem for the “react-native”

Thanks.

**Comment by nikolaytsigvintsev** [comment]
Hi.

I partially solved the problem.

1. I added chunkSize, and everything began work, the file began to upload in chunks (version tus-js-client 1.8.0).
2. I made a separate thread for the upload process, where I am waiting for the upload to finish.

But all the same there is an error: Thread 47: EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit = 1400 MB, unused = 0x0)

**Comment by nikolaytsigvintsev** [comment]
Hi.

An apparent memory leak occurs with each call function cb(null, base64.toByteArray(data))
I think the problem will be in xhr.onload = function () {} ( file tus-js-client/lib.es5/upload.js ), but I could be wrong

Thanks.

**Comment by ifedapoolarewaju** [comment]
> I added chunkSize, and everything began work

@nikolaytsigvintsev ah, I didn't realize that you weren't setting `chunkSize`. Yes, the chunkSize is required for it to work.

> An apparent memory leak occurs with each call function cb(null, base64.toByteArray(data))

How can this memory leak be reproduced? Or maybe you could also share how you arrived at the theory?

**Comment by nikolaytsigvintsev** [comment]
Hi @ifedapoolarewaju

I am very glad that you took the time. 

A memory leak occurs with each fragment. When debugging, I can see that there is a leak in the CFString module. I now do not know who is to blame or tus-js-client or React-Native

Thanks .

**Comment by Acconut** [comment]
That's interesting, thanks for pointing it out, @nikolaytsigvintsev. If there is indeed a memory leak inside react-native-fs, it will be hard/impossible for tus-js-client to work around this. I am unsure if you will get a good support there as the repository has many open issues, but in all honesty, I don't know what to do about it.

**Comment by nikolaytsigvintsev** [comment]
Hello, guys!

After a long search for a solution to my problem ( answers from react-native developers were not received. https://github.com/facebook/react-native/issues/26972 ) 
I returned to trying to upload files using tus-js-client without the chunk method (without fileReader: getTusFileReader parameter). 
I was uploading many files of 40MB each.
But a memory leak and application crash were also detected. The application works while there is a memory.

1. On platform react-native:
   video report:
		https://www.dropbox.com/s/d7y596b5ba0wx9x/Screen%20Recording%202019-11-25%20at%2016.08.53.mov?dl=0
2. The expo application was installed for react-native and uploading files of 100MB each (
   https://github.com/tus/tus-js-client/tree/master/demos/reactnative) and  it was launched on iPad Pro
   video report:
- uploading and crash: https://www.dropbox.com/s/m2m4xajr7x6gh28/ScreenRecording_11-25-2019%2014-49-21.MP4?dl=0
- logs server expo:       https://www.dropbox.com/s/uuet13yfnmp386r/Screen%20Shot%202019-11-25%20at%2014.57.15.png?dl=0
- log tus server: 		   https://www.dropbox.com/s/kd93wg83fqh1w3f/Screen%20Recording%202019-11-25%20at%2012.57.30.mov?dl=0

Please tell me how can I solve this problem?

Thanks!

**Comment by Acconut** [comment]
>  I returned to trying to upload files using tus-js-client without the chunk method (without fileReader: getTusFileReader parameter).

I am wondering, why did you decide against the fileReader option? I thought that previously worked for you?

**Comment by nikolaytsigvintsev** [comment]
Hi Marius!
Thanks for the answer.

No. The uploading files doesn't work with fileReader: getTusFileReader parameter. I am reading files by means RNFS (react-native) by chunks and occur the memory leak. I have written about it on 10 May,  10 Jun,  18 Oct. I made a lot of tests and sent the description problem to the developers react-native and react-native-fs:
- https://github.com/facebook/react-native/issues/26972
- https://github.com/itinance/react-native-fs/issues/785
- https://github.com/joltup/rn-fetch-blob/issues/474

But the answer no.

I decided to turn off  fileReader: getTusFileReader parameter and try to upload small files but faced the same problem. I have thought that   I have mistakes in my code. Then I have downloaded the example your code (https://github.com/tus/tus-js-client/tree/master/demos/reactnative) but the same problem.

I showed it on video.
I'm at a loss. 
Has anyone already had such a problem?

Thanks

**Comment by Acconut** [comment]
> No. The uploading files doesn't work with fileReader: getTusFileReader parameter. 

Ok, that's unfortunate to hear. I was at the believe that this feature should solve the problem

> Has anyone already had such a problem?

No me personally. And I also don't have the time or working environment to reproduce this problem. Maybe @ifedapoolarewaju could have a look at this since he was previously involved?

**Comment by Acconut** [comment]
@nikolaytsigvintsev FYI, @mtvv also faced memory leak issues but after upgrading React Native, they were able to resolve the problem. Maybe that also helps you: https://github.com/tus/tus-js-client/issues/178#issuecomment-565450766

**Comment by jahn-brito** [comment]
Hey, any news regarding this problem?

**Comment by nikolaytsigvintsev** [comment]
> Hey, any news regarding this problem?

Hi, Jahn-Brito 

Unfortunately, we have postponed this question for now

**Comment by jahn-brito** [comment]
@nikolaytsigvintsev I managed to upload it to Vimeo with large files.
Implementation:
```js
_upload = new Upload(file, {
      uploadUrl: video.url,
      retryDelays: [0, 1000, 3000, 5000],
      chunkSize: 15 * 1024 * 1024,
      fileReader: new TusFileReader(),
      uploadSize: video.size,
      metadata: {
        filename: video.name || video.filename,
        filetype: video.mime
      },
      onError: (error) => onError(video.hashId, error),
      onProgress: (bytesAccepted, bytesTotal) => onProgress(video.hashId, bytesAccepted, bytesTotal),
      onSuccess: () => onSuccess(video.hashId)
    });

    _upload.start();
```
--------
```js
import RNFS from 'react-native-fs'
import base64 from 'base64-js'

export default class TusFileReader {
  openFile(input, chunkSize){
    return RNFS.stat(input.uri)
     .then((stats) => new FileSource(input, stats.size))
     .catch((err) => console.tron.log('erro', err))
  }
}

class FileSource {
  constructor(file, size){
    this._file = file
    this._size = size
  }

  async slice(start, end){
    end = Math.min(end, this._size)
    const length = end - start;
    const position = start;

    const data = await RNFS.read(this._file.uri, length, position, 'base64')
    const value = base64.toByteArray(data)

    return Promise.resolve({ value });
  }

  close(){}
}
```
sources: 

- [Example Uppy with React-Native](https://github.com/transloadit/uppy/blob/master/examples/react-native-expo)
- [FileReader interface in the tus-js-client documentation](https://github.com/tus/tus-js-client/blob/master/docs/api.md#filereader)

**Comment by nikolaytsigvintsev** [comment]
Hi, Jahn-Brito !

Many thanks for the help! I will definitely try and report the result.

**Comment by divyanshverma** [comment]
Hey, any news on how did this work using the File Reader ? 
I am currently stuck with as well. My setup is :
Ionic Capacitor, Angular
On android device the tus client does not do anything after the first HEAD request however when I run this in browser everthing works ok.

I am thinking it might be due to the way tus client reads the file on android device and perhaps having a Filereader will fix the issue.

Any help appreciated.

Thanks

**Comment by Acconut** [comment]
@divyanshverma This issue is about React Native. Does Ionic Capacitor use React Native under the hood? If not, please open a new issue with more details about the problems that you are seeing.

**Comment by hellochirag** [comment]
> @nikolaytsigvintsev I managed to upload it to Vimeo with large files. Implementation:
> 
> ```js
> _upload = new Upload(file, {
>       uploadUrl: video.url,
>       retryDelays: [0, 1000, 3000, 5000],
>       chunkSize: 15 * 1024 * 1024,
>       fileReader: new TusFileReader(),
>       uploadSize: video.size,
>       metadata: {
>         filename: video.name || video.filename,
>         filetype: video.mime
>       },
>       onError: (error) => onError(video.hashId, error),
>       onProgress: (bytesAccepted, bytesTotal) => onProgress(video.hashId, bytesAccepted, bytesTotal),
>       onSuccess: () => onSuccess(video.hashId)
>     });
> 
>     _upload.start();
> ```
> 
> ```js
> import RNFS from 'react-native-fs'
> import base64 from 'base64-js'
> 
> export default class TusFileReader {
>   openFile(input, chunkSize){
>     return RNFS.stat(input.uri)
>      .then((stats) => new FileSource(input, stats.size))
>      .catch((err) => console.tron.log('erro', err))
>   }
> }
> 
> class FileSource {
>   constructor(file, size){
>     this._file = file
>     this._size = size
>   }
> 
>   async slice(start, end){
>     end = Math.min(end, this._size)
>     const length = end - start;
>     const position = start;
> 
>     const data = await RNFS.read(this._file.uri, length, position, 'base64')
>     const value = base64.toByteArray(data)
> 
>     return Promise.resolve({ value });
>   }
> 
>   close(){}
> }
> ```
> 
> sources:
> 
> * [Example Uppy with React-Native](https://github.com/transloadit/uppy/blob/master/examples/react-native-expo)
> * [FileReader interface in the tus-js-client documentation](https://github.com/tus/tus-js-client/blob/master/docs/api.md#filereader)

it is not working for me i have implemented the same thing and still getting this error

*** Terminating app due to uncaught exception 'NSMallocException', reason: 'Failed to grow buffer'
*** First throw call stack

**Comment by adrienfloor** [comment]
> > @nikolaytsigvintsev I managed to upload it to Vimeo with large files. Implementation:
> > ```js
> > _upload = new Upload(file, {
> >       uploadUrl: video.url,
> >       retryDelays: [0, 1000, 3000, 5000],
> >       chunkSize: 15 * 1024 * 1024,
> >       fileReader: new TusFileReader(),
> >       uploadSize: video.size,
> >       metadata: {
> >         filename: video.name || video.filename,
> >         filetype: video.mime
> >       },
> >       onError: (error) => onError(video.hashId, error),
> >       onProgress: (bytesAccepted, bytesTotal) => onProgress(video.hashId, bytesAccepted, bytesTotal),
> >       onSuccess: () => onSuccess(video.hashId)
> >     });
> > 
> >     _upload.start();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> > import RNFS from 'react-native-fs'
> > import base64 from 'base64-js'
> > 
> > export default class TusFileReader {
> >   openFile(input, chunkSize){
> >     return RNFS.stat(input.uri)
> >      .then((stats) => new FileSource(input, stats.size))
> >      .catch((err) => console.tron.log('erro', err))
> >   }
> > }
> > 
> > class FileSource {
> >   constructor(file, size){
> >     this._file = file
> >     this._size = size
> >   }
> > 
> >   async slice(start, end){
> >     end = Math.min(end, this._size)
> >     const length = end - start;
> >     const position = start;
> > 
> >     const data = await RNFS.read(this._file.uri, length, position, 'base64')
> >     const value = base64.toByteArray(data)
> > 
> >     return Promise.resolve({ value });
> >   }
> > 
> >   close(){}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > sources:
> > 
> > * [Example Uppy with React-Native](https://github.com/transloadit/uppy/blob/master/examples/react-native-expo)
> > * [FileReader interface in the tus-js-client documentation](https://github.com/tus/tus-js-client/blob/master/docs/api.md#filereader)
> 
> it is not working for me i have implemented the same thing and still getting this error
> 
> *** Terminating app due to uncaught exception 'NSMallocException', reason: 'Failed to grow buffer' *** First throw call stack

Hey guys, same for me here !
@nikolaytsigvintsev did you manage to figure something out ?
Thanks a lot

**Comment by nikolaytsigvintsev** [comment]
> > > @nikolaytsigvintsev I managed to upload it to Vimeo with large files. Implementation:
> > > ```js
> > > _upload = new Upload(file, {
> > >       uploadUrl: video.url,
> > >       retryDelays: [0, 1000, 3000, 5000],
> > >       chunkSize: 15 * 1024 * 1024,
> > >       fileReader: new TusFileReader(),
> > >       uploadSize: video.size,
> > >       metadata: {
> > >         filename: video.name || video.filename,
> > >         filetype: video.mime
> > >       },
> > >       onError: (error) => onError(video.hashId, error),
> > >       onProgress: (bytesAccepted, bytesTotal) => onProgress(video.hashId, bytesAccepted, bytesTotal),
> > >       onSuccess: () => onSuccess(video.hashId)
> > >     });
> > > 
> > >     _upload.start();
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```js
> > > import RNFS from 'react-native-fs'
> > > import base64 from 'base64-js'
> > > 
> > > export default class TusFileReader {
> > >   openFile(input, chunkSize){
> > >     return RNFS.stat(input.uri)
> > >      .then((stats) => new FileSource(input, stats.size))
> > >      .catch((err) => console.tron.log('erro', err))
> > >   }
> > > }
> > > 
> > > class FileSource {
> > >   constructor(file, size){
> > >     this._file = file
> > >     this._size = size
> > >   }
> > > 
> > >   async slice(start, end){
> > >     end = Math.min(end, this._size)
> > >     const length = end - start;
> > >     const position = start;
> > > 
> > >     const data = await RNFS.read(this._file.uri, length, position, 'base64')
> > >     const value = base64.toByteArray(data)
> > > 
> > >     return Promise.resolve({ value });
> > >   }
> > > 
> > >   close(){}
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > sources:
> > > 
> > > * [Example Uppy with React-Native](https://github.com/transloadit/uppy/blob/master/examples/react-native-expo)
> > > * [FileReader interface in the tus-js-client documentation](https://github.com/tus/tus-js-client/blob/master/docs/api.md#filereader)
> > 
> > 
> > it is not working for me i have implemented the same thing and still getting this error
> > *** Terminating app due to uncaught exception 'NSMallocException', reason: 'Failed to grow buffer' *** First throw call stack
> 
> Hey guys, same for me here ! @nikolaytsigvintsev did you manage to figure something out ? Thanks a lot

Hi @adrienfloor

Unfortunately, we have postponed this question for now.
I am currently using the react-native-tus-client module.

But @jahn-brito said he can transfer large files?

**Comment by hellochirag** [comment]
> react-native-tus-client

@nikolaytsigvintsev  react-native-tus-client is also throwing the same error, it not allowed the 500 MB + video from devices

**Comment by nikolaytsigvintsev** [comment]
> @nikolaytsigvintsev I managed to upload it to Vimeo with large files. Implementation:
> 
> ```js
> _upload = new Upload(file, {
>       uploadUrl: video.url,
>       retryDelays: [0, 1000, 3000, 5000],
>       chunkSize: 15 * 1024 * 1024,
>       fileReader: new TusFileReader(),
>       uploadSize: video.size,
>       metadata: {
>         filename: video.name || video.filename,
>         filetype: video.mime
>       },
>       onError: (error) => onError(video.hashId, error),
>       onProgress: (bytesAccepted, bytesTotal) => onProgress(video.hashId, bytesAccepted, bytesTotal),
>       onSuccess: () => onSuccess(video.hashId)
>     });
> 
>     _upload.start();
> ```
> 
> ```js
> import RNFS from 'react-native-fs'
> import base64 from 'base64-js'
> 
> export default class TusFileReader {
>   openFile(input, chunkSize){
>     return RNFS.stat(input.uri)
>      .then((stats) => new FileSource(input, stats.size))
>      .catch((err) => console.tron.log('erro', err))
>   }
> }
> 
> class FileSource {
>   constructor(file, size){
>     this._file = file
>     this._size = size
>   }
> 
>   async slice(start, end){
>     end = Math.min(end, this._size)
>     const length = end - start;
>     const position = start;
> 
>     const data = await RNFS.read(this._file.uri, length, position, 'base64')
>     const value = base64.toByteArray(data)
> 
>     return Promise.resolve({ value });
>   }
> 
>   close(){}
> }
> ```
> 
> sources:
> 
> * [Example Uppy with React-Native](https://github.com/transloadit/uppy/blob/master/examples/react-native-expo)
> * [FileReader interface in the tus-js-client documentation](https://github.com/tus/tus-js-client/blob/master/docs/api.md#filereader)

Hi @jahn-brito!

I had to go back to using tus-js-client to upload large files. I upgraded to 2.3.0 and updated my fileReader function from your example.

Yes ! Yes ! Yes !

I certify that the upload went smoothly and without memory leaks on my Android device. 
android: 9.0
react-native: 0.64.2
tus-js-client: 2.3.0
react-native-fs: 2.16.6
file: 2.8 GB.
chunkSize: 8 * 1024 * 1024,

>  true, when the chunk is more than 10MB, the application crashes. I could not determine the reason. I put 8MB.

==============================================================
I certify that the upload went smoothly and without memory leaks on my Ipad device.
ios: 13.3
react-native: 0.64.2
tus-js-client: 2.3.0
react-native-fs: 2.16.6
file: 1.7 GB.
chunkSize: 8 * 1024 * 1024,

report:
https://www.dropbox.com/s/fhnoa2ya2cyk0vy/Screenshot%202021-11-05%20at%2012.43.50.png?dl=0

@jahn-brito Thanks! Great job!

**Comment by Acconut** [comment]
> I certify that the upload went smoothly and without memory leaks on my Android device.

Wow, that is amazing news! Congrats :tada:

**Comment by swizes** [comment]
@nikolaytsigvintsev thanks  for letting  me  know  about this issue. Did you  test if this upload  method  works while app is in background?

**Comment by nikolaytsigvintsev** [comment]
> @nikolaytsigvintsev thanks for letting me know about this issue. Did you test if this upload method works while app is in the background?

Hi @swizes !

Yes. This method works in the background for Android and works with iOS restrictions.

**Comment by ccharliemagne** [comment]
> > @nikolaytsigvintsev I managed to upload it to Vimeo with large files. Implementation:
> > ```js
> > _upload = new Upload(file, {
> >       uploadUrl: video.url,
> >       retryDelays: [0, 1000, 3000, 5000],
> >       chunkSize: 15 * 1024 * 1024,
> >       fileReader: new TusFileReader(),
> >       uploadSize: video.size,
> >       metadata: {
> >         filename: video.name || video.filename,
> >         filetype: video.mime
> >       },
> >       onError: (error) => onError(video.hashId, error),
> >       onProgress: (bytesAccepted, bytesTotal) => onProgress(video.hashId, bytesAccepted, bytesTotal),
> >       onSuccess: () => onSuccess(video.hashId)
> >     });
> > 
> >     _upload.start();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> > import RNFS from 'react-native-fs'
> > import base64 from 'base64-js'
> > 
> > export default class TusFileReader {
> >   openFile(input, chunkSize){
> >     return RNFS.stat(input.uri)
> >      .then((stats) => new FileSource(input, stats.size))
> >      .catch((err) => console.tron.log('erro', err))
> >   }
> > }
> > 
> > class FileSource {
> >   constructor(file, size){
> >     this._file = file
> >     this._size = size
> >   }
> > 
> >   async slice(start, end){
> >     end = Math.min(end, this._size)
> >     const length = end - start;
> >     const position = start;
> > 
> >     const data = await RNFS.read(this._file.uri, length, position, 'base64')
> >     const value = base64.toByteArray(data)
> > 
> >     return Promise.resolve({ value });
> >   }
> > 
> >   close(){}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > sources:
> > 
> > * [Example Uppy with React-Native](https://github.com/transloadit/uppy/blob/master/examples/react-native-expo)
> > * [FileReader interface in the tus-js-client documentation](https://github.com/tus/tus-js-client/blob/master/docs/api.md#filereader)
> 
> Hi @jahn-brito!
> 
> I had to go back to using tus-js-client to upload large files. I upgraded to 2.3.0 and updated my fileReader function from your example.
> 
> Yes ! Yes ! Yes !
> 
> I certify that the upload went smoothly and without memory leaks on my Android device. android: 9.0 react-native: 0.64.2 tus-js-client: 2.3.0 react-native-fs: 2.16.6 file: 2.8 GB. chunkSize: 8 * 1024 * 1024,
> 
> > true, when the chunk is more than 10MB, the application crashes. I could not determine the reason. I put 8MB.
> 
> ============================================================== I certify that the upload went smoothly and without memory leaks on my Ipad device. ios: 13.3 react-native: 0.64.2 tus-js-client: 2.3.0 react-native-fs: 2.16.6 file: 1.7 GB. chunkSize: 8 * 1024 * 1024,
> 
> report: https://www.dropbox.com/s/fhnoa2ya2cyk0vy/Screenshot%202021-11-05%20at%2012.43.50.png?dl=0
> 
> @jahn-brito Thanks! Great job! @kvz,@ifedapoolarewaju Thanks!
> 
> Thanks to everyone who participated in the development of this library!

Its working but I'm experiencing FPS drops on JS thread up to -2fps.

**Comment by nikolaytsigvintsev** [comment]
> FPS drops on JS thread

Hi @ccharliemagne!

Yes. I see it too. Apparently, when a packet is formed for transmission, then all the processing power is used. I am struggling with this by reducing the block size to 1MB. 1 * 1024 * 1024.

**Comment by samal-rasmussen** [comment]
What I've seen is that it's the `base64.toByteArray(data)` that takes a long time to process per chunk/slice. `RNFS.read` and the rest of the slice function implementation is quick.

**Comment by Acconut** [comment]
> What I've seen is that it's the `base64.toByteArray(data)` that takes a long time to process per chunk/slice.

Do you know if there is an replacement for the toByteArray function to speed this up?

**Comment by samal-rasmussen** [comment]
I tried a couple of alternatives, but they were all slow. In the end we just figured out that we could do without the custom FileReader, so I didn't get so far as to profile the running code and see precisely what was slow. But an educated guess would be that it is because converting a base64 encoded string to a byte array in an inherently computationally intensive operation and the js runtime in React Native does not have a jit compiler[0] and only an interpreter. An interpreter will run code muuuuch slower than jit compiled code, and computationally intensive code like this will be hit especially hard by this slowdown.

[0] https://reactnative.dev/docs/javascript-environment

**Comment by Acconut** [comment]
@samal-rasmussen Ah, thank you for the insights. So if I understand correctly, you are just using the FileReader that is built into tus-js-client? I.e. this one: https://github.com/tus/tus-js-client/blob/c0b5a7dec0f084db8e6c2e75eae25a19a2e364d3/lib/browser/fileReader.js#L9-L19

**Comment by malnajdi** [comment]
Hey guys, i am trying to upload large file and faced the same issue with the ios and android memory fills up and crash the app. Using React native as well. i switched from axios to your client and i tried to implement the above solution without luck. 

I am using Expo Picker -> will yield a uri for me and pass it to new tus.Upload(fileUrl, {}) with options as stated above but i always get `undefined is not an object`

**Comment by mifi** [comment]
Could you post some more info about the error? Any stack or line which it crashes on?

**Comment by malnajdi** [comment]
[Wed Feb 15 2023 02:21:43.400]  LOG      [TypeError: undefined is not an object (evaluating 'path.startsWith')]

this is the error i get. I am not sure thought if i need to change my backend to be tus compatible or i can just use it with normal multipart/formdata

**Comment by mifi** [comment]
if you want to use tus-js-client you need to have a tus compatible backend. the official recommended one is https://github.com/tus/tusd

did you try this code? https://github.com/tus/tus-js-client/issues/146#issuecomment-671967166

**Comment by malnajdi** [comment]
> if you want to use tus-js-client you need to have a tus compatible backend. the official recommended one is https://github.com/tus/tusd
> 
> did you try this code? [#146 (comment)](https://github.com/tus/tus-js-client/issues/146#issuecomment-671967166)

i will try it with a compatible backend

**Comment by malnajdi** [comment]
getting this error.
tusd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by tusd)

**Comment by malnajdi** [comment]
i tested the above code with tus server and tus-js-client latest versions i got this error with large files, small files works fine:

```tus: cannot automatically derive upload's size from input. Specify it manually using the `uploadSize` option or use the `uploadLengthDeferred```

**Comment by Acconut** [comment]
> tusd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by tusd)

See https://github.com/tus/tusd/issues/909
