### ISSUE TITLE
Uncaught TypeError: Storage.removeItem is not a function

### ISSUE THREAD

**Issue by aubrey-cpt** [tus/tus-js-client#149]
**Describe the bug**
The error is displayed after a successful upload using Chrome browser.

**To Reproduce**
1. Select the file, using file html element in the form.
2. Start upload, on successful upload the following error is displayed.
3. Uncaught TypeError: Storage.removeItem is not a function at XMLHttpRequest.xhr.onload (tus.js)

** Error source **
      if (offset == this._size) {
        if (this.options.removeFingerprintOnSuccess && this.options.resume) {
          // Remove stored fingerprint and corresponding endpoint. This causes
          // new upload of the same file must be treated as a different file.
          **Storage**.removeItem(this._fingerprint);
        }

** Fix **
      if (offset == this._size) {
        if (this.options.removeFingerprintOnSuccess && this.options.resume) {
          // Remove stored fingerprint and corresponding endpoint. This causes
          // new upload of the same file must be treated as a different file.
          **this._storage**.removeItem(this._fingerprint);
        }

**Comment by Acconut** [comment]
Moved to https://github.com/tus/tus-js-client/issues/151.
