### ISSUE TITLE
Uncaught TypeError: cb is not a function

### ISSUE THREAD

**Issue by aubrey-cpt** [tus/tus-js-client#150]
**Describe the bug**
The error is displayed after a successful upload using Chrome browser. 

Two issues are raised:
- There is a missing callback check to ensure cb is a function, which generates this error
- The intended call e.g. localStorage.removeItem is not executed because of the error

**To Reproduce**
- Select the file, using file html element in the form.
- Start upload, on successful upload the following error is displayed.
- Uncaught TypeError: cb is not a function at LocalStorage.removeItem (tus.js) at XMLHttpRequest.xhr.onload (tus.js)

**Error source**
File: /lib/browser/storage.js

class LocalStorage {
  setItem(key, value, cb) {
    if (!hasStorage) return cb();
    cb(null, localStorage.setItem(key, value));
  }

  getItem(key, cb) {
    if (!hasStorage) return cb();
    cb(null, localStorage.getItem(key));
  }

  removeItem(key, cb) {
    if (!hasStorage) return cb();
    cb(null, localStorage.removeItem(key));
  }
}

**Fix**
class LocalStorage {
  setItem(key, value, cb) {
    if(typeof cb === 'function'){
      if (!hasStorage) return cb();
      cb(null, localStorage.setItem(key, value));
    } else {
      localStorage.setItem(key, value);
    }
  }

  getItem(key, cb) {
    if(typeof cb === 'function') {
      if (!hasStorage) return cb();
      cb(null, localStorage.getItem(key));
    } else {
      localStorage.getItem(key);
    }
  }

  removeItem(key, cb) {
    if(typeof cb === 'function') {
      if (!hasStorage) return cb();
      cb(null, localStorage.removeItem(key));
    } else {
      localStorage.removeItem(key);
    }
  }
}

**Comment by Acconut** [comment]
I believe this is the same underlying problem as https://github.com/tus/tus-js-client/issues/151. Could you please try out its solution and report back if it doesn't work?
