### ISSUE TITLE
Implement Cancel/Terminate upload

### ISSUE THREAD

**Issue by ifedapoolarewaju** [tus/tus-js-client#157]
Creating this issue to serve as a discussion on how to implement the `Terminate` extension for uploads. See [here](https://github.com/tus/tus-js-client/issues/135#issuecomment-498301121)

**Comment by ifedapoolarewaju** [comment]
@Acconut please let me know what are your thoughts on this. My first thought is that it makes sense to add `terminate` as a static method to `tus.Upload`, so that we can easily cancel an old upload without instantiation, or without the need to add a file.

**Comment by Acconut** [comment]
> so that we can easily cancel an old upload without instantiation, or without the need to add a file.

Yes, I agree here. That makes sense.

The question is: Do we also want to integrate this into tus.Upload#abort, for example by having a boolean argument saying whether the upload should be terminated? This would make it easier for the user in some cases but I am not sure if that's a good enough argument for having two different ways of terminating an upload. Do you as an Uppy-developer have any thoughts on this?

**Comment by ifedapoolarewaju** [comment]
yeah, I think since the `Upload` instance cannot access the static method, then it probably makes sense to have the feature also present in the `Upload#abort` instance method. As a user of tus-js-client, this is a convenience I would appreciate. But in general, I don't see any other value in it rather than convenience and the fact that there's nothing to lose if we add it.

**Comment by Acconut** [comment]
>  I think since the Upload instance cannot access the static method

Not sure I can follow this thought. Why would an instance method not be able to access a static method? Maybe I misunderstood your sentence. Could you explain?

> then it probably makes sense to have the feature also present in the Upload#abort instance method.

Ok, sounds good. Can you give the implementation a try?

**Comment by ifedapoolarewaju** [comment]
> Not sure I can follow this thought. Why would an instance method not be able to access a static method? Maybe I misunderstood your sentence. Could you explain?

I think that's the way classes behave in JS https://stackoverflow.com/a/43614217/4088675 . Static methods only exist on the class and not on the instance.

**Comment by Acconut** [comment]
> Static methods only exist on the class and not on the instance.

Yes, that's correct but instance methods can still access static methods. However, I feel we both are saying different things but mean the same. So let's just wait for your implementation and then we can discuss it if needed.

**Comment by Acconut** [comment]
Implemented in #159
