### ISSUE TITLE
Upload directly from FileReader

### ISSUE THREAD

**Issue by gencer** [tus/tus-js-client#162]
**Is your feature request related to a problem? Please describe.**
Currently we only upload from `File` item via browsers. I would like to be able to upload from memory/data.

For example, when user copy an image to clipboard from a photo editor or screenshot and paste to browser, we can get the data using `document.onpaste`. This gave us `FileReader` object. We can convert this to base64 or directly as binary. So I would like to pass this binary reader object from memory to tus instead of `File`.

Example:

```typescript
   const items: any[] = event.clipboardData.items
   if (items[0].type.indexOf("image") !== 0) return;
   const reader = new FileReader()
   const data: string = reader.readAsDataURL(blob) // as data,image base64
   const content = reader.readAsBinaryString(blob) // as binary
```

**Describe the solution you'd like**
Ability to pass content instead of `File` item.

**Describe alternatives you've considered**
Currently, no alternatives however, I upload to server first, save it to disk then upload to tus backed server again. This is frustrating.

**Can you provide help with implementing this feature?**
I will look what i can do on this.

**Comment by gencer** [comment]
I see https://github.com/tus/tus-js-client/pull/126. I will try that and report here. Sorry, I didn't noticed this being merged before.

**Comment by gencer** [comment]
Yup. Solved.

**Comment by Acconut** [comment]
Glad to read that you found a solution on your own :+1:
