### ISSUE TITLE
Javascript error 'tus is not defined' and missing file

### ISSUE THREAD

**Issue by super23n** [tus/tus-js-client#163]
**Describe the bug**
I am getting a Javascript error when going to the demos/browser/index.html
The error is: 'ReferenceError: tus is not defined'
And the directory and file 'dist/tus.js' is not present in the downloaded package (tus-js-client-master.zip).

**To Reproduce**
Download tus-js-client-master.zip, and search for 'dist/tus.js'. It's not there.

**Expected behavior**
'dist/tus.js' should be there and the 'tus' object must not be undefined during run time.

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: Firefox 67
- Used tus-js-client version: the latest (1.7.1 I think)
- Used tus server software: just the client

**Comment by gencer** [comment]
You're downloading `master` branch which is **only contains source code**. You need to build `dist/tus.js` yourself or use `npm` for that.

To build `dist/tus.js` follow this instructions:

```
# Install dependencies
npm install

# Build dist/tus.js a single time
npm run build

# Build all dist files (including minification)
npm run dist

# Watch source and rebuild
npm run watch
```

**Comment by super23n** [comment]
Ok thanks, I wanted to install NPM at first but thought that that file was missing.
