### ISSUE TITLE
How to get the last patch request in onSuccess

### ISSUE THREAD

**Issue by alireza1272** [tus/tus-js-client#166]
**Question**
First of all thank u to provide tus-js-client
I'm using tus-js-client in angular, and I uploaded videos through this package. But when It successfully ends I need to access to the **Last Patch** request. I need to access it's response headers because the X-download-Url of uploaded video located there.
I found nothing that give me the chance to access Last Patch which status is 204. 
I would be very glad, if anyone can help me.
Thanks.

**Setup details**
- Runtime environment: [Browser, Node.js, Angular]
- Used tus-js-client version: [`npm`]

**Comment by Acconut** [comment]
Thank you for the kind words. Unfortunately, there is no feature to access the HTTP requests and responses directly. A person in another repo asked for this as well: https://github.com/transloadit/uppy/issues/1713#issuecomment-520577059 So we are considering it for the future but don't have the resources right now to work on this. As a workaround you might want to add an endpoint to your API to retrieve the download URL for a specific upload.

**Comment by Acconut** [comment]
The v2 release will feature an `onAfterResponse` callback for these jobs. More details at https://github.com/tus/tus-js-client/issues/167.
