### ISSUE TITLE
Problem uploading to Vimeo. Upload-offset is always 0.

### ISSUE THREAD

**Issue by gdarko** [tus/tus-js-client#170]
**Question**
Hello,
I am trying to create a html page for vimeo uploads but no success. I am using this tus client and creating the video first with separate request, then initiating upload to the response.upload.upload_link url with vimeo.

I get HTTP error and the upload-offset is always 0 in the head requests

This is what i get:
1.) [http://prntscr.com/p85abi](http://prntscr.com/p85abi)
2.) [http://prntscr.com/p85b31](http://prntscr.com/p85b31)

The code:

```js
/**
 * Handle upload
 * @param file {File}
 * @param uploadUrl
 * @param successCallback
 */
function uploadToVimeo(file, uploadUrl, successCallback) {
    if (!file) {
        return;
    }
    var chunkSize = 5000000; // 5 MB
    var options = {
        endpoint: uploadUrl,
        uploadUrl: uploadUrl,
        chunkSize: chunkSize,
        retryDelays: [0, 1000, 3000, 5000],
        metadata: {
            filename: file.name,
            filetype: file.type
        },
        headers: {
            'Content-Type': 'application/offset+octet-stream',
            'Accept': getAccept(),
        },
        onError: function (error) {
            console.log('Error');
            console.log(error);
        },
        onProgress: function (bytesUploaded, bytesTotal) {
            var percentage = (bytesUploaded / bytesTotal * 100).toFixed(2);
            console.log(bytesUploaded, bytesTotal, percentage + "%");
        },
        onSuccess: function (resp) {
            //console.log('Response');
            //console.log(resp);
            if (successCallback) {
                successCallback(resp);
            }
        }
    };
    upload = new tus.Upload(file, options);
    upload.start();
}
```

What could be causing this?

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: [e.g. Browser, Node.js, React Native]
Browser
- Used tus-js-client version: [can be obtained by running `npm ls`]
1.8.0-2

**Comment by Acconut** [comment]
Frankly, I don't have an idea what could be the problem here. What does the network tab say about the failed HTTP request? Are there more details about the HTTP/2 protocol error?

Also, did you try to contact Vimeo support yet? It looks more like a problem on their side rather than tus-js-client.

**Comment by gdarko** [comment]
Yes it doesn't seem to be related to tus-js-client.

Here is [screenshot ](http://prntscr.com/p85t8o)of failed PATCH request.

**Comment by Acconut** [comment]
Ok, so I would suggest you talk to Vimeo's engineers. I can't help you with their services.

**Comment by gdarko** [comment]
I found the problem, it was because of the

```
'Content-Type': 'application/offset+octet-stream',
```
header i had set, after i removed it works fine.

**Comment by Acconut** [comment]
Interesting, great to hear you found the problem!
