### ISSUE TITLE
Error 412 while trying upload data to vimeo with tus approarch!

### ISSUE THREAD

**Issue by hunglas** [tus/tus-js-client#181]
**Question**
Vimeo API has 3 steps for uploading a resumable approach and I use NodeJS to step 1 (Create a video via API with Tus approach https://developer.vimeo.com/api/upload/videos#resumable-approach-step-1)
I successfully got returns data from Vimeo with upload_link look like:
https://files.tus.vimeo.com/files/vimeo-prod-src-tus-asia/........................
But when I use tus-js-client to do the patch method for step 2 https://developer.vimeo.com/api/upload/videos#resumable-approach-step-2
Either use endpoint, uploadurl with the link above I always get error 412:
Failed because: Error: tus: unexpected response while creating upload, originated from request (response code: 412, response text: unsupported version

![image](https://user-images.githubusercontent.com/50732066/74676927-bf7b9a80-51e9-11ea-98a5-50ab3f22c5b7.png)

Can I use upload_link from vimeo return data for endpoint or uploadurl in tus js client for uploading video? Does this error come from Vimeo? Can somebody help? Thanks

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: HTML
- Used tus-js-client version: Latest version download from https://github.com/tus/tus-js-client
- Used tus server software: https://files.tus.vimeo.com

**Comment by jamesmoss** [comment]
Hi @hunglas, we recently ran into the same problem. This isn't really explained clearly in the Vimep docs but if you don't pass `uploadUrl` into `tus.Upload` then the library will try to run step 1 for you (which in your case you've already done). 

If you change your call to the following you should be good:

```
const upload = new tus.Upload(file, {
  uploadUrl: url,
  endpoint: url,
  retryDelays: [0, 3000, 5000, 10000, 20000],
  metadata: {
    filename: file.name,
    filetype: file.type,
  },
  onError(error) {
    console.log(`Failed because: ${error}`);
  },
  onProgress(bytesUploaded, bytesTotal) {
    const percentage = ((bytesUploaded / bytesTotal) * 100).toFixed(2);
    console.log(bytesUploaded, bytesTotal, `${percentage}%`);
  },
  onSuccess() {
    console.log('Download %s from %s', upload.file.name, upload.url);
  },
});
```

**Comment by hunglas** [comment]
Hi @jamesmoss ,
Thanks for your answer! I am luckily when I try your code without the headers as the way Vimeo require in their document:
![image](https://user-images.githubusercontent.com/50732066/74835939-f4563180-5350-11ea-9166-7ccb7a9088c4.png)

Because when I added the headers, the error always happen!
![image](https://user-images.githubusercontent.com/50732066/74835895-e3a5bb80-5350-11ea-8222-631e8fa0525d.png)

So removed header and everything will be good!

Thank you again!
