### ISSUE TITLE
Is https supported?

### ISSUE THREAD

**Issue by martijnhiemstra** [tus/tus-js-client#186]
I am wandering will https ever be supported by tus-js-client? I am asking because I have a Angular 8 project that contains tus file upload. Locally it works perfectly however in production where https is only possible it doesn't work. In the network tab of web developer I can see the first post being sent and that one works. It also returns the Location data in the response. After that it's one error after the other. Even though I have 50kb chunkSize it only uploads 1 kb each time and eventually the request errors out. The internet speed is really good so that's not the issue. I am getting the idea that https isn't supported properly.

**Comment by Acconut** [comment]
Yes, of course, HTTPS is fully supported. This sounds like a problem in your setup. What errors are you getting? Also, please provide all the details we asked you in the issue template: https://github.com/tus/tus-js-client/blob/master/.github/ISSUE_TEMPLATE/question.md

**Comment by martijnhiemstra** [comment]
Runtime environment: Angular 8 using tus client version 1.8 browsing using Chrome
Used tus-js-client version: 1.8.0
Used tus server software: Spring boot backend which has this implemented: (https://github.com/thomasooo/spring-boot-tus/)

What I also have noticed is that locally each chunk is sent according to the chunk size and I get see alot of patch requests. However in production there is only 4 calls done. It's almost as if in production the entire file is sent or Chrome doesn't register each request as it does locally.

**Comment by Acconut** [comment]
Hm, that's weird. What behavior do you see if you upload to https://master.tus.io/files/? Is chunk size respected there or not?

Also, can you share your code responsible for handling the tus upload?

**Comment by martijnhiemstra** [comment]
Yes, that endpoint also has the same behaviour. My tus client code is:

```
const file = this.fileSelect.nativeElement.files[0];
    const upload = new tus.Upload(file, {
      endpoint: 'https://master.tus.io/files/', 
      retryDelays: [0, 5000],
      chunkSize: '2000',
      metadata: {
        filename: file.name,
        filetype: file.type,
        subjectId: this.subject.id
      },
      onError: async (error) => {
        this.alertService.error(error);
      },
      onChunkComplete: (chunkSize, bytesAccepted, bytesTotal) => {
        this.uploadProgress = Math.floor(bytesAccepted / bytesTotal * 100);
      },
      onSuccess: async () => {
        this.uploadProgress = 100;

        const createdMsg = this.translateService.instant('subject.resource.created', { 'resource': file.name });
        this.alertService.success(createdMsg, true);

        this.router.navigateByUrl('/secure/subject/' + this.subject.id + '/resources');
      }
    });

    upload.start();
```

**Comment by martijnhiemstra** [comment]
In the onChunkComplete part I have added a console.log where I log the chunksize. It says this:

```
onChunkComplete: chunkSize = 2000 - bytesAccepted = 2000
onChunkComplete: chunkSize = 20000000 - bytesAccepted = 20002000
```

So the first patch is working because the chinksize is 2000. I think I see the problem. The second chunksize is 2000 + 2000. I am guessing that  there is error in your software where the chunksize is being added up and a new chunksize is created. Instead the chunksize staying 2000 the chunksize is added to the previous chunksize and it is seen as a string

**Comment by Acconut** [comment]
I haven't had a deep dive, but why is chunkSize a string?
>       chunkSize: '2000',

It should be a number. Could that be the problem?

**Comment by martijnhiemstra** [comment]
Yes, that's it. Excellent eye. Thanks for the support. I hope this thread will help somebody else someday.

**Comment by ijunaid8989** [comment]
I have this settings
```      return new Promise((resolve) => {
        this.file = document.querySelector("#file-upload").files[0]
        console.log(this.file, process.env.TUS_URL)
        var upload = new tus.Upload(this.file, {
          endpoint: `${process.env.TUS_URL}`,
          resume: true,
          chunkSize: Infinity,
          retryDelays: [0, 1000, 3000, 5000],
          metadata: {
            filename: this.file.name,
            filetype: this.file.type,
          },
          uploadSize: this.file.size,
          onProgress: (bytesUploaded, bytesTotal) => {
            var percentage = ((bytesUploaded / bytesTotal) * 100).toFixed(2)
            console.log(bytesUploaded, bytesTotal, percentage + "%")
            this.fileCount = percentage
            this.currentStatus = STATUS_SAVING
          },
          onSuccess: () => {
            console.log("Download %s from %s", upload.file.name, upload.url)
            this.file_url = upload.url
            this.title = upload.file.name.split(".")[0]
            this.file_extension = upload.file.name.split(".")[1]
            this.currentStatus = STATUS_SUCCESS
            this.createArchive()
          },
          onError: (error) => {
            console.log("Failed because: " + error)
            this.currentStatus = STATUS_FAILED
          },
        })
        upload.start()
        resolve()
      })
```
but neither HTTP nor HTTPs is working.
this is what I got

![image](https://user-images.githubusercontent.com/13561999/93392514-5ac11500-f88a-11ea-826a-2d87d8185339.png)

**Comment by Acconut** [comment]
It looks like your endpoint (`process.env.TUS_URL`) uses the http:// protocol. But since your page is loaded over HTTPS, the tus endpoint must also be accessed over HTTPS. So you must use https://staging.evercam.io/files as the tus endpoint.

**Comment by ijunaid8989** [comment]
now both are HTTPs

![image](https://user-images.githubusercontent.com/13561999/93437401-5ece5080-f8e5-11ea-92ad-85bb822f77bb.png)

and it also came into progress part

```
        console.log(this.file, process.env.TUS_URL)
        var upload = new tus.Upload(this.file, {
          endpoint: `${process.env.TUS_URL}`,
          storeFingerprintForResuming: true,
          chunkSize: Infinity,
          retryDelays: [0, 1000, 3000, 5000],
          metadata: {
            filename: this.file.name,
            filetype: this.file.type,
          },
          uploadSize: this.file.size,
          onProgress: (bytesUploaded, bytesTotal) => {
            var percentage = ((bytesUploaded / bytesTotal) * 100).toFixed(2)
            console.log(bytesUploaded, bytesTotal, percentage + "%")
            this.fileCount = percentage
            this.currentStatus = STATUS_SAVING
          },
```
but then just failed

**Comment by Acconut** [comment]
Make sure your tusd server is properly set up to work with any proxy you have in between: https://github.com/tus/tusd/blob/master/docs/faq.md#can-i-run-tusd-behind-a-reverse-proxy

**Comment by ijunaid8989** [comment]
Actually the `process.env.TUS_URL` is HTTPS, and it starts as HTTPS but after starting? it shift https to https for staging...io, can you tell what could be the reason of this URL change?

**Comment by ijunaid8989** [comment]
Sure, but do you see any issue, why it could be moved to HTTP after starting upload? and its working fine for 2 other tus clients we are using.

**Comment by Acconut** [comment]
> Sure, but do you see any issue, why it could be moved to HTTP after starting upload?

Yes, in almost all cases where this happens, tusd is not properly configured to work with the proxy. Please follow the instructions in the link I posted.

**Comment by ijunaid8989** [comment]
I had to add this to my meta details of

```
      {
        "http-equiv": "Content-Security-Policy",
        content: "upgrade-insecure-requests",
      },
```
I was using it in nuxt so in nuxt.config.js I added this

```
  head: {
    titleTemplate: "%s",
    title: "Evercam Admin",
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      {
        "http-equiv": "Content-Security-Policy",
        content: "upgrade-insecure-requests",
      },
      {
        hid: "description",
        name: "description",
        content: process.env.npm_package_description || "",
      },
    ],
    link: [{ rel: "icon", type: "image/x-icon", href: "/favicon.png" }],
  },
```
and now its working fine.

**Comment by jdaly13** [comment]
> I had to add this to my meta details of
> 
> ```
>       {
>         "http-equiv": "Content-Security-Policy",
>         content: "upgrade-insecure-requests",
>       },
> ```
> 
> I was using it in nuxt so in nuxt.config.js I added this
> 
> ```
>   head: {
>     titleTemplate: "%s",
>     title: "Evercam Admin",
>     meta: [
>       { charset: "utf-8" },
>       { name: "viewport", content: "width=device-width, initial-scale=1" },
>       {
>         "http-equiv": "Content-Security-Policy",
>         content: "upgrade-insecure-requests",
>       },
>       {
>         hid: "description",
>         name: "description",
>         content: process.env.npm_package_description || "",
>       },
>     ],
>     link: [{ rel: "icon", type: "image/x-icon", href: "/favicon.png" }],
>   },
> ```
> 
> and now its working fine.

This was very helpful - thank you I ended doing something similar in my remix js application which utilizes node/express
```
if (process.env.NODE_ENV === "production") {
  app.use((req, res, next) => {
    res.setHeader("Content-Security-Policy", "upgrade-insecure-requests");
    next();
  });
}
```

**Comment by GauravMethwani** [comment]
Hi everyone,
I wanted to share my solution for enabling HTTPS support in the tus server. My approach involved two main changes:
1. Backend Configuration
I set respectForwardedHeaders: true in the tus server configuration. This ensures that the server respects forwarded headers like x-forwarded-proto.

```
const tusServer = new Server({
  path: '/api/v1/files',
  datastore: new CustomDatastore(),
  respectForwardedHeaders: true
});
```

2. Client Request Headers 
On the client side, I'm using tus-js-client to handle file uploads. I've added the header x-forwarded-proto (e.g., windows.protocol) to correctly indicate the original protocol.

```
import tus from 'tus-js-client';

// Suppose 'videoFile' is the File object you want to upload
const upload = new tus.Upload(videoFile, {
  endpoint: 'https://yourdomain.com/api/v1/files',
  retryDelays: [0, 1000, 3000, 5000],
  headers: {
    'x-forwarded-proto': 'windows.protocol',
  },
  metadata: {
    filename: videoFile.name,
    filetype: videoFile.type,
  },
  onError: function(error) {
    console.error("Upload failed:", error);
  },
  onProgress: function(bytesUploaded, bytesTotal) {
    const percentage = ((bytesUploaded / bytesTotal) * 100).toFixed(2);
    console.log(`${bytesUploaded} of ${bytesTotal} bytes uploaded (${percentage}%)`);
  },
  onSuccess: function() {
    console.log("Upload completed successfully!");
  }
});

// Start the upload process
upload.start();

```
I hope this helps! Please let me know if you have any questions or need further clarification.

**Comment by Acconut** [comment]
@GauravMethwani Thank you for sharing this, but the X-Forwarded-Proto header should be set by the TLS terminating proxy and not the client sending the requests. When a proxy terminates HTTPS to HTTP, the header indicates the backend servers that the original request was made using HTTPS.
