### ISSUE TITLE
onChunkComplete still triggered long after onSuccess event

### ISSUE THREAD

**Issue by djsg** [tus/tus-js-client#187]
I have observed sth rather strange, at least to me.

In my test case, tus client is embedded in a web page, which I copied from the demo page with a little modification: i added onChunkComplete event.
What I found even long (> 10 minutes) after file upload finishes, onChunkComplete still got triggered. 
Is there any good explanation for this?

**Comment by djsg** [comment]
What is the exact difference between onProgress and onChunkComplete?
According to readme: onProgress is a function that will be called each time progress information is available. The arguments will be bytesSent and bytesTotal.
It looks like onProgress is called when one piece of ChunkSize data is successfully sent out. It does not mean it has been received by the server, does it?
If it is the case, onChunkComplete is more appropriate to monitor progress, isn't it? Yet the demo page uses onProgress instead of onChunkComplete. Can anyone help to clarify? Many thanks.

**Comment by Acconut** [comment]
> What I found even long (> 10 minutes) after file upload finishes, onChunkComplete still got triggered. Is there any good explanation for this?

No, I have never heard of this before. Please share all the details as requested in the issue template.

> What is the exact difference between onProgress and onChunkComplete?

Did you read the section "Difference between onProgress and onChunkComplete" in the README: https://github.com/tus/tus-js-client#difference-between-onprogress-and-onchunkcomplete? That might answer your question already.

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)
