### ISSUE TITLE
Different behaviour of fingerprint function upgrading from v1.7.1 to v1.8.0

### ISSUE THREAD

**Issue by vindemasi** [tus/tus-js-client#188]
**Describe the bug**
I used to manage start and stop of uploading files dinamically, after upgrading to version 1.8.0 calling start on an Upload instance seems to do nothing. I'm not sure if it's a bug or I've misanderstood the API.

**To Reproduce**
1. my Upload configurations looks like:
 ```
private $uploadOptions = {
        endpoint: uploadServiceEndpoint,
        retryDelays: [0, 1000, 2000, 3000, 5000, 9000],
        removeFingerprintOnSuccess: true,
        chunkSize: uploadChunkSize,
        resume: true,
    };
    
    addFile(file: File, info: ContainerInfo, remoteFile: RemoteUploadFile) {
        const tusFile = new Upload(file, Object.assign({}, this.$uploadOptions, {
            metadata: remoteFile.metadata,
            fingerprint: () => remoteFile.uuid,
            onProgress: this.onUploadProgress.bind(this, remoteFile.uuid),
            onChunkComplete: this.onUploadChunkComplete.bind(this, remoteFile.uuid),
            onSuccess: this.onUploadSuccess.bind(this, remoteFile.uuid),
            onError: this.onUploadError.bind(this, remoteFile.uuid),
        }));
        tusFile.start();
    }
```
2. Start 'tusFile.start()'
3. The upload do not starts.
4. If I remove fingerprint function from the setting options then the upload starts.

**Expected behavior**
The upload should starts also using a custom fingerprint function.

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: Browser
- Used tus-js-client version:1.8.0
- Used tus server software: tusd

**Comment by Acconut** [comment]
Yes, you are right. We accidentally introduced a regression by making the fingerprint function asynchronous, so it now takes a callback. You can see the usage at https://github.com/tus/tus-js-client/blob/master/lib/upload.js#L230

Apologies for the inconvenience. If you add the callback, it should work again.

**Comment by vindemasi** [comment]
@Acconut tnx a lot for your hint,
just tried it and it works!

**Comment by Acconut** [comment]
You're welcome!
