### ISSUE TITLE
https requests downgraded to http => Chrome mixed-content error

### ISSUE THREAD

**Issue by c990802** [tus/tus-js-client#189]
In 1.8.0, when passing a `https:` url to `endpoint`, it is being downgraded to `http:`. This is causing uploads to be blocked when serving a page from an `https` domain.

1. Run tus-js-client in a `https` page with version 1.6.1. Endpoint url is not downgraded:
 
![Screen Shot 2020-04-09 at 16 50 16](https://user-images.githubusercontent.com/6229037/78908909-116ecd00-7a83-11ea-8ec7-4e9f812e83b2.png)

2. Upgrade package to 1.8.0
3. Same upload fails. The request is being blocked by Chrome.
![Screen Shot 2020-04-09 at 16 52 01](https://user-images.githubusercontent.com/6229037/78908960-1fbce900-7a83-11ea-836f-d94b7dee1c3d.png)

Not sure if this is a bug or a feature. If I am missing out something, please let me know :)

**Comment by JessePerry** [comment]
What was your solution to this issue?
