### ISSUE TITLE
Prebuilt script missing

### ISSUE THREAD

**Issue by TacoV** [tus/tus-js-client#195]
The installation documentation refers to a prebuilt script.
https://github.com/tus/tus-js-client/blob/master/docs/installation.md#embed-using-a-script-tag
However, this file is not available within this project (anymore?).

Since the dist folder is in .gitignore, should one generate this locally? Or should it exist and did it get lost along the way?

**Comment by Acconut** [comment]
The dist folder is not checked out into the Git repository, so you cannot find it on GitHub. So, either you build the library on your own as outlined in https://github.com/tus/tus-js-client/blob/master/docs/contributing.md. Alternatively, the script is also available on NPM, so you can get it at https://cdn.jsdelivr.net/npm/tus-js-client@2.1.1/dist/tus.min.js.
