### ISSUE TITLE
Should not retry on 409 or 423 status

### ISSUE THREAD

**Issue by PVince81** [tus/tus-js-client#196]
**Describe the bug**
The documentation in line https://github.com/tus/tus-js-client/blob/master/lib/upload.js#L926 says that it shouldn't retry if the status code is 409 or 423 (assuming that "no" is a typo and should say "the error is server error (i.e. **not** a status 4xx or a 409 or 423)")

**To Reproduce**
1. Have an endpoint that return 409 or 423 status
2. Set some retry delays
3. Start upload to the endpoint

**Expected behavior**
Abort directly after the first try.

Even better would be to provide a callback to be handle to decide what error codes are acceptable. In our use case 403 would also be aborted in some cases.

**Version**
1.8.0

**Comment by PVince81** [comment]
So I found this in the tests: https://github.com/tus/tus-js-client/blob/master/test/spec/test-common.js#L752

Apparently it is the expected behavior. So the potential typo should be fixed to make it clearer.

**Comment by PVince81** [comment]
PR here for clarifying the code comment: https://github.com/PVince81/tus-js-client/pull/1

**Comment by PVince81** [comment]
Raised feature request https://github.com/tus/tus-js-client/issues/197 for providing a callback method

**Comment by Acconut** [comment]
Users usually want to retry on 423 Locked responses which is returned if an upload is still locked from a previous request. Disabling this feature can hurt the resumability functionality but that decision is up to you.

Closing in favor of #197 and #198.
