### ISSUE TITLE
onSuccess behaviour

### ISSUE THREAD

**Issue by Novelz** [tus/tus-js-client#199]
Good morning,
I set up a Vimeo upload system and everything is working fine. I've just some troubles with the onSuccess callback, is it normal that it's being fired multiple times? Not sure about the rate but it seems like everytime a chunk has been received the onSuccess fires.
Is it possibile to get a "final" callback or should I use a custom check in the onProgress method? 

**Setup details**
- Browser integration (Vimeo)
- Used tus-js-client version: v2

**Comment by Acconut** [comment]
No, this is should not happen and onSuccess is intended to only be called once. Can you share a screenshot of the network tab in your browser's developer console?

**Comment by Novelz** [comment]
Hi there! Thank you for you reply, seems it was a problem on my callback function. If it ever happen again I will post it here with more info.

Have a nice day!

**Comment by Acconut** [comment]
That's great to hear! I will close this issue for now but feel free to leave a comment if it comes up again.

**Comment by nitingupta220** [comment]
I have one question.
After uploading my successfully to vimeo using tus-js-client I get the response but in the response I didn't get the vimeo id which is used for many purposed like embedding and getting specific video details using that video_id.
<img width="803" alt="Screenshot 1942-05-05 at 1 27 30 AM" src="https://user-images.githubusercontent.com/25584421/88488061-58d48700-cfa8-11ea-9069-ad95036f23d3.png">
In the above screenshot after the vimeo.com/{video_id}
I didn't get that video in the response in `onSuccess` callback.

How to get this id after uploading?
@Acconut @Novelz @tim-kos @fahad19 @kvz

**Comment by Acconut** [comment]
> I didn't get that video in the response in onSuccess callback.

Yes, tus-js-client is not a Vimeo-specific library, so it does not return any Vimeo-specific data. In fact, the onSuccess callback does not get invoked with any arguments, so there cannot be any video ID in there.

> How to get this id after uploading?

I don't know. Isn't the video ID provided by the Vimeo API when you create an upload? I have never used the Vimeo API, so I can't tell. Please contact Vimeo support or consult the docs for more details.

> @Acconut @Novelz @tim-kos @fahad19 @kvz

Also, please refrain from mentioning random people in these thread. That's not a very nice behavior. We will respond to you but it might take some time.
