### ISSUE TITLE
node_modules/tus-js-client/lib/index has no default export.

### ISSUE THREAD

**Issue by Nathan-Froeh** [tus/tus-js-client#204]
**Describe the bug**
On angular 9 app, cannot import tus with 
import tus from 'tus-js-client';

**To Reproduce**
ng new tus-test
`npm install tus-js-client` or `npm install --save tus-js-client` on root app folder
import tus with `import tus from 'tus-js-client';`
In termainal run ng serve/npm run

Terminal error `node_modules/tus-js-client/lib/index"' has no default export.`

**Setup details**
```
Angular CLI: 9.1.6
Node: 12.14.1
OS: win32 x64
@angular-devkit/architect         0.901.6
@angular-devkit/build-angular     0.901.6
@angular-devkit/build-optimizer   0.901.6
@angular-devkit/build-webpack     0.901.6
@angular-devkit/core              9.1.6
@angular-devkit/schematics        9.1.6
@angular/cdk                      9.2.3
@angular/cli                      9.1.6
@angular/material                 9.2.3
@ngtools/webpack                  9.1.6
@schematics/angular               9.1.6
@schematics/update                0.901.6
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0```


TUS version
"tus-js-client": "^2.1.1",

``` "tus-js-client": {
      "version": "2.1.1",
      "resolved": "",
      "integrity": "sha1-572UIm4foYYPyyLWdBSxNHSoUIc=",
      "requires": {
        "buffer-from": "^0.1.1",
        "combine-errors": "^3.0.3",
        "js-base64": "^2.4.9",
        "lodash.throttle": "^4.1.1",
        "proper-lockfile": "^2.0.1",
        "url-parse": "^1.4.3"
      },
      "dependencies": {
        "buffer-from": {
          "version": "0.1.2",
          "resolved": "",
          "integrity": "sha1-FfS5vO8BIETfMRQsFDM8r24CYNA="
        }
      }
    },```

**Comment by Acconut** [comment]
That's weird, tus-js-client does not contain or reference a file called `lib/index.js`. So I am unsure where this error is coming from.

Did you recently upgrade from tus-js-client 1.x to 2.x? Maybe the caches need to be cleared in the compiler?

**Comment by t0n1grt** [comment]
I have same problems, ES Modules import with vue.js
import tus with import tus from 'tus-js-client';
and i get warning
`"export 'default' (imported as 'tus') was not found in 'tus-js-client'`

**Comment by Nathan-Froeh** [comment]
@Acconut no upgrades or anything, this is my first time trying to use tus and I've been on Angular 9 for a while with no problems.
I've tried uninstalling and re-installing, and restarting local server and no change.

**Comment by Nathan-Froeh** [comment]
I've made some progress and it looks like the docs are out of date.

The index.d.ts does not export Tus, it exports Upload, so `import { Upload } from 'tus-js-client';` works without error.

After that the docs say to start 
```var upload = new tus.Upload(file, {...}) ```
but since tus isn't an export it's just `var upload = new tus.Upload(file, {...}) `

**Comment by t0n1grt** [comment]
in my case i fixed my code, now i'm not using ES Module import,
`import tus with import tus from 'tus-js-client';`
to
`const tus = require("tus-js-client");`
and its working :)

**Comment by Acconut** [comment]
Ok, now I get the problem. Here's the gist:

```js
import tus from "tus-js-client"; // Does not work
import * as tus from "tus-js-client"; // Does work
const tus = require("tus-js-client"); // Does work
```

I will update the documentation accordingly. Thanks for bringing this up!
