### ISSUE TITLE
Make resolveUrl function configurable

### ISSUE THREAD

**Issue by dmytrohridin** [tus/tus-js-client#205]
**Is your feature request related to a problem? Please describe.**
Currently, we have backend and frontend application for uploading files via tus protocol. Our backend service located by the URL (example) ```app.com/upload```. When we create a file it returns ```/file/some_id```. The next request should be done via ```app.com/upload/file/some_id``` but ```resolveUrl``` will return ```app.com/file/some_id``` so request will be failed. Similar issue described in https://github.com/tus/tus-js-client/issues/148

**Describe the solution you'd like**
Make ```resolveUrl``` function configurable

**Describe alternatives you've considered**
For some reasons currently, we can not change backend implementation to return full path

**Can you provide help with implementing this feature?**
If the feature will be approved I can create PR for this

Thank you

**Comment by Acconut** [comment]
Thanks for the report but I don't see the problem inside tus-js-client here. Instead of modifying the URL resolver, the server/proxy should be fixed to properly return `/upload/file/some_id` instead of `/file/some_id`, so that the client is able to resolve the link without modifications. Does that make sense?

**Comment by dmytrohridin** [comment]
It makes sense, bit unfortunately we can not change server configuration for now, that’s why I asking. Also making resolver configurable doesn’t require braking change. But if it is not ok to make this change - I understand. Thank you

**Comment by Acconut** [comment]
Thanks for understanding that it's hard to justify a feature for one misconfigured server. You can, however, implement a custom HttpStack and rewrite the URLs in there to make sure that the /upload/ prefix gets added: https://github.com/tus/tus-js-client/blob/master/docs/api.md#httpstack

**Comment by dmytrohridin** [comment]
ok, will try, thank you
