### ISSUE TITLE
Attempted import error: 'tus-js-client' does not contain a default export (imported as 'tus').

### ISSUE THREAD

**Issue by israelKusayev** [tus/tus-js-client#206]
I used **tus-js-client** version `1.8.0`
And I upgraded it to version `2.1.1`, and remove **@types/tus-js-client**

now when I'm importing: 
```javascript
import tus, { UploadOptions, Upload } from 'tus-js-client';
```

I get this error 

> Attempted import error: 'tus-js-client' does not contain a default export (imported as 'tus').

It looks like you don't have export default in your index.d.ts

**Comment by Acconut** [comment]
Yes, tus-js-client does not have a default export. You should import it as `import * as tus from 'tus-js-client'` as mentioned in the docs: https://github.com/tus/tus-js-client/blob/master/docs/installation.md#install-from-npm-recommended
