### ISSUE TITLE
Promise onBeforeRequest, onAfterResponse

### ISSUE THREAD

**Issue by Mentthew** [tus/tus-js-client#211]
I want to pass a function for onBeforeRequest, onAfterResponse that returns Promise, but "tus-js-client" currently only supports a function with void return type.
https://github.com/tus/tus-js-client/blob/6f036d6ce61cddb03bacaead6d55ecf2aad25b60/lib/upload.js#L838
https://github.com/tus/tus-js-client/blob/6f036d6ce61cddb03bacaead6d55ecf2aad25b60/lib/upload.js#L844

**Comment by Acconut** [comment]
Good idea! Can you explain your use case a bit more? Would you be willing to open a PR for this?

**Comment by Mentthew** [comment]
I need it for encryption before upload (library for encryption which I use supports only async calls). Yes, I will open PR for this.

**Comment by skychavda** [comment]
Hey, I am using the onAfterResponse function to get data from header but unfortunately this function is not giving any kind of data.

**Comment by Acconut** [comment]
@skychavda I don´t fully understand your question. Please clarify with more detail. What exactly do you mean with "this function is not giving any kind of data"?

**Comment by skychavda** [comment]
@Acconut When I use this function in the callback of this function I didn't get a response after API call is done.

**Comment by Acconut** [comment]
@skychavda Please open a new issue with more details. Right now, we don´t have enough information from you to help.

**Comment by Acconut** [comment]
This has been implemented by now.
