### ISSUE TITLE
ie find missing or invalid Content-Type header 

### ISSUE THREAD

**Issue by a852882874** [tus/tus-js-client#213]
![1595412791(1)](https://user-images.githubusercontent.com/25943026/88164759-255fc880-cc47-11ea-87cb-d445217fd503.jpg)
![image](https://user-images.githubusercontent.com/25943026/88164791-327cb780-cc47-11ea-886f-16f99c1b0f34.png)

**Comment by Acconut** [comment]
Your Content-Type header contains a trailing comma. It's `application/offset+octet-stream, `. You must remove that comma.
