### ISSUE TITLE
Problem uploading to Vimeo Tus-resumable is not allowed by Access-Control-Allow-Headers in preflight

### ISSUE THREAD

**Issue by mbrimmer83** [tus/tus-js-client#219]
**Question**
Hello,
I am experiencing an error when trying to upload to Vimeo.  I have tried multiple combinations of headers and api version. Generally it appears the first request is made with the header `Tus-resumable` and the api doesn't like this. The second request is actually successful. I see another issues that are similar. [Tus-Resumable](https://github.com/tus/tus-js-client/issues/105) but nothing I have tried has helped. Any idea what the issue could be. I have reached out to Vimeo but have not received a response yet. The [Vimeo Upload Guide](https://developer.vimeo.com/api/upload/videos) outline specific headers for each request, is there a way to get the client to follow this pattern? Is there something I am missing? Any help is would be much appreciated.

The vimeo example doesn't provide detail on whether I need to first get the url from Vimeo, maybe this is the issue and tus client doesn't do this for me?

```
Access to XMLHttpRequest at 'https://api.vimeo.com/me/videos' from origin 'http://localhost:19006' has been blocked by CORS policy: Request header field tus-resumable is not allowed by Access-Control-Allow-Headers in preflight response.
```
```
HEAD https://api.vimeo.com/me/videos net::ERR_FAILED
```

![Screen Shot 2020-09-11 at 6 26 52 PM](https://user-images.githubusercontent.com/19143056/92978009-898b5580-f45c-11ea-8bed-c41b88823c88.png)

![Screen Shot 2020-09-11 at 6 27 04 PM](https://user-images.githubusercontent.com/19143056/92977989-7d06fd00-f45c-11ea-8a46-92fe49bed902.png)

My setup
```javascript
const uploadWithTus = (file) => {
  return new tus.Upload(file, {
     endpoint: 'none',
     uploadUrl: 'https://api.vimeo.com/me/videos',
    retryDelays: [0, 1000, 3000, 5000],
    metadata: {
      filename: file.name,
      filetype: file.type
    },
    resume: true,
    uploadSize: file.size,
    chunkSize: 5000000,
        headers: {
            Authorization: `Bearer ${VIMEO_ACCESS_TOKEN}`,
            'Content-Type': 'application/json',
            Accept: 'application/vnd.vimeo.*+json;version=3.4'
        },
        onError: function(error) {
            console.log("Failed because: " + error)
        },
        onProgress: function(bytesUploaded, bytesTotal) {
            var percentage = (bytesUploaded / bytesTotal * 100).toFixed(2)
            console.log(bytesUploaded, bytesTotal, percentage + "%")
        },
        onSuccess: function() {
            console.log("Download %s from %s", upload.file.name, upload.url)
        }
  })
}
```

**Setup details**
Please provide following details, if applicable to your situation:

- Runtime environment: [e.g. Browser, Node.js, React Native]
Browser (Chrome, Safari, Firefox) all the same issue.

- Used tus-js-client version: [can be obtained by running `npm ls`]
1.8.0 & 2.20 (I have tried using both)

**Comment by mbrimmer83** [comment]
I was able to solve the issue. I was under the impression based on the Vimeo example that `tus-js-client` would make the initial create video request for me and then handle the new upload url. I now understand that I need to first call Vimeo and create the initial video and then pass the upload url returned to the client.

```
export const createVideo = async (file, url, token) => {
  const body = {
    name: file.name,
    upload: {
      approach: 'tus',
      size: file.size
    }
  }

  const response = await fetch(url, {
    method: 'POST',
    mode: 'cors',
    cache: 'no-cache',
    credentials: 'same-origin',
    headers: {
      Authorization: `bearer ${token}`,
      'Content-Type': 'application/json',
      Accept: 'application/vnd.vimeo.*+json;version=3.4'
    },
    redirect: 'follow',
    referrerPolicy: 'no-referrer',
    body: JSON.stringify(body)
  })

  return response.json()
}
```

This was kinda a bone headed mistake on my part, but it is not very clear in the example. It's working great now and I want to leave this up until y'all close it for future developer who may run into this issue. I note of warning that Vimeo is very picky about the request headers and even though there docs told to  pass `Content-Type: application/offset+octet-stream` it didn't work.

Love the library, thanks for all you guys do.

**Comment by Acconut** [comment]
I am glad to read that you found a solution for this. I think ultimately Vimeo should improve their documentation so users like you don't event stumble across this problem. I will try to contact them.

**Comment by Lefthandmedia** [comment]
I'm having the same problem, could you please show me how you used the result of `createVimeoVideo`  with  `uploadWithTus`?
I assume you used the link propertie of `createVimeoVideo` as the uploadUrl in  `uploadWithTus ` but that doesn't work for me.

Tnx
RDG

**Comment by mbrimmer83** [comment]
> I'm having the same problem, could you please show me how you used the result of `createVimeoVideo` with `uploadWithTus`?
> I assume you used the link propertie of `createVimeoVideo` as the uploadUrl in `uploadWithTus ` but that doesn't work for me.
> 
> Tnx
> RDG

Hey @Lefthandmedia, below is an example of how I am using the above function to upload with tus lcient to Vimeo. It calls the create video function and then uses the tus client to perform the upload.
```
import * as tus from 'tus-js-client'
export default async function uploadToVimeo(file, onProgress) {
  const video = await createVimeoVideo(file)

  return new Promise((resolve, reject) => {
    const upload = new tus.Upload(file, {
      uploadUrl: path(['upload', 'upload_link'], video),
      headers: vimeoHeaders,
      retryDelays: [0, 1000, 3000, 5000, 10000, 20000],
      metadata: {
        filename: file.name,
        filetype: file.type
      },
      uploadSize: file.size,
      chunkSize: 5000000,
      onProgress: (loaded, total) => {
        onProgress(Math.round((loaded / total) * 100))
      },
      onError: err => reject(err),
      onSuccess: () => resolve(video)
    })
    upload.start()
  })
}

```

**Comment by mishhub-digiryte** [comment]
I just copied these code to my react app, and still getting me Cors errors. Do anyone know if there is any changes i need to make apart from this

**Comment by mbrimmer83** [comment]
@mishhub-digiryte My only suggestion would be to make sure you are calling Vimeo to create the asset before trying to upload it. The response from Vimeo should contain a url to upload to and that is what the tus client uses to perform the upload. My issue was not creating the Vimeo video before trying to upload it.

**Comment by kuboon** [comment]
You do not have to pass vimeo access token to tus-js-client. 
`https://api.vimeo.com/me/videos` should be called in server side, which nees vimeo token.

**Comment by mbrimmer83** [comment]
> ```js
> vimeoHeaders
> ```

It's been a long time since I worked on this, but Vimeo has [authentication documentation](https://developer.vimeo.com/api/authentication). I think the correct approach is to create/request the token server side and pass it to the client for usage. You could probably also build the video URL on the server and request the access token at the same time and pass both to the client for upload. I'm pretty sure you can request tokens from Vimeo from your server which is secured with a private access key/token.
