### ISSUE TITLE
Non latin characters in filenames ar not supported

### ISSUE THREAD

**Issue by Orajo** [tus/tus-js-client#22]
I'm using demo of tus-js-client to test my implementation of Tus server in PHP. I've found that this demo doesn't support files with non-latin chars in their filename, eg. "słońce.pdf". Another polish chars: ążęłóźć.

**Comment by Acconut** [comment]
Can you please describe your problem more detailed? What does not work? I have tested tus-js-client against a file with non-latin characters in its name and everything behave as I expected.

**Comment by Orajo** [comment]
The error is showed on the attached screen: 
![ashampoo_snap_2015 11 03_16h42m07s_001_tus-js-client demo - mozilla firefox](https://cloud.githubusercontent.com/assets/11492354/10912476/fa01ac0e-8249-11e5-89fc-15a9d7cf7d20.png)
Try to set the name "BitBłemą.png" on some file.

**Comment by Acconut** [comment]
Ok, thanks for helping. As it seems this only occurs in Firefox when trying to encode the filename using base64. I will have a look into it.

**Comment by Acconut** [comment]
Thanks for reporting, and fixed in d690b87fffa0eb864efb4ea424dac1587a7356e6. I will push a new version to NPM in the next days.
