### ISSUE TITLE
System becomes unresponsive on macOS while uploading files

### ISSUE THREAD

**Issue by maksimkurb** [tus/tus-js-client#220]
**Describe the bug**
Uploads on macOS in are significally slower and/or uses more CPU/RAM/swap than on Windows in the same network environment.
Some teammates reported system freezes while testing tus on official [Tus Demo](https://tus.io/demo.html), FPS in Chrome drops to 0.

Now I'm collecting reports from my mates with macOS.

**Report №1 on Google Chrome**:
Uploading a file with a size **~280mb**.
Swap immediately goes up to 10gb, on 50% upload drops to 500mb.
CPU load was max on upload start, then drops to 30%.
Sometimes Chrome tab freezes, FPS drops to 0.
Load was for a 3-4 times slower than on a Windows laptop in the same network.

**Profiling** from a Chrome DevTools can be find here:
[https://drive.google.com/drive/folders/1KmJ6FzT0nRhwzFguaYyYxWq3Qdh76zE-?usp=sharing](https://drive.google.com/drive/folders/1KmJ6FzT0nRhwzFguaYyYxWq3Qdh76zE-?usp=sharing)

On profiling we can see frame drops/tab freezes:
<img width="1870" alt="Screenshot 2020-09-25 at 23 30 28" src="https://user-images.githubusercontent.com/1351924/94332577-80b38b80-ffe7-11ea-9671-6bf87e3be1cd.png">

**Report №1 on Safari**:
Upload was nearly as fast, as on Windows laptop (same network).
RAM goes up to +2-3GB, then swap +2GB & RAM cleared, after upload swap is used on 1gb more than before upload

**Report №1 on Firefox**:
swap usage +10GB, but upload is very fast

**To Reproduce**
1. Go to official [tus-js-client demo](https://tus.io/demo.html)
2. Upload a [test file](https://drive.google.com/file/d/1UUYGuURT1LW-R3Vbp0O8ekW4dwNCMP9w/view?usp=sharing).

**Expected behavior**
No high CPU, RAM and swap usage (for ex. on Windows machine, RAM usage is not goes up at all, CPU usage is about 2-5%).
No frame drops, upload speed should be similar to Windows environment. System should not be unresponsive while uploading file. _On Windows there is no regions with frame drops on a profiling like on a screenshot from macOS above._

**Setup details**
Please provide following details, if applicable to your situation:
```
- Used tus-js-client version: latest? (official tus demo)
- Used tus server software: latest? (official tus demo)

Report №1:
MacBook Pro (13-inch, 2017)
CPU 2,3 GHz Dual-Core Intel Core i5
Memory 16GB 2133 MHz LPDDR3
Graphics Intel Iris Plus Graphics 640 1536MB
macOS Catalina 10.15.6

Google Chrome is up to date
Version 85.0.4183.121 (Official Build) (64-bit)
```

**Comment by Acconut** [comment]
Thank you for reporting! To be honest, I have never seen such behavior and also can't explain. My tests on Linux + Firefox with a 1.1 GiB file didn't result in excessive memory or CPU usage and the UI always stayed responsive during that time. I will ask a few collegues to try and reproduce this.

Do you have any browser extensions installed or any other software that was running during the test (e.g. virus scanners)?

**Comment by Acconut** [comment]
Does similar behavior occur when uploading similar large files on other websites?

**Comment by Acconut** [comment]
A colleague was able to reproduce the same behavior on macOS using your test file. However, when upload a file of 223 MiB, the issue did not appear. How does your system perform when uploading different files of similar size?

**Comment by maksimkurb** [comment]
My colleague has assumption that such behavious can be caused by macOS preview generation in file choosing dialog. When he disabled preview window, file uploaded without any noticed issues. This tiff is very large and seems that macOS doesn't stop preview generation after file was chosen. I personally don't own a macBook, so can't check it by myself.

About browser extensions, I don't think that they were responsive to this because first test was done in 3 different browsers and only Chrome had any extensions in it.

Similar behaviour occurred when my colleague tried to upload this file to DropBox with enabled preview generation.

![image](https://user-images.githubusercontent.com/1351924/94465715-60472500-01d1-11eb-852f-a2c84f1db83f.png)

**Comment by Acconut** [comment]
> My colleague has assumption that such behavious can be caused by macOS preview generation in file choosing dialog. When he disabled preview window, file uploaded without any noticed issues. This tiff is very large and seems that macOS doesn't stop preview generation after file was chosen. 

Ok, that explanation would make sense. It also explains why this behavior can only be seen for specific files. However, it also means that we, as tus-js-client, cannot do much to prevent this, can we? Maybe this should be filed as a bug to Apple, so they can fix it in their OS.

**Comment by maksimkurb** [comment]
Exactly. Second person confirmed that disabling preview pane solves this problem, so issue is macOS-related, not tus-js-client. Thanks for you time, I'm closing this issue then :)
