### ISSUE TITLE
Missing _xhr property after upgrading to 2.x

### ISSUE THREAD

**Issue by nylon22** [tus/tus-js-client#221]
**Question**
First of all, thanks for the great library. I'm upgrading our implementation of `tus-js-client` from `v1.7.1` to `v2.2.0`. From `v1.7.1`, our implementation makes use of the `_xhr` property of an instantiated `Upload`. After upgrading to `v2.x`, that property is not defined.

The following code returns the value of the response header `header-a` in `v1.7.1` and throws an exception for attempting to access `getResponseHeader` on an undefined property, `_xhr`, in `v2.2.0`

```js
const upload = new Upload(file, options);
const headerA = upload._xhr.getResponseHeader('header-a');
```

Is there another way to access this property in `v2.x`? Our implementation relies heavily on it.

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: Browser
- Used tus-js-client version: 2.2.0
- Used tus server software: Not relevant

**Comment by Acconut** [comment]
The `_xhr` property was an undocumented and private property that should not be used or relied on. I recommend you use the new request/response callbacks: https://github.com/tus/tus-js-client/blob/master/docs/api.md#onafterresponse

**Comment by nylon22** [comment]
thanks!
