### ISSUE TITLE
A safer way to check for unsupported callbacks

### ISSUE THREAD

**Issue by kohenkatz** [tus/tus-js-client#222]
**Is your feature request related to a problem? Please describe.**

I am working with [`vue-file-agent`](https://github.com/safrazik/vue-file-agent) which supports using `tus-js-client` as a plugin. It seems that it should be able to support version 1.x and 2.x at the same time with ***almost*** the same code, but with a few minor changes. It works almost perfectly; the specific issue that prevents it from working is the way that errors are thrown for callbacks. For example, `vue-file-agent` currently calls `abort()` with a callback as the second argument. This works for `tus-js-client` 1.x, but fails for 2.x.

**Describe the solution you'd like**

I need a way to check whether the version of `tus-js-client` that is loaded is the old callback-based version or the new promise-based version.

It should be very simple to do this by changing two lines in each function that throws such an error:

For example, change this:

```
  abort(shouldTerminate, cb) {
    if (typeof cb === "function") {
      throw new Error("tus: the abort function does not accept a callback since v2 anymore; please use the returned Promise instead");
    }
```

to this:

```
  abort(shouldTerminate) {
    if (arguments.length > 1 && typeof arguments[1] === "function") {
      throw new Error("tus: the abort function does not accept a callback since v2 anymore; please use the returned Promise instead");
    }
```

This would allow me to do something simple like this:

```
if (upload.abort.length === 2) then {
    upload.abort(false, callback);
} else {
    upload.abort(false).then(callback);
}
```

**Describe alternatives you've considered**

`tus-js-client` does not provide any other way that I could find to detect the version.

The only workaround I can think of is to use a `try`/`catch` like this, but it doesn't make sense to need to do that:

```
try {
    upload.abort(false, callback);
} catch(err) {
    upload.abort(false).then(callback);
}
```

**Can you provide help with implementing this feature?**

I would be happy to submit a PR if you'd like.

**Comment by Acconut** [comment]
Interesting case, we would be open for such a PR. Since the callback is not accepted anymore it would be better to not have it show up as an argument. Please be sure to include a code comment in your PR to explain the usage of `arguments`.
