### ISSUE TITLE
stream needs to be instanceof Readable

### ISSUE THREAD

**Issue by mifi** [tus/tus-js-client#229]
**Describe the bug**

Error `source object may only be an instance of Buffer or Readable in this environment` when trying to upload a stream which is not directly an instaceof `Readable`.

**To Reproduce**
```bash
yarn add tus-js-client@1.8.0 into-stream
```

index.js
```javascript
const tus = require('tus-js-client')
const intoStream = require('into-stream')

// into-stream returns a stream where instanceof stream !== Readable
const stream = intoStream('my test string')

const tusUpload = new tus.Upload(stream, {
  endpoint: 'http://localhost:1234',
  resume  : true,
  metadata: {
    fieldname: 'field',
  },
  onError: console.error,
  onSuccess: () => console.log('done'),
})

tusUpload.start()
```

```bash
node index.js

Error: source object may only be an instance of Buffer or Readable in this environment
    at getSource (node_modules/tus-js-client/lib.es5/node/source.js:234:12)
```

**Expected behavior**
Should upload the stream. I'm not sure if it's a bug but I think so, because other libraries handles these kind of streams without problems. For instance [form-data](https://github.com/form-data/form-data/) uploads it fine.

I think `instanceof Readable` is not the best way to determine if an object is a readable stream. See:
https://stackoverflow.com/questions/23885095/nodejs-check-if-variable-is-readable-stream

Maybe we can instead do something like this? https://github.com/sindresorhus/is-stream/blob/master/index.js

https://github.com/transloadit/node-sdk/issues/86

**workaround hack**

```js
const rawStream = intoStream(str)
const stream = new require('stream').PassThrough();
rawStream.pipe(stream);
```

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: Node.js
- Used tus-js-client version: 1.8.0

**Comment by Acconut** [comment]
A quick hint to begin with: tus-js-client 1.8.0 is a bit outdated and the 1.X releases are not maintained anymore. Please upgrade to 2.2.0, which is the latest release (see https://tus.io/blog/2020/05/04/tus-js-client-200.html for breaking changes). It probably won't solve your issue but at least we are talking about the same code.

To being said, I am open to moving to a check which does not rely on `instanceof` but instead uses something like `is-stream`. Would you be willing to open a PR for that?

**Comment by mifi** [comment]
Yea sorry, I just assumed that it was the same issue on the newest version because I found the culprit in `master` also. I tested with `v2.2.0` also and it has the same issue. Sure, I can make a PR for it
