### ISSUE TITLE
onProgress no update after refreshing page - vuejs

### ISSUE THREAD

**Issue by vghernandz** [tus/tus-js-client#232]
I am uploading videos to vimeo from my frontend, using tus-js-client. The load happens without problems and everything works fine, the `onProgress` function receives the load data fine. I am using vue and these are the functions that I use to load.

```js
async vimeoQueryLink () {
  try {
    const { size } = this.upload.video

    const body = {
      name: Number(new Date()).toLocaleString(),
      upload: {
        approach: 'tus',
        size
      }
    }

    const response = await fetch('https://api.vimeo.com/me/videos', {
      method: 'POST',
      mode: 'cors',
      cache: 'no-cache',
      credentials: 'same-origin',
      headers: {
        Authorization: 'bearer TOKEN',
        'Content-Type': 'application/json',
        Accept: 'application/vnd.vimeo.*+json;version=3.4'
      },
      redirect: 'follow',
      referrerPolicy: 'no-referrer',
      body: JSON.stringify(body)
    })

    return response.json()
  } catch (error) {
    console.log(error)
  }
}
    
async vimeoUploadVideo () {
  const { upload } = await this.vimeoQueryLink()

  const tusUpload = new tus.Upload(this.upload.video, {
    uploadUrl: upload.upload_link,
    onError (error) {
      console.log('vimeoUploadVideo: error =>' + error)
    },
    onProgress (bytesUploaded, bytesTotal) {
      /**
      *   After refreshing the page, it only shows when it starts and when it loads 100%
      **/
      
      const percentage = (bytesUploaded / bytesTotal * 100).toFixed(2)
      console.log(bytesUploaded, bytesTotal, percentage + '%')
    },
    onSuccess () { 
      console.log('Download %s from %s', tusUpload.file.name, tusUpload.url)
      console.log('vimeoUploadVideo: finish')
    }
  })

  tusUpload.start()
}

```

The problem happens when I update the page, for some reason, the `onProgress` function only indicates 0% and 100% load, it does not show the progress during the upload of the video.

The video uploads to vimeo 100%, I just don't know the% load while it uploads. To make it work once again I have to clear all the manual cache or refresh with ctrl + f5

Check if it was saving something in the localstorage or cookies but I don't see anything that could link or cause the problem.

**Comment by vghernandz** [comment]
Problem caused by service worker configuración. 😑

**Comment by mkgn** [comment]
I have the same problem with VueJS. it jumps from 0% 100%. what do you mean by service worker configuration? How did you fixed it?

**Comment by Acconut** [comment]
If it jumps directly from 0% to 100% it could be that the file is not uploaded again, because you instructed tus-js-client to resume previous uploads and it realizes that it uploaded the file already, so it does not repeat the upload again. Are you using the findPreviousUploads method?

**Comment by mkgn** [comment]
Nope. just 

    new tus.Upload(files[0], this.options).start() //omitting other code.

In options I have;

            onProgress: function (bytesUploaded, bytesTotal) {
                var percentage = (bytesUploaded / bytesTotal * 100).toFixed(2);
                methodScope.currentProgress = percentage;
            },

here methodScope is basically the reference to the VueJS component and currentProgress is a data field that gets bound to the view template. problem is this onprogress event is fired once. So progress bar fills at 100 after everything has gone to server. No errors logged what so ever. 

I don't think it's an error on Vue or Tus.. may be I am missing something in wireup. That is why I asked what made it to work for @vghernandz

**Comment by Acconut** [comment]
Ok, are you using tus-js-client v2 or v1?

**Comment by mkgn** [comment]
Using "library": "tus-js-client@2.3.0" ....

**Comment by vghernandz** [comment]
Hi guys!

based on my problem was the following, I was using `nuxtjs` in my project and had integrated` @ nuxtjs / firebase` in the latter, to be able to use the uth ssr I had to call a `sw` file [here](https://firebase.nuxtjs.org/tutorials/ssr)

So, I needed to exclude from the requests the video provider where I was uploading, `vimeo` was my case and with this the` onProgress` function worked fine, but unfortunately for a long time I had little time to try it.

I asked in the nuxt `pwa-module` project [here ](https://github.com/nuxt-community/pwa-module/issues/422)and I had no answers for the short time available. In the end I solved removing from my project `@ nuxtjs / firebase`

**Comment by mkgn** [comment]
In my case it's pure vuejs and nothing else. For server side I am using tusdotnet. Everything works perfectly except for this progress. I feel it's something to do with my configuration but since it doesn't throw any error/warning I can't figure it out.

**Comment by Acconut** [comment]
What does the options look like that you are passing to `new tus.Upload`?

**Comment by mkgn** [comment]
Well it goes like this;

            this.options = {
            endpoint: uploadEndPoint,
            retryDelays: [0, 1000, 3000],
            parallelUploads: 1,
            metadata: {
                filename: null,
                filetype: null
            },
    onError ... onProgress ... onAfterResponse ...

my onProgress is like;

                onProgress: function (bytesUploaded, bytesTotal) {
                var percentage = (bytesUploaded / bytesTotal * 100).toFixed(2);
                methodScope.currentProgress = percentage;
            },

**Comment by Acconut** [comment]
Ok, thanks. Those options look normal and sensible. Nothing that would be suspicious immediately. Maybe it is indeed caused by Vuejs.

**Comment by mkgn** [comment]
I am also now thinking the same. Let's close the case and will get back if I find anything new which i think is related to tus. Thank you.

**Comment by Allaccessfans** [comment]
Add this to your fetch function in your service worker. J's

if (event.request.url.indexOf('tus') !== -1) {
  return;
}
