### ISSUE TITLE
Problem with /resume and https.

### ISSUE THREAD

**Issue by AlertRED** [tus/tus-js-client#233]
**Question**
When I deploy my site on production server i have a problem with https.
Tus is sending resume's query by http, but should be https:
![image](https://user-images.githubusercontent.com/15695000/105450877-0271a800-5cae-11eb-813c-14bb9d4d30fe.png)

upload function returns Location = /files/resume/<file_id>. I mean, that is not absolute path

My js code:
```javascript
var upload = new tus.Upload(file, {
                endpoint: "{{ url_for('dashboard.upload') }}",
                retryDelays: [0, 3000, 5000, 10000, 20000],
                metadata: {
                    filename: file.name,
                    filetype: file.type
                },
                onError: function(error) {
                    console.log("Failed because: " + error)
                },
                onProgress: function(bytesUploaded, bytesTotal) {
                    let percentage = (bytesUploaded / bytesTotal * 100).toFixed(2);
                    progress_bar.style.width=percentage.toString() + "%";
                    label_upload.innerText = `Загружено ${formatSizeUnits(bytesUploaded)} / ${formatSizeUnits(bytesTotal)} (${percentage.toString()}%)`;
                },
                onSuccess: function() {
                    is_loaded = elem.getElementsByTagName('input')[0];
                    is_loaded.setAttribute('value', upload.url);
                    check_form_filled();
                }
                })
```

**Setup details**

- Runtime environment: Browser
- Used tus-js-client version: 2.2.0
- Used tus server software: Myself

**Comment by Acconut** [comment]
Could you generate a HAR file and send it over, so I can inspect the requests? https://mediaplanhq.zendesk.com/hc/en-us/articles/360001171463-Generating-a-HAR-file-for-troubleshooting

**Comment by AlertRED** [comment]
> Could you generate a HAR file and send it over, so I can inspect the requests? https://mediaplanhq.zendesk.com/hc/en-us/articles/360001171463-Generating-a-HAR-file-for-troubleshooting

Here it is
[inmotion.fablite.tech.har.zip](https://github.com/tus/tus-js-client/files/5857509/inmotion.fablite.tech.har.zip)

**Comment by hannojg** [comment]
Ran into the exact same issue

**Comment by hannojg** [comment]
Just had to reconfigure our reverse proxy (nginx) to `X-forwarded-proto`, so that tusd can see the original protocol used by the client.
