### ISSUE TITLE
fingerprint changes everyday i want to keep it same for everyday for a particular device

### ISSUE THREAD

**Issue by prerna-bhatra** [tus/tus-js-client#235]
**Describe the bug**

**To Reproduce**
1. Execute command '...'
2. Start upload '...'
3. See error

Please try to reproduce the problem when uploading to our public tus instance at [https://tusd.tusdemo.net/files/](https://tusd.tusdemo.net/files/), if applicable to your situation. This helps us to determine whether the problem may be caused by the server component.

**Expected behavior**

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: [e.g. Browser, Node.js, React Native]
- Used tus-js-client version: [can be obtained by running `npm ls`]
- Used tus server software: [e.g. tusd, tus-node-server etc]

**Comment by Acconut** [comment]
You did not provide any description about the bug you are experiencing. Please fill out the issue template or we cannot help you.

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)
