### ISSUE TITLE
The hook onShouldRetry should be asynchronous.

### ISSUE THREAD

**Issue by wfmcodev** [tus/tus-js-client#236]
The hook onShouldRetry is synchronous. The hook can be useful to refresh an authorization token if it expire (in case of 401 error for example).
Anyway the refreshing process is asynchronous as a request to the server must be done.

The solution could be to have the onShouldRetry function returns a Promise<boolean> instead of just a boolean.

The only alternative solution is to write a class that implements the HttpStack interface. But this would be quite demanding for such simple task.

Thanks for the great library.

**Comment by Acconut** [comment]
> The hook can be useful to refresh an authorization token if it expire (in case of 401 error for example).

I do not think this would work. tus-js-client is not designed to change the headers after an Upload object is created. You can monkey patch the options object, but this is not intended to be modified and we do not guarantee that this will work in future releases.

Instead, I recommend following approach:

* return false in `onShouldRetry` if you detect a 401 response to stop the retry attempts.
* fetch a new authorization token
* once you have the token, create a new Upload object with the new authorization token and pass in the same file as before and the upload URL from before. Then tus-js-client will resume the upload from before but use the new authorization token.

**Comment by aduh95** [comment]
Having a way to programatically decide how long should be the retry delay would be very useful. My use case is when the client has several `tus.Upload` instances working in parallel and the server starts to respond with 429 error code, we would want to avoid tus scheduling all the retry requests at the same time, as it would almost inevitably lead to the server re-responding with 429...

I think an ideal API would be to accept any (Async)Iterable as `retryDelays`, so I could use e.g. a generator function that would return longer delays if the server has responded with a 429. I'll try to work on a PR doing that.

**Comment by Acconut** [comment]
@aduh95 I think an easier way for your specific case you be to simply return false in onShouldRetry if a 429 occurs. Then you can call Upload#start after your desired delay.

Making retryDelays an iterable looks like avoidable complexity that is only useful is rare situations. So I am bit cautious with such decisions.
