### ISSUE TITLE
The onShouldError is missing on npm

### ISSUE THREAD

**Issue by Luperco** [tus/tus-js-client#237]
Hi, I'm using the tus-js-client in an Angular application. I've installed the library using npm.

Anyway, it seems that the last version available from npm (2.2.0) is outdated as some fixes present in this repository are not released on the npm module.

In particular, the onShouldError function is not present in the index.d.ts module. Problem fixed three months ago in this repository.

Is it possible to update the npm repository with the new fixes? In alternative is it possibile to have some instruction on how to include the cloned library in an Angular application?

Thanks.

**Comment by Acconut** [comment]
Apologies for not responding faster here. A new version of tus-js-client has been published in the meantime, of course!

**Comment by Luperco** [comment]
I'll check it soon. Thanks.
