### ISSUE TITLE
source object may only be an instance of Buffer or Readable in this environment

### ISSUE THREAD

**Issue by a852882874** [tus/tus-js-client#252]
![image](https://user-images.githubusercontent.com/25943026/112746224-1607fa80-8fe0-11eb-8af2-0c6aca9cfee0.png)

**Comment by Acconut** [comment]
More details needed. We can't help you if all you provide is a screenshot of some error. Please fill out the entire issue template.

**Comment by m-cat** [comment]
Apparently you can't pass type `File` if you're on Node. This needs to be fixed though. I have a tus browser method that operates on File and I'm not able to test it with `jest`.

**Comment by Acconut** [comment]
@m-cat I am not sure how `File` support in Node.js would work, since there is not standard `File` object in Node.js. Or am I missing something?

**Comment by m-cat** [comment]
> @m-cat I am not sure how `File` support in Node.js would work, since there is not standard `File` object in Node.js. Or am I missing something?

Apologies for the delayed response. I'm not a JS expert, so it's probably me who's missing something. But I am able to test other functions that expect `File`, i.e.
```ts
const file = new File([fileData], filename);
```
However, tus explicitly contains a check that rejects a `File` input. I'm sure this is for good reason, but it means that I can't test my file the same way. I remember trying to convert it to a `Buffer` and not succeeding, but I'll give that another try.

**Comment by m-cat** [comment]
Looks like the error was actually a TS error that was causing the test to fail. It runs and works if I disable the TS error with `// @ts-ignore`, but the typing should be fixed.

**Comment by Acconut** [comment]
That's good to know, thanks @m-cat. We will have a look at the type definitions!

**Comment by Acconut** [comment]
Tracking progress of better definitions in https://github.com/tus/tus-js-client/issues/289
