### ISSUE TITLE
Do you have multiple files to upload demo

### ISSUE THREAD

**Issue by aidigu** [tus/tus-js-client#253]
Do you have multiple files to upload demo

The official example is only a single file upload, and I hope to upload more files to demo

**Comment by Acconut** [comment]
No, tus-js-client only supports uploads of a single file. If you want multiple files, you can create multiple instances of tus.Upload. Alternatively, I can also recommend Uppy.js (https://uppy.io), which builds on tus-js-client and support uploading multiple files.
