### ISSUE TITLE
how to get the custom filename in the onSuccess or onAfterResponse function

### ISSUE THREAD

**Issue by apchenjun** [tus/tus-js-client#268]
How to get the custom filename returned by the backend in the onSuccess or onAfterResponse function
![image](https://user-images.githubusercontent.com/4964551/124585407-d4f96f00-de87-11eb-9037-dfb3f6c68c3d.png)

**Comment by Acconut** [comment]
If your tus server is able to attach the filename as a header in the response (how to do this depends on your tus server; you seem to be using .NET with which I have no experience, so you may ask the maintainer), you are able to extract this header value from the response object in the onAfterResponse callback. Refer to the API documentation for more details.

**Comment by apchenjun** [comment]
@Acconut 
I can get the value in onAfterResponse ，but now I am debugging it will be called multiple times, how do I judge to get the head parameters after uploading is complete

**Comment by Acconut** [comment]
onAfterResponse will be called for every response it gets. You can check in the callback whether it is a response to a PATCH request. Alternatively, you can store the value from the PATCH request and only use it in the onSuccess callback to ensure that the header value is also from the **last** PATCH response.

**Comment by apchenjun** [comment]
@Acconut Thank you for your answer, I understand what you mean。

**Comment by apchenjun** [comment]
@Acconut It is recommended to add a parameter that can accept a return to the onSuccess function, which is best。

**Comment by Acconut** [comment]
> @Acconut It is recommended to add a parameter that can accept a return to the onSuccess function, which is best。

I don't understand that sentence, sorry.

**Comment by apchenjun** [comment]
@Acconut  i hope the onSuccess function can accept the returned parameters

**Comment by Acconut** [comment]
I still don´t understand what you are referring to but tus-js-client ignores the return value of the `onSuccess` method for now.

**Comment by apchenjun** [comment]
I mean it is recommended to be able to accept the return value in the onSuccess function

**Comment by Acconut** [comment]
Well, I don't see a reason against this. onSuccess will always be called after onAfterResponse, so you can access value in onSuccess that were set in onAfterResponse.

**Comment by apchenjun** [comment]
@Acconut  thank you Hope the new version can be improved
