### ISSUE TITLE
Local storage details doesn't seem to get cleared

### ISSUE THREAD

**Issue by mkgn** [tus/tus-js-client#272]
**Describe the bug**
Tus client seems to be writing some information to browser storage. However they keep collecting and not getting cleared even if files are uploaded successfully.

**To Reproduce**
1. Just upload a file, make sure it's successful
2. See local storage tab in dev tools
3. you can see stale entries, even those that happened. see below
4
![image](https://user-images.githubusercontent.com/8392595/129301502-73ac72da-d0d4-4805-ad17-3435d112d05c.png)

**Expected behavior**
Once the file is successful updated these data should be cleared

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: [e.g. Browser, Node.js, React Native]
- Used tus-js-client version: [can be obtained by running `npm ls`] - latest
- Used tus server software: [e.g. tusd, tus-node-server etc] tus-dot-net

**Comment by Acconut** [comment]
This is not a bug, but the indended behavior. If you want to clear entries from localStorage upon completion, use the removeFingerprintOnSuccess option: https://github.com/tus/tus-js-client/blob/master/docs/api.md#removefingerprintonsuccess
