### ISSUE TITLE
Success Handler didn't get Fired.

### ISSUE THREAD

**Issue by Aadilmusavir** [tus/tus-js-client#274]
Hi, I used tus.io
![COnsoleError](https://user-images.githubusercontent.com/18436397/130486631-0542dd85-8239-43a6-9a9b-598c3913e4d6.png)
![COde](https://user-images.githubusercontent.com/18436397/130486643-df0acb77-70df-4b54-99f1-87e858a0b2ae.png)
 for my react project for resume-able uploads, 

I am able to upload 100% on server.  (bytesUploaded == bytesTotal) condtion matches, still the success handle didn't gets called,  using "tus-js-client": "^2.3.0" , 
network tabs shows me 
Post Calll
head call
patch call here everthing gets uploaded 
then in continoues loop only head call , head call,

i am attaching my code and console errors via attachment.

please check why this behaviour, 
and please share some examples how can we delete files from server via tus

**Comment by Aadilmusavir** [comment]
After One week , The issue is not with tus client, the issue is, if there is any bug in code , tus client stop working  and giving messages.

here in this i am trying to console undefined value , that is the reason i am not able to fire success handler. hence this is not issue with tus, so i am closing this issue.

**Comment by Acconut** [comment]
Glad to read that you found the issue!

**Comment by Aadilmusavir** [comment]
Is there a way to update header in between calls.

Actually I want to use this client but after two minutes my authorization
token refreshes.
 That leads me to 401 not authorized error.
 Then I'm unable to update header,

Is there a way to update header which we set at beginning
