### ISSUE TITLE
404 and 405 errors

### ISSUE THREAD

**Issue by kimwebParis** [tus/tus-js-client#28]
Hello,

Thanks for your work!
I'm trying to make it work but I have 2 to errors: 404 (/tus/demo/null ) and 405 (The requested method PATCH is not allowed for the URL /tus/demo/null)

May be it's very simple but I can't find any solution...

Can you help me?

Best Regards
Fanny

**Comment by Acconut** [comment]
Thanks for bringing this to our attention but, unfortunately, I am not able to understand how these errors appeared. Would you be so kind and describe more detailed what you did before the issues occurred?

**Comment by Acconut** [comment]
Closing due to lack of information. Feel free to comment again if new details appear.
