### ISSUE TITLE
Before uploading, how to package, compress and encrypt files before uploading?

### ISSUE THREAD

**Issue by a852882874** [tus/tus-js-client#288]
excuse me.I want to implement a package compression encryption after upload, how to do？

**Comment by Acconut** [comment]
I have never used JavaScript to make a tar file and compress it. You can probably use something like https://github.com/ankitrohatgi/tarballjs and get the resulting file as a `Blob`. This blob can then be given to tus-js-client to upload it like any other normal file. Please do you own research on what is the best way to create TAR files with ZSTD compression. I have never done that before.

**Comment by a852882874** [comment]
Oh, oh, thank you. Let me check again
