### ISSUE TITLE
Don't clear fingerprint on error

### ISSUE THREAD

**Issue by infinite-persistence** [tus/tus-js-client#300]
If I tried to resume once, and encounter a `423` error, the fingerprint is automatically removed due to this line:
https://github.com/tus/tus-js-client/blob/4479b78032937ac14da9b0542e489ac6fe7e0bc7/lib/upload.js#L609

Doesn't that go against the comment of the following line, which says that `423` is normal and should be resummable later?
```
        // If the upload is locked (indicated by the 423 Locked status code), we
        // emit an error instead of directly starting a new upload. This way the
        // retry logic can catch the error and will retry the upload. An upload
        // is usually locked for a short period of time and will be available
        // afterwards.
        if (status === 423) {
          this._emitHttpError(req, res, 'tus: upload is currently locked; retry later')
          return
        }
```

Can we not auto-remove the fingerprint + create new upload, and let the user decide instead?

**Comment by Acconut** [comment]
Yes, that is a good suggestion from you! I think we should switch the two if-statements. They currently look like this:

```js
      if (inStatusCategory(status, 400)) {
          // Remove stored fingerprint and corresponding endpoint,
          // on client errors since the file can not be found
          this._removeFromUrlStorage()
        }

        // If the upload is locked (indicated by the 423 Locked status code), we
        // emit an error instead of directly starting a new upload. This way the
        // retry logic can catch the error and will retry the upload. An upload
        // is usually locked for a short period of time and will be available
        // afterwards.
        if (status === 423) {
           return ...
```
 But if we switch their order, a 423 will not lead to deleting the entry in the url storage. Would you be willing in opening a PR for this?
