### ISSUE TITLE
Resumable Vimeo upload not working with tus js?

### ISSUE THREAD

**Issue by CrackTheCode016** [tus/tus-js-client#301]
Hi all,

I have a pretty simple setup - user picks a video from the gallery, we convert the video into a blob, then we create the Vimeo upload url (which i have confirmed to be consistent), then we create an `Upload()` object to upload the video via tus to Vimeo:

```js
   const blob = await fetch(`data:video/mp4;base64,${b64}`).then((res) =>
      res.blob()
    );
    const uploadLink = await this.generateVideoUploadUrl(blob.size);
    let fileName = this.path.substring(this.path.lastIndexOf('/') + 1);

    const upload = new Upload(blob, {
      endpoint: uploadLink,
      uploadUrl: uploadLink,
      retryDelays: [0, 1000, 3000, 5000],

      onError: function (error) {
        console.log('Failed because: ' + error);
      },
      onProgress: function (bytesUploaded, bytesTotal) {
        console.log('progress');
        var percentage = ((bytesUploaded / bytesTotal) * 100).toFixed(2);
        console.log(bytesUploaded, bytesTotal, percentage + '%');
      },
      onSuccess: function () {
        console.log('Download %s from %s', upload.file, upload.url);
      },
    });

    upload.start();
```

However, I get nothing in terms of the video being uploaded or any signs in the console. Any reason as to why this could be?

Please provide following details, if applicable to your situation:
- Runtime environment: Ionic 5 with Capacitor 
- Used tus-js-client version: tus-js-client@2.3.0
- Used tus server software: using Vimeo

**Comment by Acconut** [comment]
I don´t see any apparent issue with your code. However, we have never tested tus-js-client with Capacitor, so I can´t comment whether they are compatible. Did you check whether your calls to `fetch` and `this.generateVideoUploadUrl` work properly and return what you expect? Do you see any activity in your network monitor?

**Comment by stebogit** [comment]
@CrackTheCode016 I noticed the Vimeo API [docs specify](https://developer.vimeo.com/api/upload/videos#resumable-approach-step-2) the Header `Accept: 'application/vnd.vimeo.*+json;version=3.4'` is required when pushing data via tus, try adding that:
```js
const upload = new Upload(blob, {
  uploadUrl: uploadLink,
  headers: {Accept: 'application/vnd.vimeo.*+json;version=3.4'},
  // ...
}
```
Also how do you generate the `uploadUrl` and how does it look like?

**Comment by artem-tarasenko** [comment]
```js
const upload = new Upload(blob, {
      endpoint: uploadLink,
      uploadUrl: uploadLink,
      ...
}
```

This should be different.
`uploadUrl` - you are getting from the response when you create new vimeo video (POST request with filename, filesize etc)
`endpoint` - is a fixed url provided by vimeo, same as for POST request

You are basically firstly POST for a new video and then PATCH that video to add data there, `endpoint` should be the same -  `https://api.vimeo.com/me/videos`

**Comment by Acconut** [comment]
The `endpoint` option is actually not needed at all, if `uploadUrl` is provided. It can be left out.

**Comment by Acconut** [comment]
Thanks for all the answers! Going to close this issue as the author did not show any activity.

**Comment by divyasri93** [comment]
I'm facing the same issue with uploading videos to Vimeo in my ionic capacitor app in Android/iOS. I converted the selected file to a Blob using fetch and then created a Vimeo upload URL. Then initialized a new tus.Upload() instance with the blob and called .start(). But nothing happens .. onProgress is not triggered and there is no success or errors in console. onAfterResponse logs a 200 response with an empty body. The video does not appear on Vimeo!

Environment:

   Ionic CLI:  7.2.0 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework: @ionic/angular 8.5.0
   @angular-devkit/build-angular : 18.2.16
   @angular-devkit/schematics: 18.2.16
   @angular/cli : 18.2.16
   @ionic/angular-toolkit : 11.0.1

    tus-js-client: v4.3.1

    Upload server: Vimeo tus endpoint

I’ve ensured the blob is non-empty (verified size), but the upload still doesn’t start or show any signs of progress .. Any guidance or workaround would be greatly appreciated. Thanks!

**Comment by Acconut** [comment]
@divyasri93 Please open a new issue and include your code calling tus-js-client. Also ensure that your code follows the example in https://github.com/tus/tus-js-client/blob/main/docs/usage.md#example-upload-to-vimeo, in particular the use of `uploadUrl` instead of `endpoint`.

**Comment by divyasri93** [comment]
Yes I use uploadUrl .. will open a new issue. Thanks.
