### ISSUE TITLE
Accessing response text in onSuccess?

### ISSUE THREAD

**Issue by rackfishdaniel** [tus/tus-js-client#304]
**Question**
How to access responseText from target from 'onSuccess'. We can't seem to find a way to do it the same way we can in onError, etc. In our specific use case we need access to the final response from the server side in onSuccess to retrieve metadata from the created upload.

**Comment by Acconut** [comment]
You can use the onAfterResponse methods to access response bodies.

**Comment by mdxiaohu** [comment]
> You can use the onAfterResponse callback to access response bodies.

OnSuccess is the confirmation that the file upload has been completed.
OnAfterResponse seems unable to achieve this, is there a better way?
Is it possible to return the URL of the currently uploaded file when onSuccess is completed.
Looking forward to a reply.
