### ISSUE TITLE
Browser demo isn't working

### ISSUE THREAD

**Issue by Kartik18g** [tus/tus-js-client#305]
**Describe the bug**
I cloned the repository, installed the dependencies and built it. 
But when I try to run the web browser demo, it throws an error "Access to XMLHttpRequest at 'https://tusd.tusdemo.net/files/3fce73985973ce233b71804f30daa94e+qG9Ik6RsfBsuTkmTcXtiOvfQoO2DpRZH72oR5njBNi0VXpM5B71_aAt3UyW29.66GBHmhLIhjKqsHdZ7uPIxwAZgXEu10_mvD9f5AtqUmvrY4bv2MVyfSVXj2RhmR3xz' from origin 'http://127.0.0.1:5502' has been blocked by CORS policy: Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response."

**To Reproduce**
1. npm install
2. npm run build
3. run the index.html file

**Expected behavior**
the video should upload

**Comment by Acconut** [comment]
This is not a bug in the demo or tus-js-client. As the error says, your server http://127.0.0.1:5502/ is not properly configured to send the correct CORS headers for allowing HTTP requests: 

> origin 'http://127.0.0.1:5502' has been blocked by CORS policy: Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response."

Please properly configure CORS on your server and it should work. tus-js-client cannot fix this problem by itself.

**Comment by Kartik18g** [comment]
Hey, thanks for your reply but i found the 

https://user-images.githubusercontent.com/70897225/147744868-a51d6b05-678c-43ff-947e-95e66ebcaf50.mov

same bug on https://tus.io/demo.html. If I use incognito to make a request it works fine.

**Comment by Kartik18g** [comment]
> Hey, thanks for your reply but i found the
> 
>  Screen.Recording.2021-12-30.at.4.13.35.PM.mov 
> 
> same bug on https://tus.io/demo.html. If I use incognito to make a request it works fine.

I get this error when I try to upload from tus.io 
Access to XMLHttpRequest at 'https://tusd.tusdemo.net/files/987ab897dd0bbf4a4e2b631098787cb0+u7Cvn8ybBlHWTcxXv1vQQ5r2jYdwRxN8oxIODCkhicRhJswmt5smgAnplyIlDQJOD37Qws.DrPqYK.xb.WXt_0cxd45q37jR46dYTf6iUZCTkjo5jTgKC9vsBAp4uxSB' from origin **'https://tus.io**' has been blocked by CORS policy: Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response.

**Comment by Acconut** [comment]
That is weird since the demo is working fine for me. Could it be that you have some browser extension installed or are using some proxy that could be messing with HTTP requests?

Can you try other browsers on your device and see if the demo works there?

**Comment by Kartik18g** [comment]
Oh!! i had a allow CORS extension that was messing up the HTTP requests, I disabled it and it worked 😅. Thank you it works now.

**Comment by Acconut** [comment]
Glad you found the culprit! :)
