### ISSUE TITLE
Unable to use resumable Vimeo uploads using tus-js-client

### ISSUE THREAD

**Issue by Kartik18g** [tus/tus-js-client#307]
**Question**
I'm trying to upload a resumable video to vimeo using tus-js-client. 
Here's my code
1) I make a request to vimeo first to create a upload

<pre>
 const response = await axios({
      method: 'post',
      url: `https://api.vimeo.com/me/videos`,
      headers:{
         Accept: 'application/vnd.vimeo.*+json;version=3.4',
          Authorization: `bearer ${accessToken}`,
          Content-Type': 'application/json'
       },
      data: {
        upload: {
          approach: 'tus',
          size: fileSize
        }
      }
    });
</pre>

2) Now I use tus client to upload the video

<pre>
const upload = new tus.Upload(file, {
      endPoint: 'https://api.vimeo.com/me/videos',
      uploadUrl: response.data.upload.upload_link,
      retryDelays: [0, 3000, 5000, 10000, 20000],
      metadata: {
        filename: file.name,
        filetype: file.type
      },
      chunkSize: 51200000,
      headers:{},
      onError: function (error) {
        console.log('Failed because: ' + error);
      },
      onProgress: function (bytesUploaded, bytesTotal) {
        let percentage = ((bytesUploaded / bytesTotal) * 100).toFixed(2);
        console.log(bytesUploaded, bytesTotal, percentage + '%');
        setProgress(bytesUploaded)
      },
      onSuccess: function () {
        console.log('Download %s from %s', upload.file.name, upload.url);
        setVideoUrl(upload.url);
      }
    });
</pre>

Here, this code works fine if I don't have to pause this upload, but if I pause an upload and need to resume it vimeo requires us to have these headers

<pre>
{
  'Tus-Resumable': '1.0.0',
  'Upload-Offset': upload_offset_value,
  'Content-Type': 'application/offset+octet-stream',
  Accept: 'application/vnd.vimeo.*+json;version=3.4'
}</pre>
but when i add these headers to the tus client, it throws an error. "Failed because: Error: tus: unable to resume upload (new upload cannot be created without an endpoint), originated from request (response code: 412, response text: )"

I just can't resume an upload because this error keeps on showing up. 

Any help is useful

**Comment by Acconut** [comment]
Please contact the Vimeo support for this question or look through [Vimeo related issues](https://github.com/tus/tus-js-client/issues?q=is%3Aissue+Vimeo) reported by other users. I personally have no experience with Vimeo's API, and cannot help you in this regard, but maybe these resources provide more insights.

**Comment by 11ume** [comment]
Thanks, it worked fine! I just had to pass it the http request to the tus instance, as this is a readable stream it works without problems. 

```js
 const CHUNK_SIZE = 5000000 // 5MB
  const upload = new tus.Upload(readable, {
    endpoint: '',
    chunkSize: CHUNK_SIZE,
    uploadSize: size,
    retryDelays: [0, 1000, 3000, 5000],
    onError,
    onProgress,
    onSuccess: () => onSuccess(uri),
  })

  upload.url = uploadLink
  return upload
```

Now I have another problem but it has to do with fetch (browser).


I need to send the loading process to the browser, for this I am using fetch and ReadableStreams, but I have some problems, if I can solve them I could give you an cool example.

**Comment by Acconut** [comment]
@11ume I think your response is meant for another ticket (https://github.com/tus/tus-js-client/issues/306) and not this issue, or is it?

**Comment by 11ume** [comment]
I have not had problems loading videos on vimeo, you first need make a request to get the upload link from vimeo API.
You can you my example repo: [vimeo-video-uploader](https://github.com/11ume/vimeo-video-uploader)

```js
const CHUNK_SIZE = 5000000 // 5MB
  const upload = new tus.Upload(readable, {
    endpoint: '',
    chunkSize: CHUNK_SIZE,
    uploadSize: size,
    retryDelays: [0, 1000, 3000, 5000],
    onError,
    onProgress,
    onSuccess: () => onSuccess(uri),
  })

  upload.url = uploadLink // vimeo video upload link
  return upload
```

**Comment by Kartik18g** [comment]
I found out the problem, so what happens is that tus-js-client automatically makes a head request to Vimeo to get offsets and then starts making patch requests with header offset.
I was earlier doing it myself and adding those headers with "headers" option, and that caused it to fail.
