### ISSUE TITLE
Usage with webpack emits warning about tus-js-client

### ISSUE THREAD

**Issue by jonase** [tus/tus-js-client#31]
I'm using webpack (version 1.12.11) and get the following warning when I build my project:

```
WARNING in ./~/tus-js-client/dist/tus.js
Critical dependencies:
1:476-483 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/tus-js-client/dist/tus.js 1:476-483
```

To reproduce:

Create a file `index.js` with a single require:

```
var tus = require('tus-js-client');
```

and run `webpack index.js bundle.js`.

**Comment by iperdomo** [comment]
Acording to @IngwiePhoenix on this thread https://github.com/webpack/webpack/issues/1617#issuecomment-181713671 the `main` of `package.json` should point to `index.js`

**Comment by IngwiePhoenix** [comment]
Hey!

@iperdomo is right. Most of the pre-built files are really big. You want to include the actual index file.

But I see it is coded with ES6. So what you will have to do is adjust your Babel loader to include these files also.

In your config, have a loader like this specified:
```
{
  loader: "babel",
  test: /\.js$/,
  include: [
    path.join(__dirname, "node_modules/tus-js-client/")
  ]
}
```

In your app, require it like:
```
var tus = require("tus-js-client/lib/index");
```

I know it isn't the most prettiest way to do that for now. There are multiple workarounds for this, but this is one that should work.

Alternatively you can use module aliases and define one like so:

```
modules: {
  alias: {
    "tus-js-client$": "tus-js-client/lib/index"
  }
}
```

which would allow you to `require("tus-js-client")`.

**Comment by IngwiePhoenix** [comment]
Alternatively one could utilize the `esnext:main` field in `package.json`...

**Comment by jonase** [comment]
@IngwiePhoenix, @iperdomo Thanks! I will try this workaround

**Comment by IngwiePhoenix** [comment]
@jonase Welcome :)

Also, tus seems interesting. Thanks for making me find it  @iperdomo =)

**Comment by Acconut** [comment]
Thank you for bringing this to our attention and @IngwiePhoenix for already providing a workaround. I will have a look if I can improve anything on our end. :)

> @IngwiePhoenix: Also, tus seems interesting.

Thank you :heart:

**Comment by Acconut** [comment]
I apologize that I do not have a quick fix for this but I haven't really spent time with webpack before.

> @IngwiePhoenix: Alternatively one could utilize the `esnext:main` field in `package.json`...

Could you please describe this approach more detailed or link to some external documentation. I was not able to find a reference to this in webpack. Or do you talk about `jsnext:main` which is used by Rollup (https://github.com/rollup/rollup/wiki/jsnext:main)?

Anyway, one way to get rid of this warning is by compiling the ES6 (or ES2015, I actually don't know) files inside `lib/` to ES5 and then point the `main` property to the resulting file. If this approach works a expected with other bundles, I may choose it.

**Comment by IngwiePhoenix** [comment]
@Acconut Yes - `jsnext:main` is used by webpack but might be supported by webpack in the future.
- https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L83-L88
- https://github.com/webpack/webpack/issues/1612#issuecomment-158466366

So your options:

- Add the `jsnext:main` field, point it at your ES6 entry, and tell the user to update his config accordingly.
- Transpile the output into a folder like `es5-src/` and distribute that _and_ the original ES6 source.
    - Make `main` point to `es5-src/index.js` (for example)
    - Make `jsnext:main` point to `src/index.js`
- Only distribute ES5 compiled sources and add them for `main` only.

If you use pre-publish scripts, or a tool like `publish-please`, then I would actually recommend the 2nd. This allows for both, the pretty version and the transpiled version, to be used. Since Babel isn't particularily small, I wouldn't recommend another aproach in which one adds an NPM `build` script that could look like:

    "build": "babel src/*.js es5-src/"

(Note:  I forgot Babel's CLI. So this is a mock, you'll get what i mean.)

**Comment by Acconut** [comment]
> @IngwiePhoenix:  Yes - `jsnext:main` is used by webpack but might be supported by webpack in the future.

I guess, this should be read as
> is used by Rollup but might be supported by webpack in the future.

Your extensive answer is really appreciated by me and we will probably choose the 2nd option, distributing the original and transpiled source code. Thank you :)

**Comment by IngwiePhoenix** [comment]
@Acconut I edited my answer just after posting it. I am a derp sometimes =).
Glad the answer is helping!

**Comment by Acconut** [comment]
I publish version `0.1.4` to the registry which now includes the transpiled code meaning that you should be able to require this module without warning and workarounds. I am not sure if I want to keep the transpiled code in the Git repository yet, but that is another question. Please try it out (@jonase) and provide us with feedback. :)

**Comment by jonase** [comment]
@Acconut I can confirm that version `0.1.4` works as expected. Many thanks!

**Comment by Acconut** [comment]
@jonase You're welcome :)
