### ISSUE TITLE
Can `localStorage` usage be completely turned off?

### ISSUE THREAD

**Issue by infinite-persistence** [tus/tus-js-client#315]
**Question**
I have `storeFingerprintForResuming` turned off and was assuming `localStorage` will no longer be used if so, and it seems like the case as I don't see any entries in devtools.  

However, I'm seeing `QuotaExceededError` from some users:
`tus: failed to upload chunk at offset 0, caused by QuotaExceededError: The quota has been exceeded., originated from request (method: PATCH...`

I peeked at the code and don't think it is being used when `storeFingerprintForResuming` is turned off, but I'm not 100% sure.  There is an initial test to see if localStorage is usable, but that's covered by a try-catch and is not part of the upload, so should be unrelated.

Does the `tus-js-client` need localStorage regardless, and if not, what else do I need to set to disable the use?

**Comment by Acconut** [comment]
Are you using the `findPreviousUpoads` method? If so, that will also access localStorage, so please remove these calls.

If you want to be completely sure that localStorage is never accessed, you can pass an instance of `NoopUrlStorage` to the `urlStorage` option for the `tus.Upload` constructor: https://github.com/tus/tus-js-client/blob/708df610aa9dcd2416930bc5e6fd45015bfd80bb/lib/noopUrlStorage.js#L3

Hope that helps!
