### ISSUE TITLE
Look at dropzone

### ISSUE THREAD

**Issue by hpvd** [tus/tus-js-client#32]
Maybe one could adopt / learn some interesting things from
https://github.com/enyo/dropzone

dropzone's good looking and ease of use
in combination with tus
**would be a perfect combination.**

**Comment by kvz** [comment]
A few tus developers are currently working on http://uppy.io which will have dropzone-like functionality, as well as support for other file sources. Of course, everybody is free to use tus for any type of integration, but Transloadit's resources in this area will be mostly focussed on Uppy.

**Comment by hpvd** [comment]
Many thanks for pointing to uppy.
Found this before and it was looking awesome.

But was a bit frightened
reading "not be used for anything serious yet."
and looking at 
https://github.com/transloadit/uppy/blob/master/CHANGELOG.md#todo

there seems to be several month or even years to go?
or  is it a little conservative?

**Comment by hpvd** [comment]
just opened an issue regarding which points maybe interesting:
https://github.com/transloadit/uppy/issues/59

**Comment by kvz** [comment]
Yes, it's not usable I'm afraid. But I suppose at the same time, no one has started working on dropzone/tus as far as I know, so perhaps that's farther away even :scream: 

I was merely saying our own company's resources will be focussed on getting Uppy to a usable state a.s.a.p., vs diluting it over sever higher level tus js projects. 

This does not mean no-one else should work the tus/dropzone angle, feel free to do so. We'd still be happy to assist with guidance where needed.

As for an Uppy timeframe, if it's years, I consider us a failure : ) So months, yes. If you want to help us develop or test it, that would be grand of course!
