### ISSUE TITLE
Unable to load video to vimeo

### ISSUE THREAD

**Issue by vraja-pro** [tus/tus-js-client#324]
Hello!
I'm trying to upload a video via the [resumable approach](https://developer.vimeo.com/api/upload/videos#resumable-approach-step-1), I'm able to get the upload_link through PHP curl and jquery ajax 
then I'm trying to upload the file but I receive 412 error.

"Failed because: Error: tus: unable to resume upload (new upload cannot be created without an endpoint), originated from request (method: HEAD, url: https://asia-files.tus.vimeo.com/files/vimeo-prod-src-tus-asia/123456789, response code: 412, response text: , request id: n/a)" (123456789 is just a dummy number here)

I tried to remove the headers but I get 404 error which seems worse to me, so I kept the headers.
I'm unable to upload the file via Postman (testing API software)which is also weird, PATCH with binary data in body, I get a response 204 that there is no content.
When I try the HEAD request for the upload_link via Postman (testing API software), I get status 200. 

**Expected behavior**
The file should have been uploaded to Vimeo in chunks...

         function resumable(url) {
                    // Get the selected file from the input element
	             let file = $('#video')[0].files[0];
	           var chunkSize = 128;
                      // Create a new tus upload
	              const upload = new tus.Upload(file, {
	                	uploadUrl: URL,
		                headers:{
			"Tus-Resumable":	"1.0.0",
			"Accept":	"application/vnd.vimeo.*+json;version=3.4"
		          },
		          //endpoint: URL,  I created the link manually, doesn't work even if I add here the same URL for uploadUrl
		             chunkSize,
		            retryDelays: [0, 3000, 5000, 10000, 20000],
		           metadata: {
		              	filename: file.name,
		            	filetype: file.type
	         	},

    	        uploadSize: file.size,
		onError(error) {
			console.log(`Failed because: ${error}`);
		},
		onProgress(bytesUploaded, bytesTotal) {
			const percentage = ((bytesUploaded / bytesTotal) * 100).toFixed(2);
			console.log(bytesUploaded, bytesTotal, `${percentage}%`);
		},
		onSuccess() {
			console.log('Download %s from %s', upload.file.name, upload.url);
		},
      })

    // Check if there are any previous uploads to continue.
    upload.findPreviousUploads().then(function (previousUploads) {
        // Found previous uploads so we select the first one. 
        if (previousUploads.length) {
            upload.resumeFromPreviousUpload(previousUploads[0])
        }
  
          // Start the upload
           upload.start()
       })
        }

- Runtime environment: [Browser: Crome, WordPress, PHP]
- Used tus-js-client version: [1.0.0]
cdn: ttps://cdn.jsdelivr.net/npm/tus-js-client@latest/dist/tus.min.js

**Comment by Acconut** [comment]
I don't use Vimeo so I can´t help you much with it. Please have a look at previous issues regarding uploads to Vimeo: https://github.com/tus/tus-js-client/issues?q=is%3Aissue+vimeo Very often, people described their solution in closed issues. If that does not help, please contact Vimeo's support.

**Comment by artem-tarasenko** [comment]
You probably have figured out that by now but still, here is what work for me:

```js

        const upload = new tus.Upload(file, {
            endpoint: 'https://api.vimeo.com/me/videos',
            uploadUrl: *link sent by vimeo*,
            retryDelays: [1000, 3000, 5000],
            metadata: {
                filename: file.name,
                filetype: file.type,
            },
            onError: function (error: any) {
                 ...
            },
            onProgress: function (bytesUploaded: number, bytesTotal: number) {
                 ...
            },
            onSuccess: function () {
                 ...
            },
        });
```

no extra endpoint, no headers, also no size (it's already defined, part of the data in the first request to create video)

**Comment by Acconut** [comment]
@artem-tarasenko Thanks for your help. Going to close this then.
