### ISSUE TITLE
BUG: Exception when using chunking with react-native on ios

### ISSUE THREAD

**Issue by samal-rasmussen** [tus/tus-js-client#326]
Setting the chunkSize option while uploading with a react-native app on ios gives an error like this:

```
[native] Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]' was thrown while invoking sendRequest on target Networking with params (
        {
        data =         {
            blob =             {
                "__collector" =                 {
                };
                blobId = "DEC847CE-F341-45D8-915A-EBCBCA612CCC";
                offset = 3145728;
                size = 1048576;
            };
            trackingName = unknown;
        };
        headers =         {
            "content-type" = "application/offset+octet-stream";
            "tus-resumable" = "1.0.0";
            "upload-offset" = 3145728;
        };
        incrementalUpdates = 1;
        method = PATCH;
        responseType = text;
        timeout = 0;
        url = <snip>
        withCredentials = 1;
    },
    28507
)
```

**Cause**
The crash is caused by the blob being freed prematurely. There's an open pr to fix this:
https://github.com/facebook/react-native/pull/31392

**To Reproduce**

I've made a minimal reproduction here:
https://github.com/samal-rasmussen/tus-js-client-slice-bug/tree/master
And applied the fix here:
https://github.com/samal-rasmussen/tus-js-client-slice-bug/tree/fix

**Comment by samal-rasmussen** [comment]
I've opened this bug report just for tracking purposes. The underlying bug is actually in react-native.

**Comment by Acconut** [comment]
Thank you very much for reporting this underlying bug in React Native. If I understand correctly, we cannot do much right now but wait for the bug to be resolved?

**Comment by samal-rasmussen** [comment]
Yup. The actual underlying bug is in react-native and must be fixed there. I've just opened this issue here because the bug breaks a feature of tus-js-client, and so that the react-native devs can see that it has some actual effects on other projects :)

**Comment by samal-rasmussen** [comment]
This has been fixed in react-native for a while now.
