### ISSUE TITLE
Vimeo. Loading fails after 100%

### ISSUE THREAD

**Issue by artem-tarasenko** [tus/tus-js-client#330]
**Describe the bug**
With a simple example of using the library I'm trying to load videos to Vimeo. When I use `tus.Upload` with a basic set of options, file is being loaded to the server successfully, but the library doesn't fire `onSuccess` event after 100% load, instead I have an error event.

**Expected behavior**
After 100% uploading fire onSuccess event

**Setup details**
I'm using the library (2.3.1) in react 18. Uploading to Vimeo.
The config is the following
```js
const upload = tus.Upload(file, {
        uploadUrl: vimeoFileUrl,
        retryDelays: [0, 5000, 10000],
        onError: function(error) {
            console.log('TUS Failed because: ' + error);
        },
        onProgress: function(bytesUploaded, bytesTotal) {
            let percentage = ((bytesUploaded / bytesTotal) * 100).toFixed(2);
            console.log(bytesUploaded, bytesTotal, percentage + '%');
        },
        onSuccess: function() {
            console.log('TUS Download finished', initBasicUploader.file.name, initBasicUploader.url);
        },
    });

upload.start();
```

What exactly happens I don't know but for some reason, this code goes alright all the way until "loading 100%", then repeat this in console for 5 times and throws an error.

```console
TUS Failed because: Error: tus: failed to resume upload, caused by TypeError: Cannot read properties of undefined (reading 'name'), originated from request (method: HEAD, url: https://europe-files.tus.vimeo.com/files/vimeo-prod-src-tus-eu/05d28ec…, response code: n/a, response text: n/a, request id: n/a)
```

Meanwhile, I can see the testing video uploaded to Vimeo just fine. That's confusing.
Myabe you can shed some light into what the library expects from the server when it's 100% uploaded the video or what happens there. Thanks.

**Comment by Acconut** [comment]
From the error message, it seems as if you are trying to access the property name of an undefined object in your onSuccess callback:

> initBasicUploader.file.name

initBasicUploader.file is undefined. That is not a bug in tus-js-client but your code probably. However, tus-js-client should mask sch user errors more clearly!

**Comment by artem-tarasenko** [comment]
As my case where I had used the library long changed, I cannot check that code again and see if the problem was on my part or not, so let's assume the lib works as it should and close the issue, thanks for your response anyway.
