### ISSUE TITLE
Failed to read the 'localStorage' property from 'Window'

### ISSUE THREAD

**Issue by arturi** [tus/tus-js-client#36]
See here: http://requirebin.com/?gist=dbd801b40d276a16b88f16d144ade92a

Full error message: “lib.es5/upload.js:19 Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.”

Code here: https://github.com/tus/tus-js-client/blob/master/lib/upload.js#L5

Proposed solution: wrap in a condition, so tus-js does not blow up in a case like this?

**Comment by Acconut** [comment]
Frankly, I am surprised that it is even disallowed to access the localStorage object without reading or writing to it. Do you mind if I postpone this until the Node compatibility update has landed as this will make it easier since the localStorgae handling has been moved into it's own file?

**Comment by arturi** [comment]
Sure, that sounds like a good idea, thanks!
