### ISSUE TITLE
Should demo client automatically start a new upload on 423 LOCKED status?

### ISSUE THREAD

**Issue by terrischwartz** [tus/tus-js-client#37]
I start uploading a file in one browser tab, open a 2nd tab and try to start upload of the same file.  Tus-js-client in 2nd tab tries to resume and sends a HEAD request.  Server responds with 423 LOCKED.  I'm surprised that tus-js-client then decides to start a  new upload of the file.  Shouldn't the 423 indicate that an upload is likely in progress and a new one should only be started if the user explicitly requests that?

**Comment by Acconut** [comment]
You are absolutely correct. Right now, the client will always create a new upload if the server responds with a `2XX` status code. This is probably, as you said, not the best approach we want. I will change this.

**Comment by Acconut** [comment]
I finally had a situation where an upload got locked regularly helping me to debug and implement a proper solution for this. I apologize for the delay.
