### ISSUE TITLE
File not loading after page refresh

### ISSUE THREAD

**Issue by ValentinYushKevich** [tus/tus-js-client#370]
I am uploading videos from my frontend, using tus-js-client. Frontend  vue 2.  If I refresh the page, the tusUpload.findPreviousUploads() method does not find pending uploads and does not continue uploading the file if I select it again

My upload method

`   async uploadVideo () {
      let file = event.target.files[0]

      const payload = {
        filesize: file.size,
        filename: file.name
      }

      const { data } = await this.uploadKinescopeVideoV2({ workspaceId: this.workspace.id, payload })

      const config = {
        uploadUrl: data.endpoint,
        chunkSize: 1000000,
        retryDelays: [0, 3000, 5000, 10000, 20000],
        onProgress: (bytesUploaded, bytesTotal) => {
          const allProgress = +(bytesUploaded / bytesTotal * 100).toFixed(2).split('.')[0]
          if (allProgress > this.progressing) this.progressing = allProgress
        },
        onSuccess: async () => {
          const { data: fetchedVideData } = await this.fetchKinescopeVideo(data.id)
          this.insertVideoInWidget (fetchedVideData, file)
        }
      }

      const tusUpload = new tus.Upload(file, config)

      const previousUploads = await tusUpload.findPreviousUploads()
      console.log('previousUploads', previousUploads)

      if (previousUploads.length) {
        tusUpload.resumeFromPreviousUpload(previousUploads[0])
      }

      tusUpload.start()

    },`

Thanks for any hint

**Comment by ValentinYushKevich** [comment]
![image](https://user-images.githubusercontent.com/95743857/170942993-ac20c963-d569-409d-827a-71a4652ed460.png)

**Comment by Acconut** [comment]
tus-js-client will not save upload URLs in localStorage, if you pass the `uploadUrl` option. See https://github.com/tus/tus-js-client/issues/238#issuecomment-771874185 for more details on the current situation and see https://github.com/tus/tus-js-client/pull/323 where improvements are discussed.
