### ISSUE TITLE
It's time for a new release

### ISSUE THREAD

**Issue by hpvd** [tus/tus-js-client#38]
isn't it?
![2016-06-30_17h01_39](https://cloud.githubusercontent.com/assets/5681880/16493063/7bbfda16-3ee4-11e6-9351-c9698bed3f04.png)

**Comment by Acconut** [comment]
90% of these commits were made to introduce compatibility with Node.js which is still considered a unstable feature. Therefore we would like to get feedback from the Uppy team before releasing it officially (maybe @harryh @aturi or @kvz could share some of their time management plans). An the remaining tests are mostly restructuring how we are running our automated tested and did not introduce new functionality for the library.

Also, I forgot to tag the 1.1.4 release in Git. Basically, we are going to do a new release once the features are tested a bit but thanks for pointing it out. If you want to use the latest version in your app you should be able to point it directly to the Github repository.

**Comment by hedgerh** [comment]
I am almost to the point where I am going to introduce tus into uppy server.  I will update once I've had some time to use it.

**Comment by hpvd** [comment]
@Acconut many thanks for explanation :-)
