### ISSUE TITLE
Failed because: Error: tus: failed to upload chunk at offset 195035136

### ISSUE THREAD

**Issue by juloliveira** [tus/tus-js-client#39]
I´m testing tus-js-client with tusd.
The tusd is running in Ubuntu Desktop 16.04 in Virtualbox and tus-js-cliente demo in Windows host with Firefox.
The tusd is configured with parameter -s3-bucket, 
All works fine, but an error always happen in upload process. When click in "Ok" the process continues but after some minutes the error occurs again.

"Failed because: Error: tus: failed to upload chunk at offset 62914560
Do you want to retry?"

After many click´s in "Ok" button, the upload is completed and file is correct in AWS S3

What can is happening?

![image](https://cloud.githubusercontent.com/assets/46576/16923494/f5082b3e-4cf0-11e6-9269-af1c24dfd2e7.png)

**Comment by Acconut** [comment]
First of all, I want to thank you for this detailed explanation and, in particular, the screenshot. Here's what I believe is happening: The long running uploads (the `PATCH` requests) get, at some point, interrupted. I cannot exactly tell why, with the information you provided, but there are quite a lot of reasons. Anyway, the tus protocol has been engineered with these incidents kept in mind and provides a way to resume directly after the interruption.

Now here's the deal: the tus-js-client demo (the page you have opened in Firefox) will not automatically resume and will **always** ask you before doing the actual resume. This is why pressing the `OK` button always will, in the end, result in a complete upload. On our soon roadmap is an entry which will add automatically resuming to tus-js-client meaing the script can handle these cases without user interaction.

I hope this answers helps you :)

**Comment by juloliveira** [comment]
Thank you for you repply!

I did try increase the timeout via parameters in tusd but them same error occurs yet.

Again, executing the upload process, now in Google Chrome, in colsone tab I fount the error above:

![image](https://cloud.githubusercontent.com/assets/46576/16929652/1752a1ba-4d0f-11e6-9b14-2b78cee1e188.png)

**Comment by Acconut** [comment]
A connection reset error is sadly not very helpful. Does the output of the tusd process revile something about misbehavior? Could you please post it's output here?

**Comment by juloliveira** [comment]
In tusd output don't have nothing to help us

I am thinking that can be a problem with proxy of the my company.
Today, in home, I will test in a EC2 server and post results here.

Thank you!

![image](https://cloud.githubusercontent.com/assets/46576/16930677/ae8b614e-4d13-11e6-80ab-a7b896344f0f.png)

**Comment by Acconut** [comment]
Indeed, the tusd output is not helpful in this case. Furthermore, I agree with out that any proxy in between may cause these interruptions. However, as I said, these should not matter anymore once we implemented automated resuming as described above.

**Comment by Acconut** [comment]
The 1.4.1 release of tus-js-client has been published and contains the automated retries feature I have mentioned the last times. This should eradicate the issues you were experiencing. Since this has also been deployed to tus.io/demo.html, I would be pleased if you could give it a try.
