### ISSUE TITLE
uploadUrl not working

### ISSUE THREAD

**Issue by cometta** [tus/tus-js-client#40]
I try pass custom url to "uploadUrl" to resume to different file location, but it does not work. Any working example on how to use this ?

**Comment by Acconut** [comment]
What exactly does not work? Could you please provide more information about which part misbehaves in what manner? Nobody can help you if you don't get more specific.

A good example to look at is the way how retries are implemented in the demo example: https://github.com/tus/tus-js-client/blob/master/demo/demo.js#L54-L58

**Comment by cometta** [comment]
let me elaborate more. Once a file is successfully uploaded to server, the path would be saved in browser local storage. If I move the file in the server to another location.  For subsequent upload for the same file,  I would like it to upload/resume on a separate path in server, how can I do that?

**Comment by Acconut** [comment]
If you want to resume an upload at a specific URLs, you use the uploadUrl property as follwing;

```js
var upload = new tus.Upload(file, {
  endpoint: ...,
  uploadUrl: yourUploadUrlForThisSpecificFile,
  ...
})
upload.start()
```

If the client is not able to resume the upload at the given URL because it does not point to a proper tus upload endpoint, it will create a new upload using the supplied endpoint.
