### ISSUE TITLE
What is the correct way to validate file type / mime type?

### ISSUE THREAD

**Issue by nmg196** [tus/tus-js-client#417]
What is the correct way to validate file type / mime type to ensure the user is only uploading JPEG images?

I see there is an onBeforeRequest() method which has access to `this.metadata`  but I can't see how I could use this function to block the upload. 

I'd rather show an error even before they click an upload button but there doesn't seem to be a "onFileSelected" hook.

Or should I be doing this only on the server?

Thanks!

**Comment by samal-rasmussen** [comment]
You have full control to do your own checking on the file before you call `tus.Upload` with it. So don't call tus.Upload if it is something other than jpeg.

https://stackoverflow.com/a/29672957/628418

**Comment by nmg196** [comment]
Perfect - that link is exactly what I didn't find ;)   Thanks!
