### ISSUE TITLE
Success Upload Response over HTTPS, but error return HTTP

### ISSUE THREAD

**Issue by tresnaa** [tus/tus-js-client#418]
I think I Success to upload into TUS Server (over HTTP endpoint)
![issue-A](https://user-images.githubusercontent.com/5511946/177548267-22b58f51-4cd8-4a88-ba4d-84884a2146d5.png)

But, why the response like this? cors error, because return URL is HTTP?
![issue-B](https://user-images.githubusercontent.com/5511946/177548288-431227fc-463d-41fb-ad34-1601a6037515.png)

I try to config the NGINX, but still error. is it error from client side?

Thank you for helping me.

**Comment by Acconut** [comment]
Are you using tusd? Have you followed all steps in https://github.com/tus/tusd/blob/master/docs/faq.md#can-i-run-tusd-behind-a-reverse-proxy?

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)
