### ISSUE TITLE
Cannot resume uploads, unsafe headers

### ISSUE THREAD

**Issue by davidgourde** [tus/tus-js-client#42]
I start uploading a large file of 1GB and let it upload around halfway before closing the tab (Chrome). I open the page again and start to upload the same file. I always receive this message:

```
Failed because: Error: tus: invalid or missing offset value
Do you want to retry?
```
The error in the console is:
`upload.js:257 Refused to get unsafe header "Upload-Offset"xhr.onload @ upload.js:257`

I am using `tus-js-client` to test this (the demo) and it works fine with tusd (in Go). This problem only occurs with `tus-node-server`. I also tried the tus-jquery-client, but it fails to resume uploads (it restart from 0% again each time).

My server is only a copy paste of the Quick Start code provided in the README under "Build a standalone server" on the `tus-node-server` GitHub page.

Uploading files works fine too, but never resumes correctly.

**Comment by Acconut** [comment]
I assume this was successfully fixed by a patch in tus-node-server. Is this correct?
