### ISSUE TITLE
multi upload using tus-client-js in React

### ISSUE THREAD

**Issue by cojoclaudiu** [tus/tus-js-client#422]
**Question**
Hello, I working on a upoload integration with the Vimeo API for resumable uplaods using tus.
To allow user to upload multiple files at the same time I call the function in a loop and for each file I create. Everything works perfect but I would like to implement the option to pause and resume the upload.

I created a React custom hook where I have a factory function for tus where I return:

```ts
const tusUpload = (response: VimeoPostResponse, file: FilePreview, index: number) => {
const upload = new tus.Upload(file, {
	endpoint: import.meta.env.VITE_VIMEO_API_URL,
	uploadUrl: response.upload.upload_link,
	retryDelays: [0, 3000, 5000, 10000, 20000], // seconds
	chunkSize: 5000000, // 5000000 bytes = 5 MB
	storeFingerprintForResuming: true,

	metadata: {
		filename: file.name,
		filetype: file.type,
	},
	headers: {
		Accept: 'application/vnd.vimeo.*+json;version=3.4',
	},
             ...
return {
	startOrResumeUpload: () => {
		// Check if there are any previous uploads to continue.
		upload.findPreviousUploads().then((previousUploads) => {
			// Found previous uploads so we select the first one.
			if (previousUploads.length) {
				upload.resumeFromPreviousUpload(previousUploads[0]);
			}

			// Start the upload
			upload.start();
		});
	},

	pause: () => {
		upload.abort(true);
	},
};
```

I'm calling the function inside the function like this:
```ts
if (videoFiles.length > 0) {
	for (let i = 0; i < videoFiles.length; i++) {
		triggerVimeo({
			fileSize: videoFiles[i].size,
			name: videoFiles[i].name,
		})
			.unwrap()
			.then((response) => {
				tusUpload(response, videoFiles[i], i).startOrResumeUpload();
				triggerAddVideo({
					origin_model,
					origin_model_id,
					vimeo_object: response,
					filename: videoFiles[i].name,
				});
			});
	}
}
```

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: Browser, React JS created with vite
- Used tus-js-client version: "tus-js-client": "^3.0.0-0",

**Comment by Acconut** [comment]
I don't know what your actual question is. You have described your setup and showed code, but what is your question/problem?

**Comment by cojoclaudiu** [comment]
> I don't know what your actual question is. You have described your setup and showed code, but what is your question/problem?

Hi, thank you for replay. My problem is when I pause the video upload. The pause implementation doesn't work.

**Comment by Acconut** [comment]
What do you mean doesn't work? What is happening? What are you expecting to happen?

Be aware that the `true` argument in `upload.abort(true)` causes the upload to be deleted, so that it **cannot** be resumed. This is also explained in the documentation. I do not think you want to use `true` here.

**Comment by cojoclaudiu** [comment]
I'm expecting to pause and resume an upload. I will try another implementation without true argument, but I was trying few implemententions and nothing worked.

**Comment by Acconut** [comment]
You need to be more specific or we cannot help you. Are you seeing any errors? What HTTP requests are sent? What does the network tab in the dev tools show? What implementations did you try out? Without such details, we can provide any assistance. Please be more descriptive than writing two sentences.

**Comment by cojoclaudiu** [comment]
@Acconut sorry for the late reply. I think I found the issue. The start and pause wrking fine just if I don't start the upload inside the loop.
`ts
const onMediaUploadHandler = async () => {
	try {
		// NON VIDEO FILES UPLOAD
		if (nonVideoFiles.length > 0) {
			xhrUpload({
				files: nonVideoFiles,
				origin_model,
				origin_model_id,
			});
		}

		// VIDEO FILES UPLOAD
		if (videoFiles.length > 0) {
			for (let i = 0; i < videoFiles.length; i++) {
				triggerVimeo({
					fileSize: videoFiles[i].size,
					name: videoFiles[i].name,
				})
					.unwrap()
					.then((response) => {
						// TUS Object
						// tusUpload(response, videoFiles[i], i);

						// SET UPLOAD
						setUploads((prev) => [...prev, tusUpload(response, videoFiles[i], i)]);

						triggerAddVideo({
							origin_model,
							origin_model_id,
							vimeo_object: response,
							filename: videoFiles[i].name,
						});
					});
			}
		}
	} catch {
		//	handler err
	}

	dispatch(apiSlice.util.invalidateTags(['Media']));
};`

If I call tusUpload(response, videoFiles[i], i).start() inside the loop than the upload is starting but I can't pause it anymore.

If I don't call it inside the loop and I call each object manually clicking on the start than the pause/resume will work. But doing this my uploads doesn't start automatically anymore.

**Comment by Acconut** [comment]
> If I don't call it inside the loop and I call each object manually clicking on the start than the pause/resume will work. But doing this my uploads doesn't start automatically anymore.

Yes, you must call `tus.Upload#start()` to begin the upload. I am not seeing this in your code above. It seems like some mistake in your logic. I don't know your application, but couldn't you just do this in your loop:

```js
const upload = tusUpload(response, videoFiles[i], i);
upload.start();
setUploads((prev) => [...prev, upload]);
```

**Comment by cojoclaudiu** [comment]
> 

Yes, but if I begin with upload.start() and I have my component with two buttons upload.pause() and upload.start() than I can't pause() and start() again, it will still upload util the end.

**Comment by Acconut** [comment]
> Later edit: hmm... now it seems like working

Great! Does this mean this issue is solved for you now?

**Comment by cojoclaudiu** [comment]
Yes, the issue is solved. Everything works as expected. But I think we can add more documentation or a tutorial for React with Vimeo integration.

**Comment by Acconut** [comment]
> But I think we can add more documentation

Of course. Which information do you think is currently missing in our documentation? Or what details would have helped you?
