### ISSUE TITLE
Rename `fingerprint.js` so ad blockers don't block the file

### ISSUE THREAD

**Issue by Murderlon** [tus/tus-js-client#429]
**Describe the bug**
Ad blockers, such as uBlock, block the file `fingerprint.js` sometimes which promptly crashes the client.

**To Reproduce**
Unfortunately, it doesn't happen always on Codesandbox but I got it often.

1. Install [uBlock origin](https://ublockorigin.com/) and [Privacy Badger](https://privacybadger.org/)
2. Open https://codesandbox.io/s/uppy-drag-drop-gyewzx?file=/src/index.js
3. Check console, it blocks the file (sometimes)

**Expected behavior**
tus-js-client doesn't use a filename that is on some block list for scripts

**Comment by Acconut** [comment]
Ok, I can reproduce this with uBlock. I get following errors:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.jsdelivr.net/npm/tus-js-client@2.3.2/lib.esm/browser/fingerprint.js. (Reason: CORS request did not succeed). Status code: (null).

> ModuleNotFoundError: Could not find module in path: 'tus-js-client/lib.esm/browser/fingerprint' relative to '/node_modules/tus-js-client/lib.esm/browser/index.js'

This problem should not occur if your application is bundled in a single files. But here the files are loaded individually, so the ad blockers get hung up on the name.

We can simply change the file name from `fingerprint.js` to `fileSignature.js`. That name would also be more descriptive.
