### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by arturi** [tus/tus-js-client#43]
Happens in the new version `tus-js-client@1.2.0`:

``` javascript
source.js:209

if (input instanceof _fs.ReadStream && input.path != null) {
  return new FileSource(input);
}
```

To reproduce just create a tus upload from the example using latest version `1.2.0`. In my case input is: `input = Blob {size: 122, type: "image/svg+xml"}, chunkSize = Infinity`.

Live example: http://requirebin.com/?gist=93bfd8529d983aaac9cafb638af93a88

**Comment by Acconut** [comment]
Thank you for reporting and also including this test case which made debugging it a really quick journey. v1.2.1 which includes the fix should be available on NPM now.

**Comment by Acconut** [comment]
FYI, if you want to test it out on RequireBin, be sure to change the version in the `package.json` tab!

**Comment by arturi** [comment]
Thanks!

**Comment by payner35** [comment]
I am having this problem as well. 

[https://github.com/transloadit/uppy/issues/223#issuecomment-309504171](url)

**Comment by Acconut** [comment]
@payner35 If I follow the discussion correctly, this is an issue with Meteor which has not been fixed (and they probably will not do so soon)?

**Comment by payner35** [comment]
@Acconut yeah.. i wouldn't be overly confident that change is coming anytime soon.

I did fork tus & uppy.. and trim them back to play nice with Meteor with just the browser.

https://github.com/transloadit/uppy/issues/230

**Comment by kvz** [comment]
Right, seems like it's been 'broken' in Meteor for more than a year now without attempts at a fix: https://github.com/meteor/meteor/issues/6890. Projects bigger than Uppy/tus aren't working in Meteor and that hasn't moved the needle, so it's unlikely that our adding weight to that issue, will I'm afraid :|

**Comment by Acconut** [comment]
>  Projects bigger than Uppy/tus aren't working in Meteor and that hasn't moved the needle, so it's unlikely that our adding weight to that issue, will, I'm afraid :|

That's right. The problem is that I don't see a practicable solution to have we could fix this in tus-js-client. The approach @payner35 chose (forking and modifying to just work in the browser) is not an option for us as tus-js-client must also work using Node.js.
