### ISSUE TITLE
DOC: Add information about script size

### ISSUE THREAD

**Issue by hpvd** [tus/tus-js-client#440]
**Is your feature request related to a problem? Please describe.**
There is no information about the size of the js file to be embedded.
Would be handy to decide if its worth it / determine embedding/loading strategy without having to evaluate it first.

**Describe the solution you'd like**
Provide some information about script size: pure, minified, minified and gzipped
A good place would be readme and or FAQ

**Comment by Acconut** [comment]
Thanks, done!
