### ISSUE TITLE
How dependent is this on window (browser) or fs (node)?

### ISSUE THREAD

**Issue by sdhull** [tus/tus-js-client#442]
**Context**
I'm interested in writing load tests using [k6](https://k6.io), however while you can write the tests in javascript, tests [do not run in a browser or in node](https://k6.io/docs/#what-k6-does-not), so there is no `window` object and no `fs` import available. But if I had to guess, I suspect the runtime is more like node than it is like the browser.

**Question**
I'd like to avoid re-implementing the tus protocol from scratch, so I guess my question is: can you offer me any guidance here (before I fork this project and start trying stuff willy-nilly)?

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: [goja](https://github.com/dop251/goja)
- Used tus-js-client version: 3.0.0
- Used tus server software: custom tusd

**Discussion**
I'm pondering either defining `window` using Webpacker [define plugin])(https://webpack.js.org/plugins/define-plugin/) and targeting `web` or alternatively forking the project, removing `fs` imports in node and relying on config hooks (eg for computing the fingerprint etc). I'm worried this would necessitate new / other config hooks related to getting file info.

Either way I anticipate that I'll have to leverage the `httpStack` config option and create a new HTTP stack using `k6/http`

**Comment by Acconut** [comment]
Are you trying to use tus-js-client to write a load testing tool for tus server? That sounds very interesting!

The core logic (https://github.com/tus/tus-js-client/blob/master/lib/upload.js) does not (or should not) depend on browser- or Node-specifics at all. The different components for browsers and Node.js are included using the dependency injection pattern in https://github.com/tus/tus-js-client/blob/master/lib/browser/index.js and https://github.com/tus/tus-js-client/blob/master/lib/node/index.js. If even importing these entry points does not work, maybe you can use the BaseUpload class (https://github.com/tus/tus-js-client/blob/master/lib/upload.js) directly.

So, if you target `web` and supply your own `httpStack` and maybe `fileReader` or `urlStorage`, it might work. But you will have to try that in your own :)

**Comment by sdhull** [comment]
> Are you trying to use tus-js-client to write a load testing tool for tus server?

Yes, that is the goal 😬 thanks for the guidance, I'll close this out 😄

**Comment by Acconut** [comment]
A tus load testing tool sounds amazing and I would be interested in using and helping with it as well. Is your work in that public by chance?

**Comment by sdhull** [comment]
I'll check legal at my company to see if we can make the repo public. I can't imagine they'd object. I haven't made much progress yet tho 🥲

**Comment by Acconut** [comment]
Sounds great! Maybe we could also collaborate together on this. Let me know if you are interested :)

**Comment by sdhull** [comment]
Update for you @Acconut: legal at my company is _not happy_ with the GPLv3 license of k6. I have a basic script working using `tus-java-client` with Jmeter (🤢), which I don't think I can share but it's pretty vanilla.

I'll try to get k6 working in my free time and if I make _any_ progress I'll share the repo with you here (it'll just be a repo in my personal github to appease legal at my company)

**Comment by Acconut** [comment]
Ok, thank you very much the update! It's unfortunately that the legal department does not allow it. I will also open a new issue here to track the idea of a load-testing tool using tus-js-client. Maybe in the future we will be able to work on this.
