### ISSUE TITLE
Initial authentication using  headers, then removal of headers after setting a response Location header?

### ISSUE THREAD

**Issue by scouttyg** [tus/tus-js-client#452]
We have a backend middleware server that requires authentication from a user, but then sets the `Location` header to another third party link which is the tus endpoint url we want them to hit, and doesn't require authentication. The problem is, we get CORs errors because the headers we set are sent with every request, not just the initial one.

To explain a bit further our use-case, in our initial call using tus, we do something like:

```javascript
options = {
  endpoint:  "https://our_secure_server.com/endpoint_requiring_authentication",
  // Lots of other options
  headers: {
    "Authorization":  `Bearer ${token_for_our_secure_server}` // This is required to authenticate to our secure server
  }
}

const upload = new tus.Upload(file, options);
```

But after they call our authenticated endpoint, we return a response from our authenticated endpoint that looks roughly like this:

```javascript
return new Response(null, {
  headers: {
    'Access-Control-Expose-Headers': 'Location',
    'Access-Control-Allow-Headers': '*',
    'Access-Control-Allow-Origin': '*',
    'Location': "https://third_party_website_not_needing_authentication.com/tokenized_url_generated_on_the_fly/real_tus_endpoint_here",
  },
})
````

The problem is, the bearer token headers are then sent to the third party website as well, which we don't want, and which is causing the CORs errors in question. Any way to prevent this through the tus-js-client options?

**Comment by scouttyg** [comment]
Hmm, I think the best way I found was do basically do:


```javascript
options = {
  endpoint:  "https://our_secure_server.com/endpoint_requiring_authentication",
  // Lots of other options
  onBeforeRequest: function (req) {
    if (!req._url.includes("third_party_website_not_needing_authentication.com/tokenized_url_generated_on_the_fly/real_tus_endpoint_here")) {
      const xhr = req.getUnderlyingObject()
      xhr.setRequestHeader('Authorization', `Bearer ${token}`)
    }
  }
}
```

Basically, if the request is not being made to the unauthenticated endpoint, then set the authorization headers.

Initially, I wanted to do the reverse (e.g. if `third_party_website_not_needing_authentication`, then unset header), but since `setRequestHeader` only appends, and can't "delete" a header, this was the best option I had.

Let me know if this was the ideal way though.

**Comment by Acconut** [comment]
Yes, you basically arrived at the correct solution! Use `headers` option for headers that should always be present and `onBeforeRequest` if you only want them in some requests.

> We have a backend middleware server that requires authentication from a user, but then sets the `Location` header to another third party link which is the tus endpoint url

Another solution would be that you send the request to your backend middleware on your own (without tus-js-client). And then set the Location header to be the `endpoint` for tus-js-client. But maybe that is not preferable for your for some reason.
