### ISSUE TITLE
Compatibility issue with tus-node-server v0.2.1

### ISSUE THREAD

**Issue by jwtlake** [tus/tus-js-client#47]
Did they make some breaking changes with tus-node-server v0.2.1? https://github.com/tus/tus-node-server/releases 

After upgrading from v0.2.0 -> v0.2.1 I'm getting an upload error. 
```tus: failed to upload chunk at offset 0, originated from request (response code: 0, response text: )```
The tus server ends up writing a blank file.

I'm using tus-js-client v1.1.3 on nodejs. After rolling back a version on the tus server things started working again. 

Full Error
```
{ [Error: tus: failed to upload chunk at offset 0, originated from request (response code: 0, response text: )]
  originalRequest: 
   Request {
     _method: 'PATCH',
     _url: '//127.0.0.1:8000/files/53b3de299f8afa2c9a05bdbcd6835e1b',
     _headers: 
      { 'Tus-Resumable': '1.0.0',
        'Upload-Offset': 0,
        'Content-Type': 'application/offset+octet-stream',
        'Content-Length': 24380660 },
     _resHeaders: {},
     _request: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: false,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'PATCH //127.0.0.1:8000/files/53b3de299f8afa2c9a05bdbcd6835e1b HTTP/1.1\r\nTus-Resumable: 1.0.0\r\nUpload-Offset: 0\r\nContent-Type: application/offset+octet-stream\r\nContent-Length: 24380660\r\nHost: localhost\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        method: 'PATCH',
        path: '//127.0.0.1:8000/files/53b3de299f8afa2c9a05bdbcd6835e1b',
        _ended: false,
        parser: null },
     status: 0,
     onerror: [Function],
     onload: [Function],
     upload: { onprogress: [Function] },
     withCredentials: false,
     responseText: '' },
  causingError: null }
```

**Comment by bhstahl** [comment]
Hey @jwtlake, it looks like it may be related to https://github.com/tus/tus-node-server/pull/49. My guess is the request to `//127.0.0.1:8000/files/53b3de299f8afa2c9a05bdbcd6835e1b` is failing because of the missing protocol

**Comment by jwtlake** [comment]
Ahh ya makes sense. 
https://github.com/tus/tus-node-server/commit/d56bd5ab81db5720b4b6713cd8dca8b9a9148a4b

**Comment by caryfitzhugh** [comment]
+1  for fixing this - new guy to tus, and this confuse the heck out of me.   :) I'll stick with 0.2.0 for now

**Comment by Acconut** [comment]
Currently, tus-js-client expects the URL to be absolute, including protocol and hostname. I am looking into ways to also allow relative addresses.

**Comment by caryfitzhugh** [comment]
cool! thanks!

**Comment by Acconut** [comment]
The latest commit should have fixed this issue. I tested in in the browser as well as in a Node environment against tus-node-server v0.2.1. The patch will be in the new minor release which should happen in the next week.

**Comment by jwtlake** [comment]
Cool looks like this worked! Just retested with tus-node-server v0.2.1 and tus-js-client v1.4.0. 

Thanks!
