### ISSUE TITLE
Cloudfront Content creator TUS - Fails after 100%

### ISSUE THREAD

**Issue by RafaelEchart** [tus/tus-js-client#472]
**Describe the bug**
After the uploading starts, reaches 100% but then a petition (PATCH) to my one time link URL fails

# Explanation

Hi! I am trying to upload a video using the TUS methodology (js-tus-client) everything seems to be working well. I will post my code below to see if you can help me, please!

<img width="525" alt="first" src="https://user-images.githubusercontent.com/53021807/191140746-bc3b807e-5dbb-4ceb-8eec-ff4b7ac7771c.png">

In the Upload-Metadata I set maxdurationseconds NjAw, this means a maxDurationSeconds of 10 min (I am sending a 25 secs video)

That's my node.js backend API. 

Now on the frontend side, I am using the js-tus-client as follows. 

**import:**

<img width="179" alt="import" src="https://user-images.githubusercontent.com/53021807/191140764-f5990f3a-c143-49b7-9ffc-b310e57fadd8.png">

**Function:**

<img width="386" alt="second" src="https://user-images.githubusercontent.com/53021807/191140777-01edaea1-a781-4692-9fdb-4cbceeeafbab.png">

The endpoint is pointing to my backend server which returns in the location header the URL. 

Now, this is what happens when I trigger this function.

* The backend route executes without error and the CloudFlare dashboard creates a new empty video which is great according to the docs.

<img width="581" alt="dashboard" src="https://user-images.githubusercontent.com/53021807/191140798-e9fb9f25-16e8-4be6-931f-b39b09735b7a.png">

* In the frontend logs:

**With chunkSize as 50*1024*1024:**

<img width="457" alt="try1" src="https://user-images.githubusercontent.com/53021807/191140813-f00c8645-9d1d-4e8a-b52a-9b2dd60ce752.png">

**With chunkSize as 200*1024*1024:**

<img width="461" alt="try2" src="https://user-images.githubusercontent.com/53021807/191140820-8ab519cd-6e73-4458-8a27-81c2f4cd4432.png">

**With chunkSize not defined: **

<img width="454" alt="try3" src="https://user-images.githubusercontent.com/53021807/191140826-0b0e6c13-ae59-4340-b638-3705195b3cfa.png">

Independent on the chunksize sometimes the percent reaches 100%, but NEVER saves the video. I don't know where that patch petition is coming from. 

Thanks in advance, I appreciate your help!!

**Comment by Acconut** [comment]
This does not look like a bug to me but rather some issue with the integration with Cloudflare. I have never used their API, so I cannot provide help to you. It is probably best to contact Cloudflare's support.

**Comment by RafaelEchart** [comment]
Upload Length should be bytes sent by tus-js-client as header, I set Upload-Length in API as '1' which is incorrect
