### ISSUE TITLE
How to replace an uploaded file?

### ISSUE THREAD

**Issue by piranna** [tus/tus-js-client#487]
**Question**
I'm trying to upload a file that gets updated frequently (maybe more than one time per second), so I want to overwrite the old content with the new one, but instead of that, I always end up with the content stored in a new independent file. I have tryied used the `uploadUrl` option without success. How can I do it with `tus-js-client`?

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: [e.g. Browser, Node.js, React Native] Node.js
- Used tus-js-client version: [can be obtained by running `npm ls`] 3.0.1
- Used tus server software: [e.g. tusd, tus-node-server etc] tus-node-server@0.8.1

**Comment by Acconut** [comment]
tus is not designed to "replace files". Once an upload is completed, it is immutable in the view from the protocol. tus-js-client, tus-node-sever and all other implementation from us therefore do not support changing a completed upload. If you set `uploadUrl` to point to a completed upload, tus-js-client will correctly not do anything because the upload is already completed.

Basically, what you are trying to do is not possible with tus. You should consider just creating new upload resources if you want to upload a changed file.

**Comment by Acconut** [comment]
> On my tests it seems that magically started working, maybe because sending them during few time hasn't yet clossed anyone, I'll need to test more thoroughtly.

To be honest, I do not understand that part. What do you mean?

**Comment by piranna** [comment]
> To be honest, I do not understand that part. What do you mean?

That I get the files updated / overwritten, not sure if I've done something wrong with tus-js-client or tus-node-server, but it's currently working as I expected, although it should not work at all. I don't know if it's expected behaviour, or since I'm sending the uploads very fast but I send very few, all of them are "mid-flight" before the first one fully ends and so the file doesn't get locked, so as a secondary effect I'm being able to overwrite the files just as I wanted to do.

**Comment by Acconut** [comment]
> That I get the files updated / overwritten, not sure if I've done something wrong with tus-js-client or tus-node-server, but it's currently working as I expected, although it should not work at all.

I am including @Murderlon, the developer of tus-node-server, here, as this might be an indicator of something working not properly inside tus-node-server.

@piranna, could you also provide us with some of your code, so we can reason more about how you are "replacing the uploaded files"? Are you just always passing in the same `uploadUrl` every time?

**Comment by piranna** [comment]
Yes, just only using the same uploadUrl. I'll try to send you later some code snippets.

**Comment by Murderlon** [comment]
Hi, this is surprising indeed. This may be a bug in `tus-node-server`. Could you open an issue there with a reproducible example?

I think this issue can be closed.

**Comment by Mihai-github** [comment]
Hello, so providing the same path of the file witch is already stored would not overwrite the file with a new one, right?
From what I see I get a 409 code so seems like the case but would like, if possible, to also get confirmation :)

**Comment by Acconut** [comment]
> Hello, so providing the same path of the file witch is already stored would not overwrite the file with a new one, right?

No, that is not possible. Your tests are correct :)

**Comment by Mihai-github** [comment]
> > Hello, so providing the same path of the file witch is already stored would not overwrite the file with a new one, right?
> 
> No, that is not possible. Your tests are correct :)

Thank you, @Acconut!
