### ISSUE TITLE
Nginx breaks down after ~30MB

### ISSUE THREAD

**Issue by kw005** [tus/tus-js-client#498]
Using tusd with the same config (https://github.com/tus/tusd/blob/master/examples/nginx.conf), I still cannot upload files bigger then approx 30MB (set client_max_body_size 0 or client_max_body_size 200M), but nothing works. When adding chunkSize to 25MB, things work, but the performance and user experience decreases. Does anybody has an idea for solving this issue or discovered the same problem?

**Comment by Acconut** [comment]
Did you solve the problem because you closed the issue on your own?
