### ISSUE TITLE
tus upload fails when upload url returns 404

### ISSUE THREAD

**Issue by KieranP** [tus/tus-js-client#50]
Run into the following issue:

* User uploads a file using browser with localstorage
* Expiration passes and file gets removed on server
* User uploads exact same file with same browser, same fingerprint
* tus js reuses existing url from localstorage and calls `_resumeUpload()`
* tus server responds with 404 (as per spec, because the file no longer exists on server)
* tus js seems to calls `xhr.onerror` in `_resumeUpload()` as 404 == error

Result: Upload will always fail. Instead, what is expected is that it should start upload from scratch. There is code to do this in `xhr.onload` (`if (!(xhr.status >= 200 && xhr.status < 300)`) but a 404 code isn't a success in xhr, it's an error, so the code in `xhr.onload` will never be reached. There needs to be similar code in the `xhr.onerror` section as well.

Workarounds: Clear localcache, but we can't ask users to do this each time they can't upload properly.

Thoughts? Or am I doing something wrong?

**Comment by KieranP** [comment]
For whatever reason, this no longer seems to be happening, and it's now properly creating the file rather than trying to resume a broken one. Very weird. Closing ticket...

**Comment by Acconut** [comment]
> For whatever reason, this no longer seems to be happening, and it's now properly creating the file rather than trying to resume a broken one. Very weird. Closing ticket...

Could it be that you upgraded tus-js-client in the meantime? In the beginning, the module did not create a new upload if the previous one returned a 404. However, we changed this behavior some time ago for exactly the reason you named in your comment. It may be worth looking at the code to understand how it's handled now: https://github.com/tus/tus-js-client/blob/master/lib/upload.js#L309-L320

**Comment by KieranP** [comment]
@Acconut  I was using the latest version on the master branch of this repo at the time I made the ticket.

I tracked it down to the tus-ruby-server returning a 404 for the OPTIONS call the browser makes before the HEAD request. Returning 404 at that stage causes the browser to reject with code 500 the HEAD request on a file url for security reasons, and tus-js then picks up that 500 and aborts.

I've reached out to the maintainer of the tus-ruby-server here: https://github.com/janko-m/tus-ruby-server/issues/2

What I haven't done yet is check whether the spec says a tus server should return 404 or not on options calls where the file is missing, cause if the spec specifies this, then obviously it's going to fail  :-(

**Comment by Acconut** [comment]
> I tracked it down to the tus-ruby-server returning a 404 for the OPTIONS call the browser makes before the HEAD request. Returning 404 at that stage causes the browser to reject with code 500 the HEAD request on a file url for security reasons, and tus-js then picks up that 500 and aborts.

You should be able to circumvent this issue by using the `retryDelays` setting (https://github.com/tus/tus-js-client#tusdefaultoptions). When enabled it will not error out when a server returns the 500 status code but instead will start a new upload.

> What I haven't done yet is check whether the spec says a tus server should return 404 or not on options calls where the file is missing, cause if the spec specifies this, then obviously it's going to fail :-(

The specification does not mention this case but I will investigate whether we should add a sentence about it.

**Comment by KieranP** [comment]
@Acconut I made the change I suggested (options always returning 404), and now the whole system is working perfectly. I would highly recommend adding something to that effect in the spec so other implementations don't run into the same issue.

**Comment by Acconut** [comment]
Closing in favor of https://github.com/tus/tus-resumable-upload-protocol/issues/102.
