### ISSUE TITLE
409 - conflict

### ISSUE THREAD

**Issue by brunolau** [tus/tus-js-client#507]
I'm trying to upload a video to the server of our CDN. When my connection drops during the upload, and try to resume the download, I receive:

Error: tus: unexpected response while uploading chunk, originated from request (method: PATCH, url: https://video.bunnycdn.com/tusupload/6889ce332f124606afc7c9d36a394082, response code: 409, response text: File 6889ce332f124606afc7c9d36a394082 is currently being updated. Please try again later, request id: n/a)

Any way I can battle this ?

**Comment by Acconut** [comment]
Apologies for the late reply. What tus server are you using? Please answer all questions as provided in the issue template.

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)
