### ISSUE TITLE
About `_onUploadUrlAvailable`

### ISSUE THREAD

**Issue by cjauvin** [tus/tus-js-client#524]
**Question**

I have a use case where I need to know `upload.url` as soon as possible.. I tried and it seems I can use the `_onUploadUrlAvailable` option callback to retrieve it, but then as it's not part of the `UploadOptions` interface, it seems dangerous for me to use it. Is there any reason why this callback is not part of the option interface?

**Comment by Acconut** [comment]
There is no specific reason for keeping it private. The new for this callback arose from internal demand, so we made it non-public by default. But I think there is nothing speaking against making it public now. Feel free to open a PR for this :)

**Comment by Acconut** [comment]
Fixed in #543
