### ISSUE TITLE
Incorrect usage of the tus protocol?

### ISSUE THREAD

**Issue by tvt-samuli** [tus/tus-js-client#532]
**Question**

Hi, I have been trying to setup a project for transferring user uploaded files to local filesystem. The users of this service would be uploading files ranging from megabytes to tens of gigabytes in size. 

The goal was to use the `chunkSize` parameter to chunk the user upload into smaller chunks, mainly to help users in case of failed upload (for example. network issues) so that they would not have to start the upload of really large files from scratch, but to continue from chunk they were left on.

On first sight it seemed like this worked, and the files ended up on our server correctly with file size matching what was uploaded, but after some investigation I found out that all files that had to be chunked (they exceeded the `chunkSize`) would end up corrupted on our destination server. I was unable to open the files after they were on the destination server, and their mediainfo was gone.

I'm wondering if I have understood the functionality of the tus protocol incorrectly, or if i'm using it incorrectly? I assumed the resumability of this protocol meant that users would be able to resume the upload if something went wrong without having to start the upload from the beginning, but it seems that if we left the `chunkSize` to default (Infinity) users would have to resume the upload from beginning in case of failed upload.

**Setup details**
- Runtime environment: Node.js
- Used tus-js-client version: @uppy/tus@3.0.5
- Used tus server software: [django-tus](https://github.com/alican/django-tus)

**Comment by tvt-samuli** [comment]
Did some further investigation, and it seems like the issues is indeed on server side tus. 

The current version of django-tus is outdated, and is missing some fixes present in the projects repository. The issue seems to have been fixed in this PR https://github.com/alican/django-tus/issues/18 but the updated code is not present in the package downloadeble via PiP.

**Comment by Acconut** [comment]
I am glad to read that you found a solution quickly, but I just wanted to explain it a bit more. So other people having a similar issue can be helped as well.

> The goal was to use the `chunkSize` parameter to chunk the user upload into smaller chunks, mainly to help users in case of failed upload (for example. network issues) so that they would not have to start the upload of really large files from scratch, but to continue from chunk they were left on.

That is not how tus is intended to be used. You do not have to split an upload into multiple requests using the chunkSize option (it is also necessary if a few edge cases, see https://github.com/tus/tus-js-client/blob/main/docs/api.md#chunksize). After a failure, tus will automatically fetch the current upload progress and resume from there.

**Comment by Acconut** [comment]
> What we observed with the https://github.com/alican/django-tus as our back end TUS implementation was that the upload was resumable only at `chunkSize` intervals, meaning it would resume at the last completed chunk.
> 
> For example if `chunkSize` was set at 500 MB and the upload failed at any point before 500 MB, it would always resume from the beginning. Only after it exceeded the 500 MB mark, it would then restart at 500 MB if it failed again.

This sounds like the backend is not processing the data contained in requests when the request is cancelled or the connection drops. Check your proxy's configuration to make sure, it doesn't buffer request bodies and streams them to the tus servers or otherwise django-tus does not have a chance to save any data because it doesn't receive any. If that doesn't help, it might be a bug in django-tus where they only process complete requests, but I haven't looked deeper into django-tus.

If none of the above helps, then, yes, set `chunkSize` to a finite value to force the upload being split into multiple requests.
