### ISSUE TITLE
How do I override the fetch call in the tus js client?

### ISSUE THREAD

**Issue by lunaticcoding** [tus/tus-js-client#533]
**Question**
How do I override the fetch call in the tus js client? For a Shopify embedded app I need to use the useAuthenticatedFetch method to get the correct http headers. But I want to upload a large video so simply using useAuthenticatedFetch would not work. 

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: React, Shopify CLI for embedded Apps, Node.js + Express Backend
- Used tus-js-client version: 3.0.1
- Used tus server software: ^1.0.0-beta.2

**Comment by Acconut** [comment]
Have a look at this option: https://github.com/tus/tus-js-client/blob/master/docs/api.md#httpstack
