### ISSUE TITLE
DetailedError type definitions are missing possible `null`s

### ISSUE THREAD

**Issue by nh2** [tus/tus-js-client#550]
The types say all fields in `DetailedError` are guaranteed to be peresent:

https://github.com/tus/tus-js-client/blob/4ff243c33a21a006a5d8c9a082268027f32f76ef/lib/index.d.ts#L123-L127

But they are `null` sometimes. This caused a runtime crash in my app.

I think this would be a great idea, as humans just aren't good at tracking what can be null and what cannot:

* https://github.com/tus/tus-js-client/issues/296

## Cause

https://github.com/tus/tus-js-client/blob/4ff243c33a21a006a5d8c9a082268027f32f76ef/lib/error.js#L1-L2

* `causingError` can be `null`:
  https://github.com/tus/tus-js-client/blob/4ff243c33a21a006a5d8c9a082268027f32f76ef/lib/upload.js#L124
* `originalResponse` can be `null`:
  https://github.com/tus/tus-js-client/blob/4ff243c33a21a006a5d8c9a082268027f32f76ef/lib/upload.js#L126-L128

**Comment by Acconut** [comment]
You are correct, thank you for reporting! Would you be able to submit a PR to fix the current type definitions? Getting the automatically generated is a nice improvement but will probably take some time to achieve.
