### ISSUE TITLE
[Question]: Include credentials only for first call

### ISSUE THREAD

**Issue by hitech95** [tus/tus-js-client#564]
**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: Browser (React, webpack)
- Used tus-js-client version: "^1.8.0"
- Used tus server software: none

**Question**
Hi,
My backend needs credentials to generate the uload URL to our CDN.
The credentials are required to validate the user session.

The backend generates a signed URL and credentials are not needed for the "redirected" call.

Code (ExpressJs) snippets of our code:
```js
// Process user data and generate url
if(!auth.check()){
  res.status(403);
  return;
}
const uploadURL = await generateUploadURL(context);
res.status(200);
res.set({
  "Access-Control-Expose-Headers": "Location",
  "Access-Control-Allow-Headers": "*",
  Location: uploadURL,
});
```

This part work fine on our side, but when the JS client try to contact the new server it throws an error.
The CDN dont allow credentials and everything stop.

I know that the tus-js version is quite old an I'm planning to update it while solving this issue.

**Comment by hitech95** [comment]
My solution is:
Where endpoint is the initial backend endpoint that I pass to tus

I'm not 100% sure this is the perfect way to handle this but is a start.
```js
onBeforeRequest: function (req) {
  const xhr = req.getUnderlyingObject();
  if (req.getURL() === endpoint) {
    xhr.withCredentials = true;
  }
}
```

**Comment by Acconut** [comment]
> I'm not 100% sure this is the perfect way to handle this but is a start.

Yes, this is the correct approach using the `onBeforeRequest` callback. Alternatively, you can also check if the request's method is `POST`.

**Comment by vitorguima** [comment]
If anybody comes here in the future with the same problem, you can do something like that to dynamically add an authorization header:

```
      onBeforeRequest: function (req) {
        const xhr = req.getUnderlyingObject()
        if (req.getURL()?.includes('endpoint you need to request with some authorization token')) { 
          xhr.setRequestHeader('Authorization', `Token`)
        }
      },
```

very simple approach but took me a while to figure it out lol (I was about to try creating a node server just to proxy this flow)
