### ISSUE TITLE
retryDelays as a function

### ISSUE THREAD

**Issue by oliverpool** [tus/tus-js-client#57]
I have a suggestion to make [`retryDelays`](https://github.com/tus/tus-js-client/blob/30572d850cfabf67350fe122b9b734727f67604f/lib/upload.js#L106-L154) a bit more flexible by allowing it to be a function.

If the function `retryDelay(this._retryAttempt)` returns a value greater than 0, then it is used a delay, otherwise it is aborted (value -1 returned for instance).

This allows for unlimited number of retry (and eventually to log the failed attempts for telemetry).

**Comment by Acconut** [comment]
I prefer a more explicit approach for retrying an unknown number of times, similar as used in the demo (https://github.com/tus/tus-js-client/blob/master/demo/demo.js#L52-L58). Primarily, this enables you to determine whether you want to retry in an asynchronous fashion, e.g. by asking the user for input or communicating with your remote server. And I would rather have a single approach for this.

**Comment by oliverpool** [comment]
Fair enough
