### ISSUE TITLE
tus client always sending request to http instead of https 

### ISSUE THREAD

**Issue by appunnicer13** [tus/tus-js-client#58]
I am getting mixed content error in the browser console on trying to upload the file . My server is running on nginx reverse proxy , tusd running at port 1080 . I am using proxy_pass , but still i am not able to upload , on upload from localhost i am getting preflight status error which is due to redirect from http site to https. These are my client options 
 endpoint: "https://site.com/files/",
  retryDelays: [0, 1000, 3000, 5000],

**Comment by appunnicer13** [comment]
I tried running a test from my https server also , where i get mixed content error . Some one please help me solve this issue .

**Comment by appunnicer13** [comment]
I did the same but no change

**Comment by appunnicer13** [comment]
I use supervisor , so i added -behind-proxy like this 
/home/appu/work/src/github.com/tus/tusd/cmd/tusd/main -behind-proxy

**Comment by appunnicer13** [comment]
further update
started getting this error , i am running this on a sub domain video.site.com 
OPTIONS https://video/files/b92a831ced3202614a454606cb7cea93 net::ERR_NAME_NOT_RESOLVED

and i have clearly given full domain name in the endpoint option , but this error comes

**Comment by Acconut** [comment]
> I use supervisor , so i added -behind-proxy like this
> command=/home/appu/work/src/github.com/tus/tusd/cmd/tusd/main -behind-proxy

Are you sure that this may not need some quotes around, so the `-behind-proxy` arguments is passed to the binary? I haven't used supervisior before, so I can't tell you.

> OPTIONS https://video/files/b92a831ced3202614a454606cb7cea93 net::ERR_NAME_NOT_RESOLVED

This error may occur when a previously misconfigured upload is tried to be resumed. Please clear your Web Storage for the domain where tus-js-client is running. You can find instructions about this here: http://superuser.com/a/655198

The error also may lay in your Nginx configuration. It would be helpful if you could provide the parts relevant to where you setup the reverse proxy to connect to tusd.

**Comment by appunnicer13** [comment]
Sorry for late reply , I resolved this issue , i was setting the domain name as video instead of full subdomain name in the nginx .

**Comment by Acconut** [comment]
I am glad to read that you were able to resolve your issue :)

**Comment by LeiYangGH** [comment]
> 

the link has changed to https://github.com/tus/tusd/blob/master/examples/nginx.conf

**Comment by Acconut** [comment]
> the link has changed to

Thanks, I updated my comment!

**Comment by manuucsit** [comment]
Hi i am getting same error
can you help me to get rid out of it
i am getting
```
httpStack.js:96 Mixed Content: The page at 'https://test.edeekshaam.in/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.edeekshaam.in/files/8559af01c86cfb933641e0248f305200'. This request has been blocked; the content must be served over HTTPS.
```
my nginx config
```
  location / {
        proxy_pass http://localhost:4000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Scheme https;

   }
```

my frontend config
```
  uppy.use(Tus, {
    endpoint: 'https://api.edeekshaam.in/files', // Replace with your Tus server endpoint
    // endpoint : 'http://localhost:4000/files',
    resume: true,
    retryDelays: [0, 1000, 3000, 5000],
    headers: {'Access-Control-Allow-Origin': '*'}
  })
```

and my backend config

```
const tusServer = new Server({
  path: '/',
  datastore: new FileStore({ directory: './files' })
})


router.all('/*', (req, res) => {
    tusServer.handle(req, res);
});
 ```

**Comment by Acconut** [comment]
I think you need to enable the `respectForwardedHeaders` option in tus-node-server: https://github.com/tus/tus-node-server/tree/main/packages/server#optionsrespectforwardedheaders. Please correct me if I am wrong, @Murderlon.

**Comment by andreineamtu** [comment]
> I think you need to enable the `respectForwardedHeaders` option in tus-node-server: https://github.com/tus/tus-node-server/tree/main/packages/server#optionsrespectforwardedheaders. Please correct me if I am wrong, @Murderlon.

is it enough, or changing the nginx configuration is a must?

**Comment by Murderlon** [comment]
If you tus server is on the same domain as your client, you can also use `relativeLocation`. Otherwise see the nginx example in the tus server docs.

**Comment by tbm5k** [comment]
One can also bruce force this by [generating the url](https://github.com/tus/tus-node-server/tree/main/packages/server#optionsgenerateurl)
Had an issue with my protocol and host forwarding but using this method, i got it done
