### ISSUE TITLE
is it possible to do some authorization before send data to endpoint?

### ISSUE THREAD

**Issue by kevin-openc** [tus/tus-js-client#60]
is it possible to do some authorization before send data to endpoint?
say i have custom function http://localhost/upload, and i put it as endpoint
and this page will do authorization and if authorized, pass all data to the real endpoint http://localhost/files/ and upload file as usual.
if not authorized, may fall into onerror function.

i have tried to make the same header and do redirect in http://localhost/upload but not works.

**Comment by Acconut** [comment]
Does my comment in https://github.com/tus/tusd/issues/88 answer your questions here, too?

**Comment by kevin-openc** [comment]
the hook event can helps to add customize action before file upload!

thanks!!

**Comment by Acconut** [comment]
That's great to hear :+1:
