### ISSUE TITLE
Base64.isSupported issue

### ISSUE THREAD

**Issue by olucurious** [tus/tus-js-client#61]
Why is Base64.isSupported always set to true here: https://github.com/tus/tus-js-client/blob/master/lib/node/base64.js#L7, to my little understanding, that means a function like encodeMetadata() https://github.com/tus/tus-js-client/blob/master/lib/upload.js#L452 will always return "" which eventually means something like a custom filename won't be passed in the request header, or am I getting something wrong here? I'm actually trying to implement custom file naming

**Comment by kvz** [comment]
Was this closed intentionally?

**Comment by Acconut** [comment]
> Why is Base64.isSupported always set to true

This is not true. The file you linked will only be used when the library is used in a node process. For the browser environment a different definition is relevant: https://github.com/tus/tus-js-client/blob/master/lib/browser/base64.js#L9

>  a function like encodeMetadata() will always return "" 

Could it be that you missed the negation in the if-statement you linked? The enocdeMetadata function will return an empty string if base64 encoding is *not* supported.

```js
if (!Base64.isSupported) {
     return "";
}
```

Do these clarifications help with your situation?

**Comment by olucurious** [comment]
I figure out what I wanted to achieve eventually, the documentation just wasn't straightforward enough. Thanks for the clarifications though.

**Comment by Acconut** [comment]
It's nice to hear that you figured it out. Would you be so kind and explain what you didn't find in the documentation so we can improve it?
