### ISSUE TITLE
Upload file to GCS with presigned URL

### ISSUE THREAD

**Issue by aqib008** [tus/tus-js-client#616]
**Question**
Hi, i want to upload file using resumable presigned url from client to GCS. I want to know if it's possible using this library.
If so can someone provide a details or example.

**Comment by Acconut** [comment]
tus-js-client does not directly upload to GCS. tus uploads always have to go through a tus server, which can then store it on cloud providers. For example, https://github.com/tus/tusd is able to upload to GCS.
