### ISSUE TITLE
i try testing from ios error like can help me

### ISSUE THREAD

**Issue by peterkuch** [tus/tus-js-client#619]
![Screenshot 2023-09-03 at 10 27 44 PM](https://github.com/tus/tus-js-client/assets/14107698/31e0c503-5e2e-484d-bf4a-441d1435aa84)

**Comment by Acconut** [comment]
Please provide all the details that were asked in the issue template: https://github.com/tus/tus-js-client/blob/main/.github/ISSUE_TEMPLATE/question.md. Without this information we cannot help you.

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)
