### ISSUE TITLE
Support Resumability for nodejs environment

### ISSUE THREAD

**Issue by ifedapoolarewaju** [tus/tus-js-client#62]
A number of use cases where this feature is desired seem to have come up ([uppy](https://github.com/transloadit/uppy) and [uppy-server](https://github.com/transloadit/uppy-server) being an example).  So maybe this is a great time to have this feature implemented? cc @Acconut @kvz

**Comment by Acconut** [comment]
There's what I propose:

We add a `urlStorage` property to the options which must be null or an instance with following layout:

```js
class UrlStorage {
  setItem(fingerprint, url, callback)
  getItem(fingerprint, callback)
  deleteItem(fingerprint, callback)
}
```

Notice how the API designed with callbacks to allow an asynchronous usage (which is required for Redis etc). However, we should also consider using Promises as this is probably going to be the standard in new browser APIs.

Furthermore, if the `urlStorage` options is null (it's default value) and we are in the Node environment, no resumability should be enabled. However, if we are in a browser, it should be set to an UrlStorage instance which wraps the localStorage API. This ensure backwards-compatibility.

What do you think?

**Comment by kvz** [comment]
I like this proposal, I do think it's nice that on the server, it would be cool if you could enable reusability with just configuration, so that not everybody has to write the same adapter for local file storage. I'm thinking something like this on the server:

```js
const fsAdapter = require('tus-js-client/storage-adapters/fs')
const opts = {
   urlStorage: {
     adapter: fsAdapter,
     conf: {
        dir: '/tmp/tus-resumability'
     }
   } 
}
``` 

In the browser, if we detect the default `null` as `urlStorage`, we substitute with this internally under the hood, much like you said, Marius:

```js
if (opts.urlStorage === null && env === 'web') {
  const webAdapter = require('./storage-adapters/browserLocalStorage')
  opts.urlStorage = {
     adapter: webAdapter,
  }
}
```

**Comment by Acconut** [comment]
> so that not everybody has to write the same adapter for local file storage

Sure, that's what I also thought. We should provide a basic file-based url storage.

Regarding your code snippet I would prefer if the option interface looked more like:

```js
// my-server-app.js
const FileUrlStorage = require('tus-js-client/storages/file')
const opts = {
   urlStorage: new FileUrlStorage({
      dir: '/tmp/tus-resumability'
   })
}

For me it's easier to see what's going on if you pass an object instead of a constructor and the corresponding arguments for the constructor.

**Comment by kvz** [comment]
💯% agreed!

**Comment by ifedapoolarewaju** [comment]
👌

**Comment by ifedapoolarewaju** [comment]
So I started to work on this over the weekend.

**Comment by Acconut** [comment]
> I can't figure out if "resumability" has been added to nodes or not?
> The demo doesn't seem to work though and uploads always restart at 0%.

tus-js-client can automatically resume from network interruptions or other connection problems but it is currently not able to resume an upload after the process has stopped on its own. You can achieve it manually by saving the `upload.url` and pass it to a new `tus.Upload` as the `uploadUrl` option.

**Comment by ifedapoolarewaju** [comment]
@Acconut I can close this issue right?

**Comment by Acconut** [comment]
Yes, I think this is resolved. Thanks for reminding, Ife!
