### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by RobinKamps** [tus/tus-js-client#629]
tus-js-client is using https://github.com/MatthewMueller/combine-errors as a dependency - wich is using https://github.com/Gi60s/custom-error-instance as a dependency. While combine-errors is published under a MIT License - custom-error-instance has no license information. Can you get rid of this dependency - or perhaps contact the author of custom-error-instance, so that he publishes his work under the MIT License as well?
Kind regards

**Comment by Acconut** [comment]
The package.json contains some information (https://github.com/Gi60s/custom-error-instance/blob/master/package.json#L18), but I opened an issue as well: https://github.com/Gi60s/custom-error-instance/issues/3

**Comment by Acconut** [comment]
The author was kindly enough to quickly add the MIT license, so we can close this.
