### ISSUE TITLE
Ability to retrieve File id before Tus does PATCH requests

### ISSUE THREAD

**Issue by levint** [tus/tus-js-client#63]
I have a use case where I need to know the __file id__ (the last part in the `Location` header returned upon successful execution of creation extension [spec](http://tus.io/protocols/resumable-upload.html#post)) before the tus client performs the actual uploading so that I could link it to a app-specific entity (E.g. a certain entity has many files, associated by file id).

Is there an ___official/recommended___ way to do this?

What I currently am thinking is:

1) extending the `_createUpload()` method inside `lib/upload.js` to emit a file name resolved event once the url has been resolved (response from the POST request)

2) Include the file name in the metadata and have the tus server use it instead of generating one.

**Comment by Acconut** [comment]
> Is there an official/recommended way to do this?

I am sorry, but there isn't one at the moment (excluding some hacky ways which involve overriding internal methods in the TusUpload class).

> Include the file name in the metadata and have the tus server use it instead of generating one.

This sounds to me like it would be the better approach. Let the server link the upload to your app-specific entity when the upload is created. Depending on your server implementation, this may be possible. For example, tusd exposes a hook system which allows you to execute custom routines when e.g. a new upload is created (see https://github.com/tus/tusd/blob/master/docs/hooks.md#pre-create for more details)

**Comment by Acconut** [comment]
Closing this issue due as I feel that the question has been answered. Feel free to leave a comment if you want to continue the discussion :)
