### ISSUE TITLE
tus-upload large file not working in Ubuntu nginx server

### ISSUE THREAD

**Issue by salahrzzaz** [tus/tus-js-client#630]
We are developing the platform to allow users to upload large videos with .net core & puppy (tus)
everything is working fine on the local machines when we are deploying to Ubuntu with the nginx web server the upload works fine with small files (100 m) but when trying to upload a large video (800m), the upload is not completed I attached the behavior on Microsoft edge, chrome, and Firefox.

**Firefox (upload not started) :**  https://github.com/tus/tus-js-client/assets/45657738/9a56e08b-066a-4ac0-b4d8-34513089a3f0

**Chroom & Edge same behavior the upload stopped at 20% :** 

- https://github.com/tus/tus-js-client/assets/45657738/189ce220-523d-47aa-80a4-9b0d41ed44ce
- https://github.com/tus/tus-js-client/assets/45657738/e63b33fc-589b-46d8-a851-f1e1268fb0ca

some info about the infrastructure :

we are using Cloud Flare nameserver with proxy as attached screenshot and use a flexible Cloudflare SSL certificate also in the screenshots

**Cloud flare Screenshot 1:** https://github.com/tus/tus-js-client/assets/45657738/1e43de4c-ff72-4891-8c73-77028fa3a048
**Cloud flare Screenshot 2:** https://github.com/tus/tus-js-client/assets/45657738/e67fefe0-8da8-4d7d-ae3d-7de39ab92d92

the server is google cloud Ubuntu VM instance with nginx webserver

**nginx.conf:**

1. client_max_body_size 0;
2. proxy_connect_timeout       3000;
3. proxy_send_timeout      3000;
4. proxy_read_timeout      3000;
5. proxy_buffer_size       5120k;
6. proxy_buffers           32 400m;
7. proxy_busy_buffers_size     2500m;
8. proxy_temp_file_write_size  1000m;

**Nginx API  .net configuration:**

server {
    listen 80;
    server_name  videoreceiver.kuwaitengineeringacademy.com;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:5m;
    ssl_session_tickets off;

    # certbot will place the files required for the HTTP challenge in the
    # webroot under the .well-known/acme-challenge directory. Therefore we must
    # make this path publicly accessible.
    location /.well-known {
            root  /var/www/html/learning-patform/video-receiver-service/;
    }

    location / {
        # Forward incoming requests to local tusd instance
        proxy_pass http://localhost:5022;

        # Disable request and response buffering
        proxy_request_buffering  off;
     #   proxy_buffering          off;
        proxy_http_version       1.1;
        #client_max_body_size 10000m;

        # Add X-Forwarded-* headers
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header         Upgrade $http_upgrade;
        proxy_set_header         Connection "upgrade";
        client_max_body_size     0;
    }
}

**User Scenario:**

The user enters the website example.com and navigates to the upload screen that uses **Uppy with tus client**
then the tus call API from receiving and uploading the video in the sub-domain (videoreceiver.example.com)

`import { Uppy, Dashboard, Tus, GoldenRetriever } from "https://releases.transloadit.com/uppy/v3.14.0/uppy.min.mjs"

initUppy();

function initUppy() {
    const uppy = new Uppy()
    uppy.setOptions({
        restrictions: {
            maxNumberOfFiles: 1,
            maxFileSize: '1e+9',
            allowedFileTypes: ['video/mp4,video/x-m4v,video/*', '.mp4']
        },
    });
    uppy.
        use(Dashboard, { target: '#uppy', inline: true, showProgressDetails: true }).
        use(GoldenRetriever).
        use(Tus, {
            endpoint: `${videoReceiever}files/`,
            allowedMetaFields: true,
            metadata: {
                'AuthData': document.getElementById('txtAuth').value,
                'videoDetailsData': document.getElementById('txtVideoDetails').value,
                'videoTitle': document.getElementById('txtVideoName').value
            },
            onChunkComplete: (chunkSize, bytesAccepted) => {

                openSuccessMessage('Congratulations! Your Video was uploded successfully. We are securing your video once we done the video will be show in you dashboad within 3 mins ');
                console.log('Tus onChunkComplete chunkSize', chunkSize);
                console.log('Tus onChunkComplete bytesAccepted', bytesAccepted);
            },
            onProgress: function (req) {

                console.log('Tus onProgress', req);
            },
            onBeforeRequest: function (req) {
                req.setHeader("AuthData", document.getElementById('txtAuth').value);
                req.setHeader("videoDetailsData", document.getElementById('txtVideoDetails').value);
                req.setHeader("videoTitle", document.getElementById('txtVideoName').value);
                if (!document.getElementById('txtVideoName').value)
                {
                    console.log('Tus onBeforeRequest txtVideoName', 'txtVideoName empty');

                    req.abort();
                    return;
                }
                console.log('Tus onBeforeRequest', req);

            },
            onSuccess: function (req) {
                console.log('Tus onSuccess', req);
            },
            onError: function (req) {
                console.log('Tus onError', req);

            },
            onShouldRetry: function (req) {
                console.log('Tus onShouldRetry', req);

            },
            onAfterResponse: function (req) {
                console.log('Tus onAfterResponse', req);

            },

        });

    uppy.on("success", (fileCount) => {
        console.log(`uppy success ${fileCount} files uploaded`);
    });
}

.net core  minimal API for receiving video

`
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAllPolicy", builder =>
    {
        builder
            .AllowAnyOrigin()
            .AllowAnyHeader()
            .AllowAnyMethod()
            .WithExposedHeaders(CorsHelper.GetExposedHeaders());

    });
});

app.Use((context, next) =>
{
  
    context.Features.Get<IHttpMaxRequestBodySizeFeature>().MaxRequestBodySize = null;
    return next.Invoke();
});

app.UseHsts();
app.UseHttpsRedirection();

app.MapTus("/files", async httpContext =>
{
    return new()
    {
        // This method is called on each request so different configurations can be returned per user, domain, path etc.
        // Return null to disable tusdotnet for the current request.

        // Where to store data?
        Store = app.Environment.IsProduction() ? new tusdotnet.Stores.TusDiskStore(@"/var/www/html/learning-patform/video-receiver-service/tusfiles") : new tusdotnet.Stores.TusDiskStore(@"E:\tusfiles"),
        // Store =  new tusdotnet.Stores.TusDiskStore(@"E:\tusfiles"),
        Events = new()
        {

            // What to do when file is completely uploaded?
            OnFileCompleteAsync = async eventContext =>
            {

                try
                {
                    tusdotnet.Interfaces.ITusFile file = await eventContext.GetFileAsync();
                    using Stream content = await file.GetContentAsync(eventContext.CancellationToken);

                    var authDataEncrypted = eventContext.HttpContext.Request.Headers["AuthData"].ToString();
                    var videoDetailsDataEncrypted = eventContext.HttpContext.Request.Headers["videoDetailsData"].ToString();
                    var videoTitle = eventContext.HttpContext.Request.Headers["videoTitle"].ToString();

                    Dictionary<string, tusdotnet.Models.Metadata> metadata = await file.GetMetadataAsync(eventContext.CancellationToken);

                    var result = await _uploadVideoService.UploadFile(videoDetailsDataEncrypted, authDataEncrypted, content, eventContext.CancellationToken, videoTitle);
                    if (result != null)
                    {
                       

                        await content.DisposeAsync();

                        var terminationStore = (ITusTerminationStore)eventContext.Store;
                        await terminationStore.DeleteFileAsync(file.Id, eventContext.CancellationToken);

                        //eventContext.HttpContext.Response.StatusCode = StatusCodes.Status200OK;
                        //await eventContext.HttpContext.Response.WriteAsJsonAsync(new { result, res, msg = "Ok" }, eventContext.CancellationToken);

                    }
                    else
                    {

                        logger.LogCritical($"Video Receiever UploadFile faild ");

                        await content.DisposeAsync();
                        var terminationStore = (ITusTerminationStore)eventContext.Store;
                        await terminationStore.DeleteFileAsync(file.Id, eventContext.CancellationToken);

                        //eventContext.HttpContext.Response.StatusCode = StatusCodes.Status400BadRequest;
                        //await eventContext.HttpContext.Response.WriteAsJsonAsync(new { result, res = 0, msg = "error" }, eventContext.CancellationToken);
                    }
                }
                catch (Exception ex)
                {

                    logger.LogCritical($"TUS Upload File Faild >> ::::: {ex.ToString()} ");

                }

            },

        }
    };
});
`

**Comment by Acconut** [comment]
From the Firefox screenshot it seems like the request is failing because CloudFlare is rejecting the request due to its body size. That would explain why smaller uploads work, but not bigger ones. Is there a setting with CloudFlare to disable this request limit? If so, I would recommend you to try it out.

Otherwise, you can work around this server limitation by setting `chunkSize` to a value of about 100 MiB. Then requests will be limited to this amount. See https://github.com/tus/tus-js-client/blob/main/docs/api.md#chunksize

**Comment by salahrzzaz** [comment]
Thank you, i already change the chunk size . Because i use cloud flare free plan and they have limitation

**Comment by Acconut** [comment]
Ok, it's great to hear that you found the solution. I will close this then.
