### ISSUE TITLE
It's not possible to declare onShouldRetry and fallback to the default behaviour

### ISSUE THREAD

**Issue by hahn-kev** [tus/tus-js-client#636]
**Is your feature request related to a problem? Please describe.**
I want to catch a specific server error and not retry, but now I lose online checking and the status code checking that happens by default.

**Describe the solution you'd like**
I would like to be able to detect and handle my error, then fallback to the default should retry implementation provided by the library.

**Describe alternatives you've considered**
I've tried to implement the same thing myself, but I don't want to rewrite all that code myself.

**Can you provide help with implementing this feature?**
One way to solve this would be to move the code [here](https://github.com/tus/tus-js-client/blob/64b58d0e5a10b434fafa6cd0d43d72e25f740b6e/lib/upload.js#L1029-L1030) into the defaultOptions as the default value for the `onShouldRetry` option. Then I could access the default function and call it inside my function.

**Additional context**
Maybe I should be doing error handling differently, please let me know if that's the case, I'm still learning about tus.

**Comment by Acconut** [comment]
> One way to solve this would be to move the code [here](https://github.com/tus/tus-js-client/blob/64b58d0e5a10b434fafa6cd0d43d72e25f740b6e/lib/upload.js#L1029-L1030) into the defaultOptions as the default value for the `onShouldRetry` option. Then I could access the default function and call it inside my function.

That is sensible proposal. I am not sure if there will be any complications if we basically set `defaultOptions.onShouldRetry = shouldRetry`, but we can try it out. Can you open a PR for this?
