### ISSUE TITLE
Failed because: Error: tus: unexpected response while uploading chunk, [...]

### ISSUE THREAD

**Issue by iamvyy** [tus/tus-js-client#638]
**Question**
Good day! I was facing this error while i was attempting to upload an image and store it to local filestore. 

```
Error: tus: unexpected response while uploading chunk, originated from request (method: PATCH, url: http://127.0.0.1:3000/files/285fbb6e-7871-4136-b403-bd1b90c67809, response code: 404, response text: {"statusCode":404,"message":"Cannot PATCH /files/285fbb6e-7871-4136-b403-bd1b90c67809","error":"Not Found"}, request id: n/a)
```

Ive been debugging but couldnt identify the issue. The file failed to upload however a json file + a 0 byte file was uploaded to the local folder. 

**tus-upload.html**

![Screenshot 2023-10-25 at 9 17 14 PM](https://github.com/tus/tus-js-client/assets/35486148/20b4f713-caa5-4319-973c-a323abf2a584)

**this is my nestjs service code**
![Screenshot 2023-10-25 at 9 17 54 PM](https://github.com/tus/tus-js-client/assets/35486148/5569987d-e96a-4f94-bc7d-61f6f451ff2d)

i followed the guideline given however im still hitting this error, apologies as im still quite new to this

**Setup details**
Please provide following details, if applicable to your situation:

- Runtime environment: NestJS , HTML 
- Used cdn for tus-js-client  - "https://cdn.jsdelivr.net/npm/tus-js-client@latest/dist/tus.min.js"
- Used tus server  : tus/server - "@tus/server": "^1.0.0",

**Comment by iamvyy** [comment]
![Screenshot 2023-10-25 at 9 34 22 PM](https://github.com/tus/tus-js-client/assets/35486148/ee21f6d7-a1f4-4523-b033-e107f2e1d29b)

this was the network status

**Comment by iamvyy** [comment]
![Screenshot 2023-10-25 at 9 36 59 PM](https://github.com/tus/tus-js-client/assets/35486148/b10c302c-1ddc-4cd2-8598-583b69ac1b80)
annddd this was my controoller

**Comment by Acconut** [comment]
You are uploading to `/upload/files`, but have tus-node-server configured with a path of `/files`. That could lead to problems. @Murderlon, what do you think?

**Comment by Murderlon** [comment]
That would indeed be my first guess.

**Comment by iamvyy** [comment]
hmmm upon changing im still getting the same error T.T

Failed because: Error: tus: unexpected response while uploading chunk, originated from request (method: PATCH, url: http://127.0.0.1:3000/upload/files/81a0f675-501d-4f50-9567-21061c9bcc58, response code: 404, response text: {"statusCode":404,"message":"Cannot PATCH /upload/files/81a0f675-501d-4f50-9567-21061c9bcc58","error":"Not Found"}, request id: n/a)

![Screenshot 2023-10-26 at 5 15 16 PM](https://github.com/tus/tus-js-client/assets/35486148/2cd5635a-93be-4807-8d96-08224fe52c64)

![Screenshot 2023-10-26 at 5 12 53 PM](https://github.com/tus/tus-js-client/assets/35486148/4199e97a-6518-4c38-a094-c5ea856dc71d)
![Screenshot 2023-10-26 at 5 13 05 PM](https://github.com/tus/tus-js-client/assets/35486148/30e9b3a1-359a-4a1d-b4ee-93101429fbbd)

**Comment by Acconut** [comment]
> PATCH /upload/files/81a0f675-501d-4f50-9567-21061c9bcc58

The URL looks better this time. But I don't know why this would cause a 404

**Comment by Murderlon** [comment]
Does it work if you remove your custom `namingFunction`? I'm also not sure what is going wrong.

**Comment by iamvyy** [comment]
![Screenshot 2023-10-26 at 6 19 17 PM](https://github.com/tus/tus-js-client/assets/35486148/4271f80b-10a3-4a49-a0c8-1c36d0962515)
![Screenshot 2023-10-26 at 6 19 44 PM](https://github.com/tus/tus-js-client/assets/35486148/107923c9-00f9-450a-9a0b-f1df4120e920)


unfortunately im still getting the same error, 

weird thing is im still able to upload to my local folder but its in weird format ,json and bytes file  , but with zero content

**Comment by Acconut** [comment]
The 500 error code means something different. Please open a new issue.

**Comment by nikosanif** [comment]
Hello @iamvyy, I am not sure if this is helpful, but it worked for me.

At your controller try to put `@All(['', '*'])` (add both routes).

**Comment by iamvyy** [comment]
Hi @nikosanif , yes All works! appreciate it !
