### ISSUE TITLE
Upload remembers wrong url when attempting upload to a new network address

### ISSUE THREAD

**Issue by acochrane** [tus/tus-js-client#65]
Uploads to network address 1 are working fine.

Upload fails trying to upload file to old network address after having loaded site at a new network address.
It looks like the client contacts the new address once to create the upload, but the patch requests, all hit the old address.

I'm under-experienced in javascript, but I think checking the network address from Storage against the network address in the address bar could be used to adapt to this change of host address.

I would be glad to make an attempt at a fix for myself, but I'm still a little fuzzy on exactly where to do the check, I'm thinking maybe somewhere inside the xhr.onload at upload.js:313

Any pointers?

**Comment by Acconut** [comment]
> It looks like the client contacts the new address once to create the upload, but the patch requests, all hit the old address.

Looks to me like that your tus server at the new address sends the tus-js-client an upload URL which points to the old address. What does your setup look like? How do you configure tus-js-client?

**Comment by acochrane** [comment]
I have a client using tus-js-client with the following uploader initialization:
`$("#inputFile").on('change', function(event) {
    var file = event.target.files[0];
    $("#inputFile").prop('readonly', true);
    var upload = new tus.Upload(file, {
	endpoint: "/videospheres/uploads/",
	retryDelays: [0, 1000, 3000, 5000],
	metadata: {"sphereid": $("#inputFile").data("sphereid"), "filename":file.name },
	chunkSize: 10000000,
	onError:function(error){
	    console.log("failed because " + error);
	    upload.abort();
	},
	onProgress:function(bytesUploaded, bytesTotal) {
	    var percentage = (bytesUploaded/bytesTotal*100).toFixed(2);
	    $("#newVideoModal progress").attr('value', percentage);
	},
	onSuccess: function() {
	    //	    console.log("download %s from %s", upload.file.name, upload.url);
	    $("#editThumbnailModalLabel").html("Thank you! Your video is being processed and the streaming player will be optimized shortly.<br>You can start filling in the metadata any time by selecting the settings on the black tile with the name you chose for this video.<br>Please refresh this page now.")
	    $("#successModal #message").html("")
	    
	    $("#successModal").modal('show');
	    
	    
	    
	}
    });

    upload.start();
});`

My server is written in go and is running on a vagrant instance.
Nginx is used to proxy port 80 traffic to the webserver port in the vagrant instance.

Incidentally, I changed the value of the proxy forward, and the whole setup started working, albeit slowly.

Is there any magic I can do to ensure the server in the vagrant instance is the server that is actually answering the pre-flight requests?

**Comment by Acconut** [comment]
> Incidentally, I changed the value of the proxy forward, and the whole setup started working, albeit slowly.

So, does it work for you now?

> Is there any magic I can do to ensure the server in the vagrant instance is the server that is actually answering the pre-flight requests?

Not much. Pre-flight requests are sent by the browser, so we as developers have no influence over them. Also they will be sent to the same URL as the endpoint.

**Comment by acochrane** [comment]
@Acconut Yes it works, I have some performance issue now that I think is unrelated to pre-flight checks.
 FWIW, everytime a chunk finishes sending, the response from the server takes 30-60 seconds, during which no data uploads.

But I think it's a vagrant writes to disk slowly issue.
