### ISSUE TITLE
RetryDelays: "Type 'null' is not assignable to type 'number[] | undefined'". But null is acceptable.

### ISSUE THREAD

**Issue by dmitryprusakov** [tus/tus-js-client#652]
**Bug description:**

Option _retryDelays_ [can be](https://github.com/tus/tus-js-client/blob/HEAD/docs/api.md#retrydelays) an array or null, but in type definitions null is not assignable.

Current [type](https://github.com/tus/tus-js-client/blob/eed7b9aa6e21be3b7ee44ab8f0e48ca36bf565ec/lib/index.d.ts#L47C6-L47C6
) for retryDelays: `retryDelays?: number[]`

![image](https://github.com/tus/tus-js-client/assets/46815138/128fc08a-a5ed-4797-aed3-7b1b141729ef)

@uppy/tus version: latest 3.4.0
tus-js-client version: latest 3.1.1

**To Reproduce**
Use latest 3.1.1 version of tus-js-client.

**Expected behavior**
No typescript error, null is acceptable for retryDelays.
Expected type: `retryDelays?: number[] | null`

**Comment by Acconut** [comment]
Thanks for reporting this issue. Can you open a PR to fix the type`/

**Comment by dmitryprusakov** [comment]
> Thanks for reporting this issue. Can you open a PR to fix the type`/

@Acconut , done!
Could you please check?
