### ISSUE TITLE
window is undefined when trying to run in worker file on browser

### ISSUE THREAD

**Issue by rashyad** [tus/tus-js-client#658]
**Describe the bug**
The bug is regarding the `window` global object that is available when running in browser. However, when trying to run the upload process in a worker thread on client side, the window object is not defined in the worker global scope. 

In the file /lib/browser/index.js, line 31 - 33, the code uses the window global object to check for `XMLHttpRequest` and `Blob` to determine the `isSupported` property. 

![image](https://github.com/tus/tus-js-client/assets/132123505/1286c8fe-5af2-4592-9505-44ebcbde74e7)

Running this in worker will return `window is not defined` since the code assume that `window` is available. I understand the thoughts here since its supposed to be running in browser. I supposed we should put a check instead of assuming that `window` is available.

**To Reproduce**
1. Run any web server of your choice, apache web server, node http-server etc so you can serve html and js files.
2. Create two js files, one as the worker file and another one as the parent to init the worker using `new Worker()`
3. Try to run the tus.Upload in the worker file and you will get the `window not defined` error in browser logs. You can copy the upload code part from  `/demos/browser/demo.js`

**Expected behavior**
The upload should work on both the main thread and worker thread on browser. I supposed we should not be assuming that window would always be defined or something..

Just to add,
I have it working locally where I modified the file `/lib/browser/index.js` like so,
![image](https://github.com/tus/tus-js-client/assets/132123505/7081c337-915c-4f9a-9a7f-8059286db7c3)

Built the code and it works fine. The upload works on both the main thread and worker thread.
However, this might not be the best fix.

**Comment by Acconut** [comment]
Thanks for the report! You are right that `window` does not exist in the environment for Web Workers. Maybe we should use `self` instead for detecting support: https://developer.mozilla.org/en-US/docs/Web/API/Window/self and https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/self

The following code could be a replacement without depending on `window`, although I didn't test it yet:

```
const isSupported = typeof self !== undefined && 'XMLHttpRequest' in self && 'Blob' in self && typeof Blob.prototype.slice === 'function'
```

Could you try it out and open a PR if it works?

**Comment by rashyad** [comment]
Tested your code and it works fine with worker. The `test-node` and `test-puppeteer` run just fine.
However, I did not manage to create a specific demo for worker or a specific test for worker.

Here is my PR https://github.com/tus/tus-js-client/pull/660

**Comment by rashyad** [comment]
May I know the status of this? Anything that I need to do on my side?

**Comment by Acconut** [comment]
I didn't have the time yet to try it out but I plan on doing so in the next few days

**Comment by jtag05** [comment]
I would also love to get this merged if it would solve this issue. If any additional help is required, I'm happy to lend a hand.

**Comment by Acconut** [comment]
I added a few more commits to your PR and merged it. Can you please test the latest main branch from GitHub and let me know if it works? If so, I can release a new version.

**Comment by rashyad** [comment]
Tested the main branch locally and works fine
