### ISSUE TITLE
Can onSuccess return the file address when the upload is successful?

### ISSUE THREAD

**Issue by mdxiaohu** [tus/tus-js-client#663]
Although onBeforeRequest and onAfterResponse have returned file addresses.
When these two methods are used, we cannot be certain whether the file has been uploaded.

According to general logic, once the file is successfully uploaded, the file address is obtained and stored in the database.
If there is an error, the current file address will not be stored.

If the file address is directly stored in the database without onSuccess triggering, user access may encounter errors. For example, a file upload error resulted in the file not being uploaded as expected.

Can the successfully uploaded file address be returned when onSuccess is triggered to avoid similar situations.

For example:
```
onSuccess(data = {}) {
    console.log('success', data.fileUrl )
},
```

**Comment by mdxiaohu** [comment]
I have reviewed some questions and responses regarding this method.

Will the onBeforeRequest method necessarily be triggered when onSuccess is triggered?
Can I determine the type of method in onBeforeRequest to determine if the upload was successful.

I don't know if my understanding is correct.

**Comment by mdxiaohu** [comment]
![Uploading hello.png…]()

**Comment by mdxiaohu** [comment]
![hello](https://github.com/tus/tus-js-client/assets/42248614/f700df65-3752-4ee3-813d-1ea72ee82e07)

**Comment by Acconut** [comment]
Have a look at the `upload.url` property (https://github.com/tus/tus-js-client/blob/main/docs/api.md#tusuploadurl). This might be what you are looking for.

**Comment by mdxiaohu** [comment]
Perhaps language translation may lead to misunderstandings.
To be precise, what I want to ask is the return parameter of onSuccess.

**Comment by mdxiaohu** [comment]
I may not have explained it clearly, but I think I should describe my problem again.


After uploading the file, the onSuccess method will be triggered.
But the onSuccess method does not have any return value.

I use the uppy open-source library in combination to upload multiple files.
In the absence of a return value for onSuccess, I don't know which file has already been uploaded.


The current plan is to have two solutions.

The first option:

Currently, it has been observed that onSuccess triggers onBeforeRequest before each trigger.

Can this be so that I can directly determine the return value in the onBeforeRequest method to distinguish which file is currently about to trigger onSuccess.

For example, onBeforeRequest returns the_ When the method value is PATCH, I assume that the current file is about to trigger onSuccess.
So, if I save the value of the returned file address in this, the upload will be completed in one go.

```
onBeforeRequest(req, file) {
    console.log(req, file, 'req, file')
    if (req._method == 'PATCH' && file.source) {
	    this.saveObj = {
		    fileId: ile.source,
		    fileUrl: req._url
	    }
    }
},
```

The second option: 

I don't know if onSuccess can return parameters like onBeforeRequest.
Just like below.

```
onSuccess(req, file) {
    console.log(req, file, 'req, file')
},
```

**Comment by Acconut** [comment]
I am still confused about what you are actually trying to achieve here. What do you mean by "file address"? Are you trying to retrieve some data returned from the server? Or do you just want to identify which files are uploaded when Uppy emits an event?

**Comment by mdxiaohu** [comment]
![b](https://github.com/tus/tus-js-client/assets/42248614/bcc01a80-22ad-492f-b227-389cd2ea4cb7)
When the file is successfully uploaded, a URL will be returned, which is the address of the file on the server.

**Comment by Acconut** [comment]
tus-js-client exposes this URL through its `Upload#url` property, as explained above. I am not sure how you can access this URL through Uppy. That question is best asked to the Uppy engineers directly.

However, it seems like Uppy emit a special event that includes the URL once the upload is finished: https://github.com/transloadit/uppy/blob/df11d2bc83eea2894e294f69947ba779e6b60711/packages/%40uppy/tus/src/index.js#L270-L277

**Comment by mdxiaohu** [comment]
You are really amazing, thank you very much.
I once thought that "upload-success" would only take effect when using "@upload/xhr-upload".

**Comment by Acconut** [comment]
Glad I could help!

> I once thought that "upload-success" would only take effect when using "@upload/xhr-upload".

Maybe that's something that can be improved in the documentation, @arturi @Murderlon @aduh95?
