### ISSUE TITLE
removeFingerprintOnSuccess not working on multiple files

### ISSUE THREAD

**Issue by Aztarok** [tus/tus-js-client#667]
I have this code with uppy, and it works on uploading one file, but when I try to upload multiple files at the same time I get them uploaded to supabase but I get an error on the client. I tried to set removeFingerprintOnSuccess to true but it only removes the first file from localStorage.

code:
const [uppy] = useState(() =>
        new Uppy({
            allowMultipleUploadBatches: false,
            restrictions: {
                maxNumberOfFiles: 4,
                allowedFileTypes: ["image/*"],
                maxFileSize: 10 * 1000 * 1000
            }
        }).use(Tus, {
            endpoint:
                process.env.NEXT_PUBLIC_SUPABASE_URL +
                "/storage/v1/upload/resumable",
            onBeforeRequest,
            allowedMetaFields: [
                "bucketName",
                "objectName",
                "contentType",
                "cacheControl"
            ],
            removeFingerprintOnSuccess: true,
            limit: 4
        })
    );

error:
Uncaught (in promise) Error: tus: unexpected response while terminating upload, originated from request (method: DELETE, url: https://supabase.co/storage/v1/upload/resumable/cG9zdEltYWdlcy9iOWUyMjgzYS05NzRkLTRmYTEtYmFiZC0yNDkyOTAyN2ViOGUvNGNkYzQ4NzEtYTZiNi00NTZiLWExOGYtNmQ0NDdjNWUyMjBiL21haW5fSnVsaWFfc3BlY192Mi5wbmcvYmNmOTEwMzUtN2IzZi00Y2U0LTg4ZDgtNTI2NGNhOGRhMmM0, response code: 404, response text: The file for this url was not found
, request id: n/a)

**Comment by Aztarok** [comment]
Tested commenting out the uppy on success function and it works perfectly but I don't know why:
// uppy.on("upload-success", () => {
    //     uppy.cancelAll();
    //     if (inputRef.current) {
    //         inputRef.current.value = "";
    //     }
    
    //     document.getElementById("trigger-close")?.click();
    //     router.refresh();
    // });

**Comment by Aztarok** [comment]
Ok I changed the "upload-success" to "complete" and it works with 4 files and no errors lets gooo

**Comment by Acconut** [comment]
Glad that you found the solution. Please ask similar Uppy-related questions in their repository first in the future :)
