### ISSUE TITLE
Better online / offline retry support

### ISSUE THREAD

**Issue by psi-4ward** [tus/tus-js-client#67]
If `navigator.onLine === false` the error callback fires immediately which is imho not good.
We should wait for the online event.

**Comment by Acconut** [comment]
I disagree, tus-js-client is meant to be a low-level uploading library. We thought about your idea previously but rejected it as it would require adding timeouts for how long to wait, events to notify the user about the network interrupting etc. This would make this project more complex then we wanted. If you are looking for a more fully-features uploader, you may have a look at https://uppy.io/ which, I believe, monitors the online status.

**Comment by psi-4ward** [comment]
Hmm okay. It is possible to handle this case using a custom onError method wich restartes the upload onOnline

**Comment by Acconut** [comment]
That's exactly how we imagined it :)
