### ISSUE TITLE
Don't remove fingerprint on server errors?

### ISSUE THREAD

**Issue by psi-4ward** [tus/tus-js-client#68]
Hi,

in [upload.js#L314](https://github.com/tus/tus-js-client/blob/master/lib/upload.js#L314) we trigger a `Storage.removeItem(this._fingerprint);` even on server errors (`statusCode >= 500`).
But probably there's only a short service outage and it could be resumed after the backend is up again. 

I think we should only remove the stored fingerprint on client errors (< 500). What do you think?

**Comment by Acconut** [comment]
> I think we should only remove the stored fingerprint on client errors (< 500). What do you think?

Good idea, would you mind opening a PR for this?

**Comment by psi-4ward** [comment]
So many PR's, so less time :\
I'll see what I can do

**Comment by Acconut** [comment]
Unfortunately the same applies to me or else I would have already taken care of it :) If you need any help, I can provide assistance, of course!
