### ISSUE TITLE
Change request method to PATCH

### ISSUE THREAD

**Issue by hotscope** [tus/tus-js-client#682]
Hello,

I'd like to change the request method to PATCH. How Do I do that?

**Comment by Acconut** [comment]
I don't understand what you mean exactly. Can you please elaborate and explain your thinking?

**Comment by hotscope** [comment]
In the network tab it shows I'm sending a POST request when I start the tus upload. I'd like tus to send a PATCH request instead.

**Comment by hotscope** [comment]
Ok, I got it now I had to read a little bit more into it!
