### ISSUE TITLE
HttpRequest/HttpResponse.getHeader have incorrect return type

### ISSUE THREAD

**Issue by SpecLad** [tus/tus-js-client#706]
**Describe the bug**
`getHeader` is defined as following:

```ts
  getHeader(header: string): string
```

This means that an implementation of this method can't return anything if there is no such header.

**To Reproduce**
N/A: this is a type definition problem

**Expected behavior**
The return type should be something like `string | undefined` or `string | null`.

**Setup details**
Please provide following details, if applicable to your situation:

- Runtime environment: N/A
- Used tus-js-client version: 4.1.0
- Used tus server software: N/A

**Comment by Acconut** [comment]
Thank you for bringing this up. In the TypeScript rewrite we also allowed it to return undefined: https://github.com/tus/tus-js-client/pull/683/files#diff-7aa514e8766689bfea8a2264cb7dfc9140125a8b34e7eb5876b542ed6e1b3addR120 The PR is not yet merged, but we can backport this change.
