### ISSUE TITLE
HttpRequest.setHeader is being called with an incorrect parameter type, number insted of string

### ISSUE THREAD

**Issue by DraganDanicic** [tus/tus-js-client#708]
**Describe the bug**
In my implementation of the _HttpRequest_ interface, the _setHeader(header, value)_ method is being called with a number as the second parameter. This disrupts the logic of Angular's HttpClient, which I've used as the request handler.

**To Reproduce**

1. Implement _HtttpRequest_ with Angular's _HtttpClient_, 
2. also implement _HttpStack_ and initialise it using the instance from step 1
3. Instance from step 2 to should be passed to _tus.Upload_ constructor as _httpStack_ option
4. Try now uploading a file with  _tus.Upload_ instance
5.  File upload will fail with  **TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a.....**
6. Error is thrown by Angular's _http.mjs_ script because it can not process number value

<img width="1556" alt="Screenshot 2024-08-23 at 12 30 09" src="https://github.com/user-attachments/assets/3f9899e0-037b-4972-a29e-f96f851d8c24">

**Expected behavior**
Function call of _HttpRequest.setHeader_ should receive _string_ as second argument as per defintion of method in interface.

**Setup details**
- Runtime environment: Browser, Angular
- Used tus-js-client version: 4.1.0
- Used tus server software: tusproject/tusd:v2.4.0

**Comment by Acconut** [comment]
Thanks for bringing this up. I just saw that you already started working on a PR: https://github.com/tus/tus-js-client/pull/709 Thank you very much for this!

**Comment by Acconut** [comment]
This is fixed in the 4.2.0 release.
