### ISSUE TITLE
Incorrect type for onSuccess callback

### ISSUE THREAD

**Issue by rizametovd** [tus/tus-js-client#716]
**Describe the bug**
According to docs `onSuccess` callback should accept a `payload`, but in `index.d.ts` the signature for `onSuccess` is:
`onSuccess?: (() => void) | null`

- Browser
- Used tus-js-client version: 4.2.0

**Comment by Acconut** [comment]
Thanks for reporting it. Should be fixed in https://github.com/tus/tus-js-client/releases/tag/v4.2.1.
