### ISSUE TITLE
error.originalRequest.getHeader returns undefined

### ISSUE THREAD

**Issue by rizametovd** [tus/tus-js-client#729]
**Describe the bug**
`error.originalRequest.getHeader(header)` returns undefined

The `getHeader` method is available on `error.originalRequest` but it always returns undefined.

**Expected behavior**
Expected to get specified request header e.g. `error.originalRequest.getHeader('accept')`

**Setup details**
- Runtime environment: Browser
- Used tus-js-client version: 4.2.3

**Comment by Acconut** [comment]
Did you check whether the CORS policy allows you to access the Accept header field?

**Comment by Acconut** [comment]
If not, the dev tools console will likely contain a warning message about this.

**Comment by rizametovd** [comment]
I don't see any console CORS errors/warning.

```
  const request = error.originalRequest.getHeader('content-length'); // undefined
  const response = error.originalResponse?.getHeader('content-length'); // works fine
```

**Comment by Acconut** [comment]
Ah, your talking about request headers, not response headers. I missed that at first.

JavaScript does not provide a way to access request headers at all. In tus-js-client we partially work around this by storing the headers that we explicitly set, so they can be retrieved using `getHeader`:

https://github.com/tus/tus-js-client/blob/bb8862e139b04aee59336c00a2f0806c1719c201/lib/browser/httpStack.js#L29-L36

But headers that were not explicitly set cannot be retrieved. So fetching the Content-Length request header will not be possible. The Fetch API seems to have a debug API for accessing more details about requests but I haven't looked into this further.
