### ISSUE TITLE
Wrong status code check when Location header is set?

### ISSUE THREAD

**Issue by jezzdk** [tus/tus-js-client#731]
**Question**
I'm trying to implement the direct creator uploads method from Cloudflare, and I'm following [the guide](https://developers.cloudflare.com/stream/uploading-videos/direct-creator-uploads/#resumable-uploads), but I've run into some problems. 

When my endpoint returns a "Location:" header, the response code is automatically set to 302 because that header specifies a redirect. However, the tus-js-client only checks [if the status code is 200](https://github.com/tus/tus-js-client/blob/27a57934e28e46afb0641e5bbfebac1fdf310a88/lib/upload.js#L607) or throws an error. 

I'm using PHP on the backend, and PHP forces a 302 if the "Location:" header is set. It also seems to be the [standard behavior](https://www.ietf.org/rfc/rfc2616.txt). In any case I'm not able to force a status code of 200, so I'm not able to use this upload method even though all the documentation says I should. Is there something I can do to make this work?

**Setup details**
Please provide following details, if applicable to your situation:

- Runtime environment: Browser, PHP
- Used tus-js-client version: tus-js-client@4.2.3
- Used tus server software: Cloudflare Stream

**Comment by Acconut** [comment]
The `Location` header is not exclusive used for redirects with 3xx responses. It can also be used with the 201 status code to indicate the URL of a newly created resource, which how tus uses the header. This is in line with RFC 9110, which defines the schematics of HTTP and, in particular, the Location header: https://www.rfc-editor.org/rfc/rfc9110.html#name-location (As a brief side note: RFC 2616 has been obsoleted through many revisions, so it's better to use the newer RFCs that replaced it).

From the standard's point of view, tus' use of Location and 201 is not unusual or incorrect. I would suggest you to fix the PHP part generating the response. It appears odd to me that PHP would not allow you to customize the status code.

**Comment by jezzdk** [comment]
Thanks for the reply. I didn't think about setting the status code to 201 instead of 200, but PHP allows me to do that and that actually makes it work.
