### ISSUE TITLE
onSuccess arguments

### ISSUE THREAD

**Issue by mhf-ir** [tus/tus-js-client#83]
There is no upload id for onSuccess event i use regex parse the url and get last hash for uploaded id. but better to have
```
onSuccess(uploadedData) {

}
```

**Comment by Acconut** [comment]
As you correctly mentioned, you can access the upload URL using [Upload#url](https://github.com/tus/tus-js-client#tusuploadurl). However, the tus **protocol** does not have an upload ID, but just the concept of an upload URL. The upload ID is just a common **implementation** detail used by most tus servers and, therefore, it's not really possible to extract such IDs, if they exist.

Furthermore, if you explain your use case, I may be able to help you to work around this limitation.
