### ISSUE TITLE
Tus js client dosnt follow endpoint host port and use default port

### ISSUE THREAD

**Issue by mhf-ir** [tus/tus-js-client#85]
I use my endpoint to special port for testing mode. `https://example.tld:3434/app/upload`
Process start on this HTTP methods after first POST method OPTIONS WILL SEND on `default` port for host not the given `endpoint`. 
```
Request URL:https://example.tld:3434/app/upload
Request Method:POST

Request URL:https://example.tld/app/upload/c9930f642a549a0dd4380129a49cada2
Request Method:OPTIONS

Request URL:https://example.tld/app/upload/c9930f642a549a0dd4380129a49cada2
Request Method:PATCH
```

**Comment by Acconut** [comment]
This is likely not a problem with tus-js-client but instead I believe the server is not properly configured, which causes it to respond with the `https://example.tld/app/upload/c9930f642a549a0dd4380129a49cada2` URL after the POST request.

What tus server are you using? Are you using a proxy in front of it? If you are using tusd, did you follow these instructions: https://github.com/tus/tusd#can-i-run-tusd-behind-a-reverse-proxy?

**Comment by mhf-ir** [comment]
I use nodejs version seems be there is no options behinde proxy. i set this nginx proxy configuration that other nginx serve nodejs tus server:
```
location /sampleproxypath {
  rewrite ^/sampleproxypath$ /sampleproxypath/ permanent;
  rewrite ^/sampleproxypath(.*) $1 break;
  proxy_ssl_verify off;
  proxy_pass https://127.0.0.1:443;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Port $server_port;
  proxy_set_header X-Forwarded-Base-Path '/sampleproxypath';
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
}
```

**Comment by Acconut** [comment]
Unfortunately, I do not have much experience with the tus-node-server. Would you mind opening an issue at its repository  where you can most likely get better help: https://github.com/tus/tus-node-server/issues

**Comment by jeremyckahn** [comment]
I ran to this issue as well. In case it's helpful to anyone else, I resolved it by setting this for my [`generateUrl` option for `@tus/server`](https://github.com/tus/tus-node-server/tree/main/packages/server#optionsgenerateurl):

```ts
import { Server } from '@tus/server'

// ...

const tusServer = new Server({
  generateUrl: (_request, { host, id, path, proto }) => {
    return `${proto}://${host}:${process.env.WHATEVER_YOUR_TUS_SERVER_PORT_IS}${path}/${id}`
  },
  // ...
})
```
