### ISSUE TITLE
TypeScript type definition file

### ISSUE THREAD

**Issue by KhaledSMQ** [tus/tus-js-client#87]
There is any plan to support TypeScript type definition file for typescript in the future or if any one already created support file.

**Comment by Acconut** [comment]
We personally do not use TypeScript but there are definition files available in the DefinitelyTyped
 repository: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/tus-js-client

**Comment by KhaledSMQ** [comment]
Thank you

**Comment by Acconut** [comment]
You're welcome :)

**Comment by Acconut** [comment]
Thanks for letting us know, I opened a pull request to add the missing definitions: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30384

**Comment by Acconut** [comment]
@nbonavia The definitions in DefinitelyTyped have been updated.

**Comment by freiondrej** [comment]
@Acconut hello, are you planning to update the typings for v2, or should I resort to 1.8 for now?

**Comment by Acconut** [comment]
@freiondrej I added the definitions directly to tus-js-client in https://github.com/tus/tus-js-client/commit/3774a74b187ac1764ad83ec2bedc1f0fd23d68aa. Please install the latest version of tus-js-client directly from github and see if they work before I do a real release.

**Comment by freiondrej** [comment]
@Acconut thank you. Unfortunately when trying this, I'm getting `Can't resolve 'tus-js-client'` (I'm using webpack). It surely can be something on my end. But for now I'll stick to the 1.8.0 version which ran just fine for me.

**Comment by Acconut** [comment]
Version 2.1.0 has been released with the definition file included. Maybe you want to give it another try. I would recommend using the latest version since the 1.x branch won't receive updates in the future.

**Comment by freiondrej** [comment]
@Acconut I just installed 2.1.1 and it seems to be working perfectly. Thank you very much!

**Comment by brootle** [comment]
Can anyone post minimalistic example of using tus-js-client with TypeScript? I am trying to use "tus-js-client": "^2.2.0"

I am getting file from event

`const file = e.currentTarget.files && e.currentTarget.files[0]`

First I got this error _Argument of type 'File | null' is not assignable to parameter of type 'File | Blob | Pick<ReadableStreamDefaultReader<any>, "read">'._ In the line below

`var upload = new tus.Upload(file, {`

to fix it I used

`var upload = new tus.Upload(file as File, {`

and now I am having _Object is possibly 'null'.ts(2531)_  in

`
          metadata: {
              filename: file.name,
              filetype: file.type
          },
`

I am new to TypeScript, but looks like something is missing in variable definitions. So if somebody can show me the way of implementing example from https://www.npmjs.com/package/tus-js-client that would be super awesome!

**Comment by Acconut** [comment]
@brootle You are on the right way. The `file` variable has the type `File | null` but tus-js-client does not accept `null` values in the constructor. So that's not a missing definition on our end.

I would recommend you to add a check before calling tus-js-client to make sure that `file` is not `null` and you only pass `File` instances to tus-js-client.

**Comment by brootle** [comment]
@Acconut you are absolutely right, adding _**file !== null**_ check before calling **_new tus.Upload(...)_** fixes all TypeScript errors and example from npm now runs as it is without any modifications
