### ISSUE TITLE
Optional endpoint if uploadUrl is provided

### ISSUE THREAD

**Issue by goto-bus-stop** [tus/tus-js-client#94]
Currently when you provide an uploadUrl but no endpoint, tus-js-client throws an error because the endpoint is a required option. However, this seems unnecessary when an uploadUrl is already available: the endpoint is used to create a new tus upload, but if you have an uploadUrl you have also already created a tus upload.

A practical example is the new tus upload api from vimeo. Vimeo creates the upload internally and only gives you the uploadUrl you need to upload to. There is no /files/ endpoint that you can use to create a new upload; this is instead done by sending a vimeo API request to create a new video resource. Currently, to use the tus-js-client with the vimeo api, you have to provide a fake endpoint value.

```js
new tus.Upload({
  endpoint: 'https://api.vimeo.com/whatever-fake'
  uploadUrl: response.upload.upload_link
})
```

It seems to me that the endpoint option can be ignored in this situation.

**Comment by Acconut** [comment]
I finally found the time to work on this, many apologies for the delay on my side. Now, the endpoint option is not mandatory any more if uploadUrl is provided. Would you be so kind and test if it works properly for you before I publish a new release?

**Comment by goto-bus-stop** [comment]
Works here, thanks!

**Comment by Acconut** [comment]
FYI, tus-js-client v1.5.0 has been released.
