### ISSUE TITLE
Delete the fingerprint on success.

### ISSUE THREAD

**Issue by mperrando** [tus/tus-js-client#97]
https://github.com/tus/tus-js-client/blob/ebc5189eac35956c9f975ead26de90c896dbe360/lib/upload.js#L441

Take into account the following use case.

"After a file has been completely uploaded, it may happens that the user deletes it from the server, and then the same user decides to upload it again"

In such a case, the new file should be treated as a brand new file, with a new id, but if we don't remove the fingerprint from the storage, the client tries to upload using the same id.

Furthermore, the local storage keeps growing while the user loads files successfully!

The idea is to add something like the following, what do you think about it?

```
if (this.options.resume ) {
    // Remove stored fingerprint and corresponding endpoint,
    // a new upload of the same file must be treated as a different file
    Storage.removeItem(this._fingerprint);
}
```

**Comment by Acconut** [comment]
> "After a file has been completely uploaded, it may happens that the user deletes it from the server, and then the same user decides to upload it again"
> In such a case, the new file should be treated as a brand new file, with a new id, but if we don't remove the fingerprint from the storage, the client tries to upload using the same id.

This is true but no the full story. When tus-js-client tries to resume an upload which has been deleted from the server it will remove the fingerprint from its storage and start a brand new upload (see
https://github.com/tus/tus-js-client/blob/master/lib/upload.js#L335-L361). Therefore this scenario is not really a big problem, IMO.

> the local storage keeps growing while the user loads files successfully!

I agree, this could be a problem. Even if the fingerprint per upload is small, it will accumulate over this.

> The idea is to add something like the following, what do you think about it?

I like it, would you be able to open a PR for this?
