### ISSUE TITLE
Files tus.js and tus.min.js are different and work differently

### ISSUE THREAD

**Issue by MiroslavMerinsky** [tus/tus-js-client#99]
Hi,

I tested uploading file to the vimeo.com. While uploading, tus.min.js uses POST method instead PATCH for uploading. I've started debugging source code and noticed differences between source code in tus.min.js and on github. I compared tus.js and tus.min.js in the same package and there are also differencies. 

I was surprised  when the tus.js works properly.

Thank you for minify process correction

Best Regards,

Miroslav

**Comment by kvz** [comment]
Closes by accident or on purpose?

**Comment by MiroslavMerinsky** [comment]
Hi,

I realized there is no relation between reported  POST/PATCH error and the minified file. 

Best Regards,

Miroslav

**Comment by kvz** [comment]
Okay, as far as I understand Vimeo creates an endpoint for you and so does not require a POST. We attempted Vimeo uploads with uppy.io and created this issue to accommodate https://github.com/tus/tus-js-client/issues/94
